Repository wildfly/wildfly-core, pull requests merged in 2018-02, with the labels that each got.

#3091 WFCORE-3586 - issues with adding jmx to embedded HC started with empty config
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  patching/src/main/java/org/jboss/as/patching/management/PatchIntegrationFactory.java
Labels: ready-for-merge

#3077 [WFCORE-3555] Pipe with echo commad gives incorrect result
  cli/src/main/java/org/jboss/as/cli/handlers/EchoVariableHandler.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/PipeTestCase.java
Labels: ready-for-merge

#3030 [WFCORE-3073] Invoke the SuspendController if the BootstrapImpl shutd…
  server/src/main/java/org/jboss/as/server/BootstrapImpl.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/ProcessStateListenerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Labels: ready-for-merge

#3066 [WFCORE-3541] ScramDigestPassword into set-password operation
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
Labels: security

#3089 backport fixes
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleMode.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementRootConsoleRedirectHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/resources/StoppedServerResource.java
  logging/src/main/java/org/jboss/as/logging/deployments/AbstractLoggingDeploymentProcessor.java
  pom.xml
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingTransformers.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformersTestCase.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerManagementTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/console/WebConsoleRedirectionTestCase.java
Labels: 3.x

#2949 [WFCORE-3305][WFCORE-3425] Add more runtime operations to the Elytron key-store resource for advanced KeyStore manipulation
  elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
  elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/Readme.txt
  elytron/src/test/resources/org/wildfly/extension/elytron/test-cert-chain-reply.cert
  elytron/src/test/resources/org/wildfly/extension/elytron/test-exported.cert
  elytron/src/test/resources/org/wildfly/extension/elytron/test-single-cert-reply.cert
  elytron/src/test/resources/org/wildfly/extension/elytron/test-trusted.cert
  elytron/src/test/resources/org/wildfly/extension/elytron/test-untrusted-cert-chain-reply.cert
  elytron/src/test/resources/org/wildfly/extension/elytron/test-untrusted.cert
  elytron/src/test/resources/org/wildfly/extension/elytron/test.keystore
Labels: Feature, security

#3098 WFCORE-3594 Reload is racey with regard to reading the process state
  controller/src/main/java/org/jboss/as/controller/operations/common/ProcessReloadHandler.java
Labels: ready-for-merge

#3097 WFCORE-3593 Make sure the dependent module is resolved first when add…
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
Labels: ready-for-merge

#2963 [WFCORE-3441] Undeprecate
  controller/src/main/java/org/jboss/as/controller/SubsystemRegistration.java
Labels: ready-for-merge

#3013 [WFCORE-3483] Deprecate PathAddress.navigate and remove, replace controller catches of NoSuchElementException with Resource.NoSuchResourceException
  controller/src/main/java/org/jboss/as/controller/PathAddress.java
  controller/src/main/java/org/jboss/as/controller/RestartParentResourceHandlerBase.java
  controller/src/main/java/org/jboss/as/controller/RestartParentWriteAttributeHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ServerGroupDeploymentReplaceHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java
Labels: ready-for-merge

#3113 [WFCORE-3582] Upgrade XNIO to 3.6.2.Final
  pom.xml
Labels: ready-for-merge

#3112 [WFCORE-3610] Upgrade JBoss Modules to 1.7.0.Final
  pom.xml
Labels: ready-for-merge

#3111 [WFCORE-3604] Attribute required-attributes of Elytron x500-attribute-principal-decoder cannot be added to configuration
  elytron/src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
  elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
Labels: ready-for-merge

#3108 [WFCORE-3609]:Fix milliseconds format in configuration changes operation date
  controller/src/main/java/org/jboss/as/controller/ConfigurationChangesCollector.java
Labels: ready-for-merge

#3110 WFCORE-3607 WFCORE-3606 [JDK9 & 10] marshalling upgrade & fixes
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling/river/main/module.xml
  deployment-scanner/pom.xml
  pom.xml
Labels: ready-for-merge

#3130 WFCORE-3636 Undertow 2.0.0.Final
  pom.xml
Labels: ready-for-merge

#3131 [WFCORE-3633]: Read only mode is not properly supported for domain.
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ReadOnlyModeTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Labels: ready-for-merge

#3062 [WFCORE-3540] hardcode terminal width and height to avoid malformed t…
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/util/SimpleTable.java
Labels: ready-for-merge

#3127 [WFCORE-3563] Could not enable application deployment on two server g…
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/EnableCommand.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/DeployAllDomainTestCase.java
Labels: ready-for-merge

#3132 Fix for WFCORE-3640, CLI output swallowed with script + prompting
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
Labels: 4.x, ready-for-merge

#3134 [WFCORE-3641] Upgrading JBoss MSC to 1.3.1.Final.
  pom.xml
Labels: 4.x, ready-for-merge

#3124 [WFCORE-3579] LocalClient should establish an AccessAuditContext for …
  controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
  core-security/implementation/src/main/java/org/jboss/as/core/security/AccessMechanism.java
Labels: 4.x, security

#3144 [WFCORE-3653] Upgrade JBoss Marshalling to 2.0.4.Final
  pom.xml
Labels: 4.x, ready-for-merge

#3143 Fix for WFCORE-3649. CLI, --replace advertised for legacy command
  cli/src/main/java/org/jboss/as/cli/handlers/DeployHandler.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractDeployContentCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/DeployFileCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/DeployUrlCommand.java
Labels: 4.x, ready-for-merge

#3133 Fix for WFCORE-3637, upgrade to aesh-readline 1.5
  pom.xml
Labels: 4.x, ready-for-merge
