Repository wildfly/wildfly-core, pull requests merged in 2018-06, with the labels that each got.

#3248 [WFCORE-3795]: ReadFeatureDescription doesn't return ObjectAttributeDefinition capabilities
  controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
  controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
Labels: 6.x, ready-for-merge

#3274 [WFCORE-3817] Eliminating usages of deprecated ServiceListeners.
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/UninterruptibleCountDownLatch.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ProcessReloadHandler.java
  server/src/main/java/org/jboss/as/server/BootstrapImpl.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
Labels: 6.x, ready-for-merge

#3316 [WFCORE-3864] Switch to using WildFly Common byte and code point iterators
  cli/pom.xml
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/util/FingerprintGenerator.java
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/security/RealmIdentityManager.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesCallbackHandler.java
  elytron/src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLContextResource.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLSessionDefinition.java
Labels: 6.x, ready-for-merge

#3332 Fix for WFCORE-3829, ReloadRedirectTestCase failing with ibm jdk
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/ManagementDisableSSLCommand.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
Labels: 6.x, ready-for-merge

#3335 [WFCORE-3896] Fix custom-formatter descriptions.
  logging/src/main/resources/org/jboss/as/logging/LocalDescriptions.properties
Labels: ready-for-merge

#3331 [WFCORE-3898] Upgrade PicketBox to 5.1.0.Final
  pom.xml
Labels: 6.x, ready-for-merge

#3339 Fix for WFCORE-3844, CLI upgrade to aesh 1.5
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GrepTestCase.java
Labels: ready-for-merge

#3342 [WFCORE-3902] Support Maven staged repositories
  model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
Labels: ready-for-merge

#3336 [WFCORE-3868] Notify the suspend listener when timeout is 0
  server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
  server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
Labels: ready-for-merge

#3337 [WFCORE-3559] Remove FilePermissionTestCase.testFileDefaultPermissions
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/FilePermissionTestCase.java
Labels: ready-for-merge

#3346 Fix for WFCORE-3910, CLI remove dependency on jdk.jconsole
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
Labels: ready-for-merge

#3333 [WFCORE-3830] standardize handling of JAVA_OPTS in .ps1 scripts.
  core-feature-pack/src/main/resources/content/bin/domain.conf.ps1
  core-feature-pack/src/main/resources/content/bin/domain.ps1
  core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
  core-feature-pack/src/main/resources/content/bin/standalone.ps1
Labels: ready-for-merge

#3344 [WFCORE-3907] Rename wildfly-component-matrix-builder to
  component-matrix-builder/pom.xml
Labels: ready-for-merge

#3350 WFCORE-3918 Services created by extension index service is not part o…
  server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
Labels: ready-for-merge

#3357 [WFCORE-3102]: CloseableLocalClient
  controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
Labels: ready-for-merge

#3355 [WFCORE-3922] add staged-releases profile
  pom.xml
Labels: ready-for-merge

#3353 Revert "[WFCORE-3898] Upgrade PicketBox to 5.1.0.Final"
  pom.xml
Labels: ready-for-merge

#3349 [WFCORE-3915] Do not deploy testsuite modules
  testsuite/shared/pom.xml
  testsuite/test-runner/pom.xml
  testsuite/vault-test-feature-pack/pom.xml
Labels: ready-for-merge

#3358 [WFCORE-3924] Add Apache License v2 to the README
  README.md
Labels: ready-for-merge

#3361 [WFCORE-3678] Upgrade to picketbox 5.0.3
  pom.xml
Labels: ready-for-merge

#3360 [WFCORE-3928] Put exclusion groupId and artifactId in the correct order
  pom.xml
Labels: ready-for-merge

#3216 WFCORE-3751 DefaultCapabilityReferenceRecorder generates wrong dependent name if corresponding RuntimeCapability uses a dynamic name mapper
  controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/AbstractBoottimeAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/AbstractRemoveStepHandler.java
  controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
  controller/src/main/java/org/jboss/as/controller/ReloadRequiredAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/ReloadRequiredRemoveStepHandler.java
  controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
  controller/src/main/java/org/jboss/as/controller/resource/AbstractSocketBindingResourceDefinition.java
  controller/src/test/java/org/jboss/as/controller/CapabilityReferenceRecorderTest.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessIdentityResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/AggregateComponentDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/AggregateRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/FilteringKeyStoreDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/LdapKeyStoreDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/LdapRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
  host-controller/pom.xml
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/SocketBindingGroupResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/ProfileResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/DomainControllerWriteAttributeHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/RemoteDomainControllerAddHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ProfileIncludesHandlerTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ReloadRequiredServerTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerGroupOperationsTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/SocketBindingGroupIncludesHandlerTestCase.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/TestHostCapableExtension.java
Labels: ready-for-merge

#3363 Fix for WFCORE-3903, upgrade aesh 1.6, readline 1.9 and extensions 1.5
  cli/src/main/java/org/jboss/as/cli/impl/CLICommandCompleter.java
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/MoreTestCase.java
Labels: ready-for-merge

#3338 [WFCORE-3897] set explicitly domain model to available before domain ops boot up.
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnectionService.java
Labels: ready-for-merge

#3343 [WFCORE-3806] Eliminating dead code.
  controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
Labels: ready-for-merge

#3318 [WFCORE-3866] CLI does not need an MSC dependency to function as the …
  cli/pom.xml
  cli/src/main/java/org/jboss/as/cli/embedded/EmbeddedControllerHandlerRegistrar.java
Labels: 6.x, ready-for-merge

#3366 Fix for WFCORE-3935, CLI, revisit modular context detection
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/EmbeddedControllerHandlerRegistrar.java
  cli/src/main/java/org/jboss/as/cli/impl/SecurityActions.java
Labels: ready-for-merge

#3368 [WFCORE-3941] elytron-tool.sh script detects JBOSS_HOME incorrectly
  core-feature-pack/src/main/resources/content/bin/elytron-tool.sh
Labels: ready-for-merge

#3373 [WFCORE-3930] Possible file permission issues in .properties files
  core-galleon-pack/src/main/resources/packages/misc.common/pm/wildfly/tasks.xml
Labels: ready-for-merge

#3345 [WFCORE-3908] When adding property to remoting check first if it is valid
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorChildResource.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorUtils.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/logging/RemotingLogger.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-cli.xml
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-transformers.xml
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-with-expressions-and-good-legacy-protocol.xml
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-with-expressions.xml
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting.xml
Labels: ready-for-merge

#3348 Fix for WFCORE-3568 and WFCORE-3743, CLI scrolling and searching
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/MoreTestCase.java
Labels: Feature, ready-for-merge

#3374 [WFCORE-3938]: Checking target paths when unzipping deployements.
  deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
Labels: ready-for-merge
