Repository wildfly/wildfly-core, pull requests merged in 2018-08, with the labels that each got.

#3401 [WFCORE-3974] Adjust AuditLogBootingSyslogTest test case to test number of operations within the audit log events instead of counting how many events they are chopped into.
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
Labels: ready-for-merge

#3414 [WFCORE-3990] Upgrade to Byteman version 4.0.4 for better JDK9+ support.
  pom.xml
Labels: ready-for-merge

#3412 WFLY-5550 Add deployment phase priorities for distribute-web subsystem DUPs
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: ready-for-merge

#3407 [WFCORE-3519] Add JASPI module to core-feature-pack.
  core-feature-pack/pom.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/javax/security/auth/message/api/main/module.xml
  core-galleon-pack/pom.xml
  pom.xml
Labels: ready-for-merge

#3406 [WFCORE-3984] --add-modules java.se for modular.jdk.args
  pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/standalone/pom.xml
Labels: ready-for-merge

#3404 [WFCORE-3981] Upgrade jboss-logging from 3.3.1.Final to 3.3.2.Final.
  pom.xml
Labels: ready-for-merge

#3413 [WFCORE-3797] Add the -Djava.util.logging.manager system property to …
  logging/pom.xml
Labels: ready-for-merge

#3415 [WFCORE-3992] Avoid allowing duplicate paths to be used for the modul…
  patching/src/main/java/org/jboss/as/patching/installation/InstallationManagerService.java
Labels: ready-for-merge

#3416 [WFCORE-3994] Add WildFly 13 as a known release for use in host-exclu…
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
Labels: ready-for-merge

#3371 Fix for WFCORE-3942, CLI browse deployment completion with .. crashes
  cli/src/main/java/org/jboss/as/cli/impl/DeploymentItemCompleter.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ExplodedDeploymentTestCase.java
Labels: ready-for-merge

#3419 [WFCORE-3970] Add a management operation to allow an Elytron trust-manager to be re-initialized
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
Labels: Feature, ready-for-merge

#3423 WFCORE-4006 Undertow 2.0.12.Final
  pom.xml
Labels: ready-for-merge

#3428 [WFCORE-4005] Refactor parsing for new elements added to version 4 of the Elytron schema
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser3_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser4_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
Labels: ready-for-merge

#3429 [WFCORE-4009] Upgrade VFS to 3.2.13
  pom.xml
Labels: ready-for-merge

#3431 [WFCORE-4010] Adjust provisioning configs to reduce config diff noise
  core-galleon-pack/src/main/resources/feature_groups/access-control.xml
  core-galleon-pack/src/main/resources/feature_groups/domain-profile.xml
  core-galleon-pack/src/main/resources/feature_groups/elytron-app.xml
  core-galleon-pack/src/main/resources/feature_groups/elytron-management.xml
  core-galleon-pack/src/main/resources/feature_groups/host-profile.xml
Labels: ready-for-merge

#3432 [WFCORE-4011] Upgrade WildFly Elytron to 1.5.2.Final
  pom.xml
Labels: ready-for-merge

#3427 [WFCORE-3999] Allow registering a custom HTTP handler for management interface
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  server/src/main/java/org/jboss/as/server/mgmt/domain/ExtensibleHttpManagement.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/CustomContextExtension.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/testbase/CustomManagementContextTestBase.java
Labels: 6.x, Feature, ready-for-merge

#3435 [WFCORE-37] Don't throw an exception if a handler is added via the ad…
  logging/src/main/java/org/jboss/as/logging/CommonAttributes.java
  logging/src/main/java/org/jboss/as/logging/handlers/AsyncHandlerResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/loggers/LoggerOperations.java
  logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
Labels: 6.x, ready-for-merge

#3430 [WFCORE-3991] read-config-as-features management operation
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  controller/src/main/java/org/jboss/as/controller/operations/PathAddressFilter.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadConfigAsFeaturesOperationHandler.java
  controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
  controller/src/test/java/org/jboss/as/controller/test/ReadConfigAsFeaturesTestCase.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/GenericModelDescribeOperationHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainOperationsHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
Labels: 6.x, Feature, ready-for-merge

#3438 [WFCORE-3991] read-config-as-features management operation
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  controller/src/main/java/org/jboss/as/controller/operations/PathAddressFilter.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadConfigAsFeaturesOperationHandler.java
  controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
  controller/src/test/java/org/jboss/as/controller/test/ReadConfigAsFeaturesTestCase.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/GenericModelDescribeOperationHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ReadMasterDomainOperationsHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
Labels: Feature, ready-for-merge

#3446 [WFCORE-3991] Fixed test coverage for read-config-as-features
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ReadConfigAsFeaturesDomainTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ReadConfigAsFeaturesTestBase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
Labels: 6.x, ready-for-merge

#3449 [WFCORE-4025]: Intermittent errors on RemoteGitRepositoryTestCase.historyAndManagementOperationsTest
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/GitRepositoryTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteGitRepositoryTestCase.java
Labels: 6.x, ready-for-merge

#3451 [WFCORE-4028] Upgrade to WildFly Elytron 1.5.4.Final
  pom.xml
Labels: 6.x, ready-for-merge

#3452 [i18n] Use the correct Zanata repository version.
  zanata.xml
Labels: 6.x, ready-for-merge

#3454 [WFCORE-4031] Test coverage for read-config-as-features(nested=false)
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/ReadConfigAsFeaturesDomainTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/api/ReadConfigAsFeaturesTestBase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ReadConfigAsFeaturesStandaloneTestCase.java
Labels: hold

#3458 WFCORE-4037 Undertow 2.0.13.Final
  pom.xml
Labels: 6.x, ready-for-merge

#3466 [WFCORE-4051] Also unwrap the TrustManager if in FIPS mode.
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
Labels: ready-for-merge

#3472 [WFCORE-4059] Add missing attribute 'always-send-client-cert' to configuration schemas.
  server/src/main/resources/schema/wildfly-config_5_0.xsd
  server/src/main/resources/schema/wildfly-config_6_0.xsd
  server/src/main/resources/schema/wildfly-config_7_0.xsd
  server/src/main/resources/schema/wildfly-config_8_0.xsd
Labels: ready-for-merge

#3477 [WFCORE-4023] Upgrade to xerces 2.12.0.SP02
  pom.xml
Labels: ready-for-merge

#3487 [WFCORE-4073] Upgrade JBoss Marshalling to 2.0.6.Final
  pom.xml
Labels: 6.x
