Repository wildfly/wildfly-core, pull requests merged in 2018-03, with the labels that each got.

#3141 WFCORE-3648 Options --disabled/--enabled/--replace are missing in CLI code completion
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/security/OptionActivators.java
Labels: 5.x, ready-for-merge

#3140 [WFCORE-3646] Improve reload handling in WildFly Core test runner
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Labels: 5.x, ready-for-merge

#3120 [WFCORE-3623] Remove ModuleIndexService
  server/src/main/java/org/jboss/as/server/ApplicationServerService.java
  server/src/main/java/org/jboss/as/server/Services.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleIndexService.java
Labels: 5.x, ready-for-merge

#3114 WFCORE-3614 Only report on directly missing deps
  controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
  controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Labels: 5.x, ready-for-merge

#3153 WFCORE-3664 WildFly OpenSSL 1.0.4.Final
  pom.xml
Labels: ready-for-merge

#3150 WFCORE-3659 1.4.23.Final
  pom.xml
Labels: ready-for-merge

#3151 [WFCORE-3660] / [WFCORE-3661] WildFly Elytron Component Upgrades
  pom.xml
Labels: ready-for-merge

#3152 WFCORE-3662 If an exception occurs resuming an activity the exception…
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
Labels: ready-for-merge

#3157 WFCORE-3668 WFCORE-3669 Jandex 2.0.5.Final Jboss Invocation 1.5.1.Final
  pom.xml
Labels: 5.x, ready-for-merge

#3145 Fix for WFCORE-3647, CLI, Cygwin issue when paging output
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
Labels: 5.x, ready-for-merge

#3156 [WFCORE-3638] Coverity, dead code in AbstractEnableSSLCommand and Key…
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/SSLSecurityBuilder.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/AbstractEnableSSLCommand.java
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
Labels: 5.x, ready-for-merge

#3161 Fix for WFCORE-3671, fixed cd command path validation
  cli/src/main/java/org/jboss/as/cli/handlers/PrefixHandler.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CdTestCase.java
Labels: 5.x, ready-for-merge

#3162 Fix for WFCORE-3673, CLI, add examples in for/done command help
  cli/src/main/resources/help/done.txt
  cli/src/main/resources/help/for.txt
Labels: 5.x, ready-for-merge

#3163 Fix for WFCORE-3674, CLI fix .bat file to not strip out ! from arguments
  core-feature-pack/src/main/resources/content/bin/jboss-cli.bat
Labels: 5.x, ready-for-merge

#3149 [WFCORE-3658] Introducing wildfly-url-http component
  core-feature-pack/pom.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/commons/codec/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/httpcomponents/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/james/mime4j/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/standalone/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/url/http/wildfly-url-http/main/module.xml
  pom.xml
Labels: 5.x, ready-for-merge

#3047 WFCORE-3525 Expose Xnio buffer pools as an Undertow ByteBufferPool ca…
  controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
  io/subsystem/pom.xml
  io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java
  io/subsystem/src/main/java/org/wildfly/extension/io/IOServices.java
  io/subsystem/src/main/resources/org/wildfly/extension/io/LocalDescriptions.properties
Labels: 5.x, ready-for-merge

#3129 [WFCORE-3587] Remove unused dependencies
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/core-security/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-repository/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-management/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/jmx/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/logging/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/remoting/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/threads/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/version/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/invocation/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/logmanager/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/remoting-jmx/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/embedded/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/core-management-client/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/discovery/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/request-controller/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/security/manager/main/module.xml
Labels: ready-for-merge

#2680 [WFCORE-3133] - [Migration operation] [Web to Undertow] truststore - ke…
  domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_5.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/KeystoreAttributes.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
Labels: 5.x, ready-for-merge

#3164 WFCORE-3675 make it build and test on JDK 11
  cli/pom.xml
  pom.xml
Labels: ready-for-merge

#3165 WFCORE-3676 Register wildcard children last so that any override models are not treated as duplicate registrations
  controller/src/main/java/org/jboss/as/controller/registry/LegacyResourceDefinition.java
Labels: ready-for-merge

#3174 [WFCORE-3690] Upgrade JBoss Marshalling to 2.0.5.Final
  pom.xml
Labels: 5.x

#3175 [WFCORE-3691] Upgrade JBoss Threads to 2.3.2.Final
  pom.xml
Labels: 5.x

#3177 [WFCORE-3694] Upgrade WildFly Common to 1.3.1.Final
  pom.xml
Labels: 5.x

#3172 WFCORE-3681 Undertow 2.0.2.Final
  pom.xml
Labels: 5.x, ready-for-merge

#3170 [WFCORE-3587] Remove maven deps corresponding to the unneeded module deps
  core-management/core-management-client/pom.xml
  deployment-repository/pom.xml
  deployment-scanner/pom.xml
  discovery/pom.xml
  domain-management/pom.xml
  embedded/pom.xml
  host-controller/pom.xml
  remoting/subsystem/pom.xml
  request-controller/pom.xml
  server/pom.xml
  version/pom.xml
Labels: 5.x, ready-for-merge

#3070 [WFCORE-3550] Minimize creation of attribute descriptions in support …
  jmx/src/main/java/org/jboss/as/jmx/logging/JmxLogger.java
  jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
  jmx/src/main/java/org/jboss/as/jmx/model/TypeConverters.java
Labels: 5.x, ready-for-merge

#3010 [WFCORE-3458] External CS, PKCS11 can't be configured with externalPath
  elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreService.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
Labels: 5.x, ready-for-merge, security

#3179 [WFCORE-3409] If the user has overridden the module.path system prope…
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
Labels: ready-for-merge

#3182 [WFCORE-3703] Move all SLF4J dependencies to Core
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/ch/qos/cal10n/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/slf4j/ext/main/module.xml
  pom.xml
Labels: ready-for-merge

#3184 Fix for WFCORE-3704, upgrade to aesh 1.1
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandInvocationBuilder.java
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AppendTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GrepTestCase.java
Labels: ready-for-merge

#3187 [WFCORE-3707] Add the restart level for add operations in the logging…
  logging/src/main/java/org/jboss/as/logging/LoggingResourceDefinition.java
  logging/src/test/java/org/jboss/as/logging/LoggingOperationsSubsystemTestCase.java
Labels: ready-for-merge
