Repository wildfly/wildfly-core, pull requests merged in 2018-07, with the labels that each got.

#3379 [WFCORE-3945] Remove the application-http-authentication http-authentication-factory from the default configuration.
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractDisableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractEnableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractMgmtDisableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractMgmtEnableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/HTTPServerDisableAuthCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/HTTPServerEnableAuthCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementDisableHTTPCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementDisableSASLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementEnableHTTPCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementEnableSASLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ApplicationSecurityDomain.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthSecurityBuilder.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/HTTPServer.java
  cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/auth/command_resources.properties
  core-galleon-pack/src/main/resources/feature_groups/elytron-app.xml
  elytron/src/main/resources/subsystem-templates/elytron.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
Labels: Feature

#3394 [WFCORE-3967] Upgrade to Galleon and WildFly Galleon Plugins 2.0.0.Al…
  build/pom.xml
  core-galleon-pack/pom.xml
  core-galleon-pack/wildfly-feature-pack-build.xml
  dist/pom.xml
  pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/patching/pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
  testsuite/vault-test-feature-pack/pom.xml
  testsuite/vault-test-feature-pack/wildfly-feature-pack-build.xml
Labels: ready-for-merge

#3390 [WFCORE-3961] / [WFCORE-3591] Elytron Web Component Upgrade and Additional Module
  pom.xml
Labels: ready-for-merge

#3395 Fix for WFCORE-3968, Upgrade CLI to use aesh 1.7 and aesh-readline 1.10
  pom.xml
Labels: ready-for-merge

#3381 [WFCORE-3613] Remove the org.wildfly.javax.json module.
  core-feature-pack/src/main/resources/modules/system/layers/base/javax/json/api/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/logmanager/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/javax/json/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
Labels: ready-for-merge

#3359 [WFCORE-3666] Provide Elytron alternative to RoleMappingLoginModule
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_4_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-4.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/role-mappers-test.xml
Labels: Feature, ready-for-merge

#3398 Fix for WFCORE-3973, Upgrade CLI to use aesh-extensions 1.6
  pom.xml
Labels: ready-for-merge

#3396 update jboss-parent to 28
  pom.xml
Labels: ready-for-merge

#3393 [WFCORE-3965] Cover possible error when host controllers can not connect to domain after creating a rollout plan and restarting the master host controller
  management-client-content/src/main/java/org/jboss/as/management/client/content/ManagedDMRContentTypeResource.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ReloadWithRolloutPlanTestCase.java
Labels: ready-for-merge

#3364 Fix for WFCORE-3933, compact ouput for echo-dmr
  cli/src/main/java/org/jboss/as/cli/CommandContext.java
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/handlers/EchoDMRHandler.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/resources/help/echo-dmr.txt
  cli/src/test/java/org/jboss/as/cli/EchoDMRTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Labels: Feature, ready-for-merge
