Repository wildfly/wildfly-core, pull requests merged in 2018-05, with the labels that each got.

#3242 [WFCORE-3776] Deprecate attribute 'show-model' in jmx subsystem
  jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRootResource.java
  jmx/src/main/resources/org/jboss/as/jmx/LocalDescriptions.properties
Labels: ready-for-merge

#3212 Fix for WFCORE-3672, Extend CLI security command with support for Authentication
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractDisableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractEnableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractReorderSASLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/HTTPServerDisableAuthCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/HTTPServerEnableAuthCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementDisableHTTPCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementDisableSASLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementEnableHTTPCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementEnableSASLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/ManagementReorderSASLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/OptionActivators.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AbstractKeyStoreConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthFactory.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthFactorySpec.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthMechanism.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthSecurityBuilder.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/DefaultResourceNames.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/EmptyConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ExistingKeyStoreConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ExistingPropertiesRealmConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/FileSystemRealmConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/HTTPServer.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/KeyStoreConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/LocalUserConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ManagementInterfaces.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/MechanismConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/PropertiesRealmConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/Realm.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/SecurityDomain.java
  cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/auth/command_resources.properties
  cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/ssl/command_resources.properties
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: Feature, ready-for-merge

#3240 [WFCORE-3784] Add missing subsystems to WildFly Core domain.xml profile
  core-feature-pack/src/main/resources/configuration/domain/subsystems.xml
Labels: ready-for-merge

#3246 Fix for WFCORE-3789, CLI, powershell option handling
  core-feature-pack/src/main/resources/content/bin/jboss-cli.ps1
Labels: ready-for-merge

#3234 [WFCORE-1917] Deprecate 'reload', 'suspend' and 'resume' ops on the server-config resource
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerReloadHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerResumeHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStartHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerSuspendHandler.java
  host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
Labels: ready-for-merge

#3224 [WFCORE-3752] Upgrading to MSC 1.4.2.Final - brings support for multi-value services
  component-matrix/pom.xml
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: Feature, ready-for-merge

#3245 WFCORE-3794 Undertow 2.0.5.Final
  component-matrix/pom.xml
Labels: ready-for-merge

#3238 [WFCORE-3781] Upgrade WildFly Common to 1.3.2.Final
  component-matrix/pom.xml
Labels: ready-for-merge

#3230 [WFCORE-3608] Add core pool size attribute to IO subsystem
  component-matrix/pom.xml
Labels: Feature, fixme

#3249 [WFCORE-3798] Upgrade WildFly Elytron to 1.3.1.Final
  component-matrix/pom.xml
Labels: ready-for-merge

#3241 [WFCORE-3785 + WFCORE-3800] Allow capability builders to declare additional galleon…
  controller/src/main/java/org/jboss/as/controller/capability/Capability.java
  controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
  controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
Labels: ready-for-merge

#3254 [WFCORE-3802] Add main-class to the org.jboss.jandex module.xml to ma…
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/jandex/main/module.xml
Labels: ready-for-merge

#3250 [WFCORE-3793]: Allow for the provisioning of SecurityRealm without a 'running' elytron
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
Labels: ready-for-merge

#3232 [WFCORE-3577] Add support for coloured output to CLI
  cli/src/main/java/org/jboss/as/cli/CliConfig.java
  cli/src/main/java/org/jboss/as/cli/ColorConfig.java
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextConfiguration.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/Namespace.java
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICompletionHandler.java
  cli/src/main/resources/help/help.txt
  cli/src/main/resources/schema/wildfly-cli_3_3.xsd
  cli/src/test/java/org/jboss/as/cli/completion/mock/MockCliConfig.java
  core-feature-pack/src/main/resources/content/bin/jboss-cli.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CLITestUtil.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliControllerConfigTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliEmbedServerTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityAuthCommandsTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: Feature

#3202 [WFCORE-3205 & WFCORE-3698] Fix embedded server property setting and update the logging works
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
  embedded/pom.xml
  embedded/src/main/java/org/wildfly/core/embedded/ChainedContext.java
  embedded/src/main/java/org/wildfly/core/embedded/Configuration.java
  embedded/src/main/java/org/wildfly/core/embedded/Context.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcessImpl.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/HostControllerSystemPropertyContext.java
  embedded/src/main/java/org/wildfly/core/embedded/LoggerContext.java
  embedded/src/main/java/org/wildfly/core/embedded/SecurityActions.java
  embedded/src/main/java/org/wildfly/core/embedded/StandaloneSystemPropertyContext.java
  embedded/src/main/java/org/wildfly/core/embedded/SystemPropertyContext.java
  embedded/src/main/java/org/wildfly/core/embedded/logging/EmbeddedLogger.java
  logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelector.java
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
  testsuite/embedded/pom.xml
  testsuite/embedded/server-provisioning.xml
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/AbstractTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/EmbeddedTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/Environment.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/LoggingTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/SystemPropertyResetTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/JBossLogManagerHostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/JulHostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/Log4jHostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/JBossLogManagerStandaloneTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/JulStandaloneTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/Log4jStandaloneTestCase.java
  testsuite/embedded/src/test/resources/log4j.properties
  testsuite/embedded/src/test/resources/logging.properties
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
  testsuite/pom.xml
Labels: Feature

#3264 [WFCORE-3596] Introduce named permission sets in the Elytron subsystem
  core-galleon-pack/src/main/resources/feature_groups/elytron-common.xml
  core-galleon-pack/src/main/resources/feature_groups/host-elytron-common.xml
  core-galleon-pack/src/main/resources/feature_groups/host-profile.xml
  elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser1_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser1_1.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser3_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/PermissionSetDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_3_0.xsd
  elytron/src/main/resources/subsystem-templates/elytron.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-3.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/sasl-test.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
Labels: Feature, ready-for-merge

#3283 [WFCORE-3827] Test for thread pool attribute propagation for IO subsystem
  io/tests/src/test/java/org/wildfly/extension/io/IOSubsystemTestCase.java
Labels: ready-for-merge

#3284 [WFCORE-3205] Added log4j2 and logback tests to embedded TS
  testsuite/embedded/pom.xml
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/LoggingTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/Log4j2HostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/LogbackHostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/Log4j2StandaloneTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/LogbackStandaloneTestCase.java
  testsuite/embedded/src/test/resources/log4j2-test.properties
  testsuite/embedded/src/test/resources/logback-test.xml
  testsuite/shared/pom.xml
Labels: ready-for-merge

#3286 [WFCORE-3833] Upgrade WildFly Common to 1.4.0.Final
  pom.xml
Labels: ready-for-merge

#3288 [WFCORE-3835] Make CLI JAR be Multi-Release
  cli/pom.xml
Labels: ready-for-merge

#3289 [WFCORE-3709] Upgrade JBoss Remoting to 5.0.7.Final
  pom.xml
Labels: ready-for-merge

#3290 [WFCORE-3717] Upgrade XNIO to 3.6.3.Final
  pom.xml
Labels: ready-for-merge

#3291 [WFCORE-3837] / [WFCORE-3838] WildFly Elytron Component Upgrades
  pom.xml
Labels: ready-for-merge

#3236 [WFCORE-3762] Actually create the response warning; the previous fix …
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/TestModelControllerService.java
Labels: ready-for-merge

#3302 [WFCORE-3850] core-galleon-pack: remove org.jboss.as.domain-http-erro…
  core-galleon-pack/wildfly-feature-pack-build.xml
Labels: ready-for-merge

#3308 WFCORE-3857 Upgrade to WildFly Galleon plugins 1.0.0.CR6
  pom.xml
Labels: ready-for-merge

#3312 [WFCORE-3861] Fix POM name to be consistent with other modules
  testsuite/embedded/pom.xml
Labels: ready-for-merge

#3317 [WFCORE-3862] Ensure the modulePath set by the user is used if set.
  embedded/src/main/java/org/wildfly/core/embedded/Configuration.java
Labels: ready-for-merge

#3309 BLOCKER - [WFCORE-3859] Add transformer to transform from version 2.0.0 to 1.2.0 of the Elytron subsystem model.
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
Labels: ready-for-merge

#3304 [WFCORE-3853] CLI prompt contains extra space when colors are enabled
  cli/src/main/java/org/jboss/as/cli/Util.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
Labels: ready-for-merge

#3323 [WFCORE-3886] Upgrade to WildFly Galleon plugins 1.0.0.CR12
  pom.xml
Labels: ready-for-merge

#3324 WFCORE-3888 Undertow 2.0.8.Final
  pom.xml
Labels: ready-for-merge

#3328 [WFCORE-3893] Upgrade to Galleon 1.0.0.Final and Galleon Plugins 1.0.…
  pom.xml
Labels: ready-for-merge

#3325 [WFCORE-3883] / [WFCORE-3890] WildFly Elytron Component Upgrades
  pom.xml
Labels: ready-for-merge

#3322 [WFCORE-3884] / [WFCORE-3889] Ensure correct ClassLoader is used when dynamically loading classes and add dependency on 'jdk.security.auth' for the domain-management module.
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
  domain-management/src/main/java/org/jboss/as/domain/management/security/KeytabService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapSubjectSupplementalService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java
Labels: ready-for-merge

#3330 WFCORE-3894 Undertow 2.0.9.Final
  pom.xml
Labels: ready-for-merge
