Repository wildfly/wildfly-core, pull requests merged in 2018-10, with the labels that each got.

#3507 [WFCORE-3404] Elytron audit performance - separated sync and flushing
  elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser5_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_5_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/audit-logging.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
Labels: Feature, ready-for-merge

#3537 [WFCORE-4141] Register the ServerEnvironment resource def from the co…
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
Labels: ready-for-merge

#3538 [WFCORE-3996] Update GC logging to work on Java 9+ - part II.
  core-feature-pack/src/main/resources/content/bin/common.ps1
  core-feature-pack/src/main/resources/content/bin/standalone.bat
  core-feature-pack/src/main/resources/content/bin/standalone.sh
Labels: Feature, ready-for-merge

#3434 [WFCORE-3386] Add JASPI Configuration to the Elytron Subsystem
  core-feature-pack/pom.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser5_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/JaspiDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TrivialResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_5_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-5.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/jaspi.xml
  testsuite/vault-test-feature-pack/src/main/resources/modules/system/layers/base/org/picketbox/main/module.xml
Labels: Feature, ready-for-merge

#3533 Fix for WFCORE-4096, CLI replace paging support with aesh one
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
Labels: ready-for-merge

#3541 [WFCORE-4146] Remove redundant calls to .setXmlName().
  elytron/src/main/java/org/wildfly/extension/elytron/JaspiDefinition.java
Labels: ready-for-merge

#3546 [WFCORE-4153] Don't discard the fact that dependent caps are *not* dy…
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
Labels: ready-for-merge

#3549 Fix for WFCORE-4159, remove invalid dep on javafx
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
Labels: ready-for-merge

#3543 [WFCORE-4151] Upgrade jboss-logmanager from 2.1.4.Final to 2.1.5.Final
  pom.xml
Labels: ready-for-merge

#3548 [WFCORE-4158] Ensure the KernelServices are shutdown for logging tests.
  logging/src/test/java/org/jboss/as/logging/FormatterOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/HandlerLegacyOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LogFilterTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggerLegacyOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggerOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingOperationsSubsystemTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingSubsystemRollbackTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
  logging/src/test/java/org/jboss/as/logging/RootSubsystemOperationsTestCase.java
Labels: ready-for-merge

#3545 [WFCORE-4155] Upgrade to Galleon and WildFly Galleon Plugins 2.0.1.Final
  pom.xml
Labels: ready-for-merge

#3547 [WFCORE-4156] Add missing KernelAPIVersion for WildFly 14
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
Labels: ready-for-merge

#3555 [WFCORE-4167] Upgrade to WildFly Galleon Plugins 2.0.2.Final and prop…
  build/pom.xml
  core-feature-pack/pom.xml
  core-galleon-pack/pom.xml
  dist/pom.xml
  pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/patching/pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
Labels: ready-for-merge

#3554 [WFCORE-4164] Add fixed requirements to the read-feature-description output
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
  controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/ServerService.java
Labels: ready-for-merge

#3553 [WFCORE-3039] Capability requirement can be lost if two attributes on same resource reference the same capability
  controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
  controller/src/main/java/org/jboss/as/controller/capability/registry/RegistrationPoint.java
  controller/src/main/java/org/jboss/as/controller/capability/registry/RequirementRegistration.java
  controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
  jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorResource.java
  logging/src/main/java/org/jboss/as/logging/capabilities/LoggingProfileCapabilityRecorder.java
Labels: ready-for-merge

#3552 [WFCORE-3952] Do not bother with host controllers in standalone module
  testsuite/standalone/enable-elytron.cli
  testsuite/standalone/pom.xml
Labels: ready-for-merge

#3544 [WFCORE-4152] HC cannot connect to DC after lost connect if models are out of sync and RBAC is enabled
  controller-client/src/main/java/org/jboss/as/controller/client/impl/ModelControllerProtocol.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClient.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClientImpl.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolOperationHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
  server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerClient.java
  server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnection.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/DeploymentOverlayScenario.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/DeploymentScenario.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/OrderedChildResourceScenario.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/RBACModelOutOfSyncScenario.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/ReconnectTestScenario.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/SlaveReconnectTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/slavereconnect/UnaffectedScenario.java
Labels: ready-for-merge

#3521 [WFCORE-4113] Add a commented line to standalone.conf to show how to use a custom java.security file to override all the Java security properties
  core-feature-pack/src/main/resources/content/bin/standalone.conf
  core-feature-pack/src/main/resources/content/bin/standalone.conf.bat
  core-feature-pack/src/main/resources/content/bin/standalone.conf.ps1
Labels: ready-for-merge

#3556 [WFCORE-4147] Delete the gc.log after the -version check to see if the GC settings are valid.
  core-feature-pack/src/main/resources/content/bin/standalone.bat
  core-feature-pack/src/main/resources/content/bin/standalone.sh
Labels: Blocker, ready-for-merge

#3558 [WFCORE-4168] / [WFCORE-4169] WildFly Elytron Component Upgrades
  pom.xml
Labels: ready-for-merge

#3004 Upgrade to http-core 4.4.5 and http-client 4.5.4
  pom.xml
Labels: 7.x, ready-for-merge

#3563 [WFCORE-4174] Update jackson-databind to 2.9.5 and mockserver-netty to 5.4.1
  elytron/src/test/java/org/wildfly/extension/elytron/AcmeMockServerBuilder.java
  pom.xml
Labels: ready-for-merge

#3564 WFCORE-4175 Undertow 2.0.14.Final
  pom.xml
Labels: ready-for-merge

#3560 [WFCORE-4120] Do not allow adding a module as extension when the module does not contain an extension
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
Labels: ready-for-merge

#3559 [WFCORE-4166] HttpListenerRegistryService is not exposed via a capability
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/Capabilities.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpListenerRegistryService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemRootResource.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestUtil.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Labels: ready-for-merge

#3557 [WFCORE-4116] Do not set the accessible value on Object.class types
  server/src/main/java/org/jboss/as/server/deployment/reflect/ClassReflectionIndex.java
Labels: ready-for-merge

#3565 [WFCORE-4165] Expose SuspendController via a capability
  core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemAdd.java
  request-controller/src/test/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemTestCase.java
  server/src/main/java/org/jboss/as/server/BootstrapImpl.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/Services.java
  server/src/main/java/org/jboss/as/server/operations/ServerDomainProcessShutdownHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerResumeHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerSuspendHandler.java
  server/src/main/java/org/jboss/as/server/operations/SuspendStateReadHandler.java
  server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
Labels: ready-for-merge

#3566 [WFCORE-4173] Register socket-binding bound attributes as read-only
  server/src/main/java/org/jboss/as/server/services/net/BindingRuntimeHandlers.java
  server/src/main/java/org/jboss/as/server/services/net/SocketBindingResourceDefinition.java
Labels: ready-for-merge

#3567 [WFCORE-4177] Default subsystem test reverse controller tests to Addi…
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Labels: ready-for-merge

#3562 [WFCORE-3873] / [WFCORE-3966] Support for SNI and JwtValidator jku and kid header parameters
  core-feature-pack/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser5_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_5_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-5.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  testsuite/shared/src/main/java/org/wildfly/test/undertow/UndertowSSLService.java
  testsuite/shared/src/main/java/org/wildfly/test/undertow/UndertowSSLServiceActivator.java
  testsuite/shared/src/main/java/org/wildfly/test/undertow/UndertowServiceActivator.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
Labels: Feature, ready-for-merge

#3571 [WFCORE-4182] Minor typos in shutdown and reload help descriptions
  cli/src/main/resources/help/reload.txt
  cli/src/main/resources/help/shutdown.txt
Labels: ready-for-merge

#3574 [WFCORE-4184] Don't lose track of what object's fields are all undefined
  model-test/src/main/java/org/jboss/as/model/test/ModelTestUtils.java
Labels: ready-for-merge

#3575 [WFCORE-4189] Remove failIfNoTests=true from surefire plugin for rbac…
  testsuite/rbac/pom.xml
Labels: ready-for-merge

#3577 [WFCORE-4191] Fix IO metrics registration
  io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
Labels: ready-for-merge
