Repository wildfly/wildfly-core, pull requests merged in 2019-04, with the labels that each got.

#3720 [WFCORE-4393] Upgrade XNIO to 3.7.1.Final
  pom.xml
Labels: ready-for-merge

#3718 [WFCORE-4357] Introducing DeploymentPhaseContext.requires() method
  server/src/main/java/org/jboss/as/server/deployment/DelegatingSupplier.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java
Labels: ready-for-merge

#3717 [WFCORE-4390] Introducing new o.j.a.s.d.Attachments.COMPONENT_JNDI_DEPS key
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
Labels: ready-for-merge

#3715 Fix for WFCORE-4389, CLI, deploy fails in batch when operation is validated
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/deployment/AbstractDeployContentCommand.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/DeployTestCase.java
Labels: ready-for-merge

#3699 WFCORE-4363 No need to handle error page request if console is disabled
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
Labels: ready-for-merge

#3716 WFCORE-4388 Subsystem test framework alters order of child resources…
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformationUtils.java
Labels: ready-for-merge

#3714 [WFCORE-4387] Fix typo in remoting descriptions
  remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties
Labels: ready-for-merge

#3698 [WFCORE-4359] Ensure the CLI embedded stdio and log contexts are used for CLI loggers.
  cli/src/main/java/org/jboss/as/cli/embedded/ThreadLocalContextSelector.java
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelector.java
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
  pom.xml
Labels: ready-for-merge

#3653 WFCORE-4376 Fix deprecation warnings resulting from the improper deprecation of AbstractCapability.
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
  controller/src/main/java/org/jboss/as/controller/capability/registry/CapabilityRegistration.java
  controller/src/main/java/org/jboss/as/controller/capability/registry/RuntimeCapabilityRegistration.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
Labels: ready-for-merge

#3721 [WFCORE-4396] Use HTTPS for repository and pluginRepository URLs
  pom.xml
Labels: ready-for-merge

#3674 [WFCORE-3969] ALIAS_FILTER in Elytron trustmanager ignored when crl used
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
Labels: ready-for-merge

#3702 [WFCORE-4369] Fixing JDK 13 test issue
  core-feature-pack/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
  elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/JdkUtils.java
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
Labels: ready-for-merge

#3733 [WFCORE-4405] Binary jar files in model-test
  model-test/src/test/java/org/jboss/as/model/test/ChildFirstClassLoadingTest.java
  model-test/src/test/java/org/jboss/as/model/test/child/WelcomeChild.java
  model-test/src/test/java/org/jboss/as/model/test/parent/WelcomeParent.java
  model-test/src/test/resources/org/jboss/as/model/test/child.jar
  model-test/src/test/resources/org/jboss/as/model/test/parent.jar
Labels: deps-ok

#3722 WFCORE-4399 ResourceEntry implementations to not implement equals/hashCode()
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionResource.java
  controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
  controller/src/main/java/org/jboss/as/controller/registry/PlaceholderResource.java
  controller/src/main/java/org/jboss/as/controller/transform/description/TransformationRule.java
Labels: ready-for-merge

#3723 [WFCORE-4401] Make the 'org.wildfly.security.password.util' package public.
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron/main/module.xml
Labels: ready-for-merge

#3726 WFCORE-3296 Ephemeral port number (port="0") should not be affected b…
  network/src/main/java/org/jboss/as/network/SocketBinding.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/OtherServicesSubsystemTestCase.java
Labels: ready-for-merge

#3727 [WFCORE-4403] Upgrade Undertow to 2.0.20.Final
  pom.xml
Labels: ready-for-merge

#3670 [WFCORE-4325] Unable to run testsuite/domain tests with -Delytron
  testsuite/domain/enable-elytron.cli
  testsuite/domain/pom.xml
Labels: ready-for-merge

#2935 [WFCORE-3185] Run parallel boot tasks in coarser grained chunks
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/extension/ParallelExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  server/src/main/java/org/jboss/as/server/ServerService.java
Labels: deps-ok, ready-for-merge

#3581 Update service.bat
  core-feature-pack/src/main/resources/content/docs/contrib/scripts/service/service.bat
Labels: ready-for-merge

#3596 [WFCORE-4129] WFLYSRV0266: Server home is set to... info msg in domain for RPM installation
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: ready-for-merge

#3725 Fix for WFCORE-4402, Upgrade CLI to use aesh 2.3
  cli/src/main/java/org/jboss/as/cli/impl/aesh/CLICommandContainer.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/operation/LegacyCommandContainer.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/operation/OperationCommandContainer.java
  pom.xml
Labels: deps-ok, ready-for-merge

#3732 [WFCORE-4409] Avoid hangs from https://bugs.openjdk.java.net/browse/JDK-8219658
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/auditlog/AuditLogToTLSSyslogTestCase.java
Labels: deps-ok, ready-for-merge

#3734 [WFCORE-4410] Upgrade Elytron Web to 1.5.0.CR1
  pom.xml
Labels: deps-ok, ready-for-merge

#3736 [WFCORE-4413] Fixing javax.api and javax.sql.api modules BC issues
  core-feature-pack/src/main/resources/modules/system/layers/base/javax/api/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
Labels: deps-ok, ready-for-merge

#3741 [WFCORE-4418] Deprecate unused ParseUtil methods.
  controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
Labels: ready-for-merge

#3742 [WFCORE-4420] Fix check for XMLConstants.NULL_NS_URI
  controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
Labels: ready-for-merge

#3739 [WFCORE-4416] Some capabilities requirements are not recorded in features generated by Galleon
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
Labels: deps-ok

#3738 [WFCORE-4415] Upgrading JBoss Modules from 1.9.0.Final to 1.9.1.Final
  core-feature-pack/src/main/resources/content/bin/common.bat
  core-feature-pack/src/main/resources/content/bin/common.ps1
  core-feature-pack/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
Labels: deps-ok

#3743 Logging and wildfly-common component upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#3745 [WFCORE-4430] Upgrade jboss-stdio from 1.0.2.GA to 1.1.0.Final.
  pom.xml
Labels: deps-ok, ready-for-merge

#3744 [WFCORE-4429] Default to https when accessing repositories.
  model-test/src/main/java/org/jboss/as/model/test/ChildFirstClassLoaderBuilder.java
  model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
  model-test/src/test/java/org/jboss/as/model/test/MavenSettingsTest.java
  model-test/src/test/resources/org/jboss/as/model/test/settings-empty-local-repo.xml
Labels: deps-ok, ready-for-merge

#3740 [WFCORE-4417] Upgrade WildFly Elytron to 1.9.0.CR3
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  core-galleon-pack/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
  pom.xml
Labels: deps-changed, ready-for-merge

#3735 [WFCORE-4412] Eliminating CapabilityServiceTarget.addCapability() deprecated method usages
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  elytron/src/main/java/org/wildfly/extension/elytron/TrivialAddHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java
  io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/BindingGroupAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/SpecifiedInterfaceAddHandler.java
Labels: deps-ok, ready-for-merge

#3713 WFCORE-3891: ensure unique names for default formatters
  logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/formatters/StructuredFormatterResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
  logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
Labels: deps-ok, ready-for-merge

#3426 [WFCORE-3995] forbid invalid Sensitivity Constraint attribute read-wr…
  controller/src/main/java/org/jboss/as/controller/access/constraint/AbstractSensitivity.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/access/RuntimeSensitivityReconfigurationTestCase.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/access/StandaloneAccessControlTestCase.java
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/access/standalone.xml
  domain-management/src/main/java/org/jboss/as/domain/management/access/ApplicationClassificationConfigResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/SensitivityResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ConfigurationChangesHistoryTestCase.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/LegacyConfigurationChangesHistoryTestCase.java
Labels: deps-ok, ready-for-merge

#3753 Revert "[WFCORE-3185] Run parallel boot tasks in coarser grained chunks"
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/extension/ParallelExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  server/src/main/java/org/jboss/as/server/ServerService.java
Labels: deps-ok, ready-for-merge

#3752 [WFCORE-4436] Ensure the TCCL is not null before doing the equals check.
  cli/src/main/java/org/jboss/as/cli/embedded/ThreadLocalContextSelector.java
Labels: deps-ok, ready-for-merge

#3747 [WFCORE-4432] Upgrading JBoss Marshalling to 2.0.7.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3757 [WFCORE-4443] / [WFCORE-4444] WildFly Elytron Component Upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#3758 [WFCORE-4421] Upgrade remoting to 5.0.9.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3737 WFCORE-3298: do not try to modify protected nodes
  controller/src/main/java/org/jboss/as/controller/operations/validation/EnumValidator.java
Labels: deps-ok, ready-for-merge

#3754 [WFCORE-4438] Disable console error context handler for ConsoleMode.NO_CONSOLE
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
Labels: deps-ok, ready-for-merge

#3759 [WFCORE-4448] Deprecate unused MultistepUtil methods so we can clean …
  controller/src/main/java/org/jboss/as/controller/operations/MultistepUtil.java
Labels: deps-ok, ready-for-merge

#3755 [WFCORE-4442] Migrating UndertowHttpManagementService & HttpShutdownService to new MSC API
  domain-management/src/main/java/org/jboss/as/domain/management/SecurityRealm.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/mgmt/HttpShutdownService.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Labels: deps-ok, ready-for-merge

#3751 Fix for WFCORE-4406 and Upgrade to Galleon 4.0.0.alpha
  core-galleon-pack/pom.xml
  core-galleon-pack/src/main/resources/packages/bin/package.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#3749 [WFCORE-4433] Update wildfly-discovery-client to 1.2.0.Final
  pom.xml
Labels: deps-ok, ready-for-merge
