Repository wildfly/wildfly-core, pull requests merged in 2019-02, with the labels that each got.

#3657 [WFCORE-4304] Upgrade Galleon to 3.0.1.CR2 and WFGP to 3.0.1.CR3
  build/pom.xml
  dist/pom.xml
  pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/layers/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/patching/pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
Labels: ready-for-merge

#3658 [WFCORE-4310] Upgrade Remoting JMX to 3.0.1.Final
  pom.xml
Labels: ready-for-merge

#3659 [WFCORE-4307] / [WFCORE-4308] / [WFCORE-4058] WildFly Elytron Component Upgrades and related RFE
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/schema/wildfly-elytron_6_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
  pom.xml
Labels: ready-for-merge

#3626 [WFCORE-4058] Automatic detection of file based KeyStore types
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/schema/wildfly-elytron_6_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
Labels: Feature

#3654 CLI, fix for WFCORE-1478 and WFCORE-1698
  cli/src/main/java/org/jboss/as/cli/handlers/BaseOperationCommand.java
  cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
  cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestAddress.java
  cli/src/test/java/org/jboss/as/cli/handlers/ShutdownHandlerTestCase.java
  cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestAddressTestCase.java
Labels: ready-for-merge

#3662 [WFCORE-4315] Upgrade the wildfly-maven-plugin to 1.2.1.Final
  pom.xml
Labels: ready-for-merge

#3661 [WFCORE-4251] Provide ability to list module dependencies for a deployment and subdeployment
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerDeploymentResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerSubDeploymentResourceDefinition.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentModulesListTestCase.java
Labels: Feature, ready-for-merge

#3632 [WFCORE-1427] Provide ability to suspend and resume the set of servers managed by a specific host controller
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
  cli/src/main/resources/help/shutdown.txt
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/domain/root/DomainRootTransformersTestCase.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HostShutdownHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStopHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerSuspendHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
  host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
  host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/operations/ServerDomainProcessShutdownHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerSuspendHandler.java
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerManagementTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveSynchronizationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suspendresume/DomainGracefulShutdownTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suspendresume/HostSuspendResumeTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnShutdownTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestUtils.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/CoreServerTestCase.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Labels: Feature, ready-for-merge

#3664 [WFCORE-4089] Introduce the real 7.2.0 legacy test version
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  pom.xml
Labels: Blocker

#3660 Fix for WFCORE-4311, Testing of layer execution
  testsuite/layers/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
Labels: ready-for-merge

#3665 [WFCORE-4318] Upgrading JBoss ClassFileWriter to 1.2.4.Final
  pom.xml
Labels: ready-for-merge

#3666 [WFCORE-4321] Upgrade XML namespace for Galleon packages from 1.0 to 2.0
  core-galleon-pack/src/main/resources/packages/bin/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.domain.config.history.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.domain.data.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.domain.log.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.domain.servers.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.provisioned.state.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.standalone.config.history.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.standalone.data.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.standalone.log.dir/package.xml
  core-galleon-pack/src/main/resources/packages/cleanup.standalone.tmp.vfs/package.xml
  core-galleon-pack/src/main/resources/packages/docs.licenses.merge/package.xml
  core-galleon-pack/src/main/resources/packages/misc.common/package.xml
  core-galleon-pack/src/main/resources/packages/misc.domain/package.xml
  core-galleon-pack/src/main/resources/packages/misc.standalone/package.xml
  core-galleon-pack/src/main/resources/packages/product.conf/package.xml
Labels: ready-for-merge
