Repository wildfly/wildfly-core, pull requests merged in 2019-10, with the labels that each got.

#3964 [WFCORE-4684] The legacy core feature pack should create the .well-kn…
  core-feature-pack/feature-pack-build.xml
Labels: deps-ok

#3967 Fix Test Suite to Work with Eclipse OpenJ9
  logging/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnHttpTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/suspend/SuspendOnSoftKillTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
  testsuite/shared/src/main/java/org/wildfly/test/jmx/JMXListenerDeploymentSetupTask.java
Labels: deps-ok, ready-for-merge

#3966 [WFCORE-4689] Upgrade jboss remoting to 5.0.16.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3968 [WFCORE-4692] Upgrade WildFly Common to 1.5.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3950 WFCORE-4656 fix ConfigurationPersistenceException due to incorrect em…
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/mgmt_interfaces/HostMgmtInterfacesTestCase.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/mgmt_interfaces/StandaloneMgmtInterfacesTestCase.java
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/host_empty_allowed_origins.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/standalone_empty_allowed_origins.xml
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_10.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_10.java
Labels: deps-ok, ready-for-merge

#3948 [WFCORE-4652] Do not execute tests that expect default configuration when Elytron is tested
  testsuite/standalone/pom.xml
Labels: deps-ok, ready-for-merge

#3969 [WFCORE-4699] preferIPv6Addresses and preferIPv4Stack System Properti…
  controller/src/main/java/org/jboss/as/controller/interfaces/OverallInterfaceCriteria.java
  controller/src/test/java/org/jboss/as/controller/interfaces/InterfaceCriteriaTestUtil.java
  controller/src/test/java/org/jboss/as/controller/interfaces/OverallInterfaceCriteriaUnitTestCase.java
  server/src/main/java/org/jboss/as/server/services/net/NetworkInterfaceService.java
Labels: deps-ok, ready-for-merge

#3963 [WFCORE-4681] Add MP OpenAPI constants; bump Jandex to current release
  pom.xml
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: ready-for-merge

#3962 [WFCORE-4678] Use a more recent version of guava
  pom.xml
  testsuite/patching/pom.xml
Labels: deps-ok, ready-for-merge

#3961 [WFCORE-4679] Update the mock-server-netty dep; specify the logback dep
  pom.xml
  testsuite/embedded/pom.xml
Labels: deps-ok, ready-for-merge

#3793 use default charset for cli --properties file
  cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
Labels: deps-ok, ready-for-merge

#3974 [WFCORE-4691] Upgrade XNIO 3.7.5.Final
  pom.xml
Labels: deps-ok, hold

#3977 [WFCORE-4705] / [WFCORE-4706] WildFly Elytron Component Upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#3972 WFCORE-4702 Add deployment phases for MicroProfile Fault Tolerance
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok, ready-for-merge

#3971 WFCORE-4701 SecurityCommandsTestCase and SyslogAuditLogTestCase cleanup
  elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: deps-ok, ready-for-merge

#3980 [WFCORE-4708] Upgrade XNIO 3.7.6.Final
  pom.xml
Labels: deps-ok

#3981 [WFCORE-4683] User with Monitor role can stop the servers in domain mode
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerProcessHandlers.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerStopHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractHostScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractRbacTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/AbstractStandardRolesTestCase.java
Labels: deps-ok, ready-for-merge

#3975 WFCORE-4656 port fix parsers for old namespaces
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_4.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_5.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_6.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_7.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_8.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_9.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_Legacy.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_4.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_5.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_6.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_7.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_8.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_9.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_Legacy.java
Labels: deps-ok, ready-for-merge

#3973 [WFCORE-4680] Redact passwords in the sun.java.command logging
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
  server/src/main/java/org/jboss/as/server/ApplicationServerService.java
Labels: deps-ok, ready-for-merge

#3889 [WFCORE-4594][WFCORE-4595] Expose a capability to allow tracking of ControllledProcessState.State
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ControlledProcessState.java
  controller/src/main/java/org/jboss/as/controller/ControlledProcessStateService.java
  controller/src/main/java/org/jboss/as/controller/ProcessStateNotifier.java
  core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java
  core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerAdd.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
  deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
  deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/ShutdownFileSystemDeploymentServiceUnitTestCase.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/BootstrapImpl.java
  server/src/main/java/org/jboss/as/server/DomainServerCommunicationServices.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/deployment/ContentCleanerService.java
  server/src/main/java/org/jboss/as/server/deployment/ContentRepositoryCleaner.java
  server/src/main/java/org/jboss/as/server/jmx/RunningStateJmx.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerConnectionService.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Labels: 11.x, deps-ok, ready-for-merge

#3983 [WFCORE-4710] Don't arbitrarily turn unescaped mbean names into quote…
  platform-mbean/src/main/java/org/jboss/as/platform/mbean/BufferPoolMXBeanAttributeHandler.java
  platform-mbean/src/main/java/org/jboss/as/platform/mbean/PlatformMBeanUtil.java
  platform-mbean/src/main/java/org/jboss/as/platform/mbean/logging/PlatformMBeanLogger.java
Labels: deps-ok, ready-for-merge

#3984 [WFCORE-4338] Race condition on PID file allows for termination of ar…
  core-feature-pack/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
Labels: deps-ok

#3986 [WFCORE-4714] Upgrade galleon-plugins to 4.0.4.Final
  pom.xml
Labels: deps-ok

#3987 [WFCORE-4709] Upgrade Undertow to 2.0.27.Final
  pom.xml
Labels: deps-ok

#3990 [WFCORE-4717] Add missing EE Security DUP phases.
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#3988 [WFCORE-4716] Upgrade Byteman to 4.0.8
  pom.xml
Labels: deps-ok, ready-for-merge

#3989 [WFCORE-4449] Remove MultistepUtil methods that were deprecated in WF…
  controller/src/main/java/org/jboss/as/controller/operations/MultistepUtil.java
Labels: deps-ok, ready-for-merge

#3991 [WFCORE-4419] Remove deprecated ParseUtil methods
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
Labels: deps-ok, ready-for-merge

#3992 [WFCORE-4720] Clarify that SetupActions.dependencies() cannot return …
  server/src/main/java/org/jboss/as/server/deployment/SetupAction.java
Labels: deps-ok, ready-for-merge

#3993 [WFCORE-4721] Upgrade test and build dependencies
  pom.xml
Labels: deps-ok, ready-for-merge

#3994 [WFCORE-4723] Remove 'testZeroReconnectAttemptsBadHost' test as using a bad address for UDP is unreliable.
  elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java
Labels: deps-ok

#3995 [WFCORE-4726] Add exclusion for 'javax.inject:javax.inject'.
  pom.xml
Labels: deps-ok

#3985 [WFCORE-4713] Migrating controller maven module to new MSC API
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ControlledProcessStateService.java
  controller/src/test/java/org/jboss/as/controller/AbstractCapabilityResolutionTestCase.java
  controller/src/test/java/org/jboss/as/controller/CompositeOperationHandlerUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/InterleavedSubsystemTestCase.java
  controller/src/test/java/org/jboss/as/controller/MetricsRegistrationTestCase.java
  controller/src/test/java/org/jboss/as/controller/MetricsUndefinedValueUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/OperationTimeoutUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/RemoveNotEsistingResourceTestCase.java
  controller/src/test/java/org/jboss/as/controller/SocketCapabilityOnHostResolutionUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/ServerService.java
Labels: deps-ok

#3997 [WFCORE-4728] Add javax.inject as a banned dependency
  pom.xml
Labels: deps-ok

#3998 [WFCORE-4688] Support OpenJ9 GC logging in the standalone scripts.
  core-feature-pack/src/main/resources/content/bin/common.ps1
  core-feature-pack/src/main/resources/content/bin/standalone.bat
  core-feature-pack/src/main/resources/content/bin/standalone.sh
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
Labels: deps-ok

#3999 [WFCORE-4732] Upgrade wildfly-server-provisioning-maven-plugin from 1…
  pom.xml
Labels: deps-ok

#3996 [WFCORE-4727] Remove no longer needed constructors
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
Labels: deps-ok

#4000 [WFCORE-4734] Upgrade Jackson Databind test dep to 2.9.10.1
  pom.xml
Labels: deps-ok
