Repository wildfly/wildfly-core, pull requests merged in 2019-05, with the labels that each got.

#3764 Aggregate Pull Request
  controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
  controller/src/main/java/org/jboss/as/controller/services/path/AbsolutePathService.java
  controller/src/main/java/org/jboss/as/controller/services/path/AbstractPathService.java
  controller/src/main/java/org/jboss/as/controller/services/path/RelativePathService.java
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/DefaultSSLContextService.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser7_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_7_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-7.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
  pom.xml
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/KDCServerAnnotationProcessor.java
Labels: deps-ok

#3756 [WFCORE-4446] Migrating AbsolutePathService & RelativePathService to new MSC API
  controller/src/main/java/org/jboss/as/controller/services/path/AbsolutePathService.java
  controller/src/main/java/org/jboss/as/controller/services/path/AbstractPathService.java
  controller/src/main/java/org/jboss/as/controller/services/path/RelativePathService.java
Labels: deps-ok, ready-for-merge

#3761 [WFCORE-4457] Ensure that any tests that set the JVM wide default SSLContext restore it to the default default.
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/DefaultSSLContextService.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
Labels: deps-ok, ready-for-merge

#3763 [WFCORE-4458] Do not re-wrap a LogContextSelector if it's already bee…
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
Labels: deps-ok, ready-for-merge

#3700 [WFCORE-4355] Introduce a simple event logging API.
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/event/logger/main/module.xml
  core-galleon-pack/pom.xml
  event-logger/README.adoc
  event-logger/pom.xml
  event-logger/src/main/java/org/wildfly/event/logger/AbstractEvent.java
  event-logger/src/main/java/org/wildfly/event/logger/AbstractEventLogger.java
  event-logger/src/main/java/org/wildfly/event/logger/AsyncEventLogger.java
  event-logger/src/main/java/org/wildfly/event/logger/Event.java
  event-logger/src/main/java/org/wildfly/event/logger/EventFormatter.java
  event-logger/src/main/java/org/wildfly/event/logger/EventLogger.java
  event-logger/src/main/java/org/wildfly/event/logger/EventWriter.java
  event-logger/src/main/java/org/wildfly/event/logger/JsonEventFormatter.java
  event-logger/src/main/java/org/wildfly/event/logger/LazyEvent.java
  event-logger/src/main/java/org/wildfly/event/logger/StandardEvent.java
  event-logger/src/main/java/org/wildfly/event/logger/StandardEventLogger.java
  event-logger/src/main/java/org/wildfly/event/logger/StdoutEventWriter.java
  event-logger/src/test/java/org/wildfly/event/logger/AbstractEventLoggerTestCase.java
  event-logger/src/test/java/org/wildfly/event/logger/AsyncEventLoggerTestCase.java
  event-logger/src/test/java/org/wildfly/event/logger/QueuedJsonWriter.java
  event-logger/src/test/java/org/wildfly/event/logger/StandardEventLoggerTestCase.java
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: Feature, deps-changed, ready-for-merge

#3769 [WFCORE-4464] Upgrade WildFly Elytron to 1.9.0.CR5
  pom.xml
Labels: deps-ok, ready-for-merge

#3770 [WFCORE-4460] jboss-cli.sh doesn't return json when the output command is 'failed'
  cli/src/main/java/org/jboss/as/cli/handlers/OperationRequestHandler.java
Labels: deps-ok, ready-for-merge

#3772 [WFLY-6143] Server interceptors: add phases
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok, ready-for-merge

#3774 [WFCORE-4466] Upgrade to Galleon and Plugins 4.0.0.Final
  pom.xml
Labels: deps-ok

#3775 [WFCORE-4467] / [WFCORE-4468] WildFly Elytron Component Upgrades
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  core-galleon-pack/pom.xml
  pom.xml
Labels: deps-changed

#3776 [WFCORE-4469] Upgrade Remoting JMX to 3.0.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3729 [WFCORE-4407] Configure Elytron domain services with LAZY initial mode
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TrivialAddHandler.java
  elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
Labels: deps-ok, ready-for-merge

#3780 [WFCORE-4476] Upgrade Wildfly Elytron to 1.9.1.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3778 [WFCORE-4400] Validation of 'host-context-map' attribute of 'server-s…
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-7.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-5.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-6.0.xml
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/ServerSslSniContextTestCase.java
Labels: deps-ok, ready-for-merge

#3783 [WFCORE-4480] Upgrade Remoting JMX to 3.0.3.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3785 [WFCORE-4333] Check that the size of the sub-handlers is equal before…
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
Labels: deps-ok, ready-for-merge

#3789 [WFCORE-4492] Upgrade to component matrix 1.0.3.Final
  pom.xml
Labels: deps-ok

#3790 [WFCORE-4479] Upgrade jboss-logmanager from 2.1.10.Final to 2.1.11.Fi…
  pom.xml
Labels: deps-ok, ready-for-merge

#3259 [WFCORE-323] Allow multistep op handling to defer resolution of the O…
  controller/src/main/java/org/jboss/as/controller/operations/MultistepUtil.java
  controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/OperationRouting.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationResolver.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerOperationsResolverHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AbstractConfigurationChangesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ConfigurationChangesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ExtensionManagementTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HcExtensionAndSubsystemManagementTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/OperationErrorTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/optypes/OpTypesExtension.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/ExtensionSubsystemCompositeTestCase.java
Labels: deps-ok, ready-for-merge
