Repository wildfly/wildfly-core, pull requests merged in 2019-08, with the labels that each got.

#3864 Fix for WFCORE-4428, upgrade to aesh 2.4 and readline 2.0
  cli/pom.xml
  cli/src/main/java/org/jboss/as/cli/handlers/batch/BatchRunHandler.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/HelpSupport.java
  cli/src/test/java/org/jboss/as/cli/impl/aesh/HelpSupportTestCase.java
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/aesh/main/module.xml
  core-galleon-pack/pom.xml
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliConfigTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
Labels: deps-changed, ready-for-merge

#3874 [WFCORE-4577] Upgrade WildFly Elytron to 1.10.0.CR4
  pom.xml
Labels: deps-ok, ready-for-merge

#3877 Update README.md
  README.md
Labels: ready-for-merge

#3879 WFCORE-4586 Don't fail on wrong copied hashes if override options pro…
  patching/src/main/java/org/jboss/as/patching/runner/AbstractPatchingTask.java
  patching/src/main/java/org/jboss/as/patching/runner/IdentityPatchContext.java
  patching/src/main/java/org/jboss/as/patching/runner/PatchingTaskContext.java
  patching/src/test/java/org/jboss/as/patching/tests/PatchUndoTestCase.java
Labels: deps-ok, ready-for-merge

#3881 [WFCORE-4587] Clarify description of 'maximum-cert-path'
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
Labels: deps-ok, ready-for-merge

#3882 [WFCORE-4525] Disable CLI embedded server tests that do not work with…
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
Labels: deps-ok, ready-for-merge

#3883 [WFCORE-4551] Configure JDBC Realm services to LAZY initial mode when…
  elytron/src/main/java/org/wildfly/extension/elytron/JdbcRealmDefinition.java
Labels: deps-ok, ready-for-merge

#3884 WFCORE-4593 Make ServiceRemoveStepHandler(AbstractAddStepHandler) public
  controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
Labels: deps-ok, ready-for-merge

#3885 [WFCORE-4538] Disabling SSL & SASL failing tests on JDK14+
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosHttpMgmtSaslTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosNativeMgmtSaslTestCase.java
Labels: deps-ok, ready-for-merge

#3158 [WFCORE-3670] load correct additional module with alias name.
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
Labels: deps-ok

#3887 [WFCORE-4590] Upgrade jboss-logmanager from 2.1.13.Final 2.1.14.Final
  pom.xml
Labels: deps-ok

#3878 [WFCORE-4552] Upgrade Undertow to 2.0.24.Final
  pom.xml
Labels: deps-ok, fixme

#3866 [WFCORE-4571] Value of 'soft-fail' attribute in 'elytron/trust-manager'…
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
Labels: deps-ok, ready-for-merge

#3876 [WFCORE-4556] Upgrade jboss-remoting version to 5.0.14.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3886 [WFCORE-4579] Upgrade jboss-logging from 3.4.0.Final to 3.4.1.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3893 [WFCORE-4601] Upgrade XNIO version to 3.7.3.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3894 [WFCORE-4600] Resolve problems with ByteBufferSlicePool usage that are affecting memory footprint and causing leaks
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
  io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolService.java
Labels: deps-ok

#3895 [WFCORE-4580] Upgrade JBoss Marshalling from 2.0.7.Final to 2.0.8.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3896 [WFCORE-4604] Disable testEndpointConfigurationViaSubsystemRoot
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
Labels: deps-ok, ready-for-merge

#3892 WFCORE-4599 Handle wildfly-config.xml better for authentication
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationContextAssociationProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
Labels: deps-ok

#3899 [WFCORE-4603]: Replace Deployment --runtime-name option not working.
  server/src/main/java/org/jboss/as/server/deployment/DeploymentReplaceHandler.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/DeploymentTestCase.java
Labels: deps-ok, ready-for-merge

#3900 [WFCORE-4606] Upgrade Jackson Databind to 2.9.9.3
  pom.xml
Labels: deps-ok, ready-for-merge

#3902 [WFCORE-4608] Upgrade undertow to 2.0.25.Final
  pom.xml
Labels: deps-ok

#3901 [WFCORE-4607] Don't force a clone of the entire model just to check i…
  server/src/main/java/org/jboss/as/server/deployment/DeploymentReplaceHandler.java
Labels: deps-ok, ready-for-merge

#3871 [WFCORE-4574] Adding code to shut down ScheduledThreadPoolExecutor cr…
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/HttpAuthenticationFactoryService.java
Labels: deps-ok, ready-for-merge

#3880 WFCORE-1446 EJB thread pool keepalive not honored and is not reusing …
  threads/src/main/java/org/jboss/as/threads/CommonAttributes.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorAdd.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorMetricsHandler.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorRemove.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorService.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorWriteAttributeHandler.java
  threads/src/main/java/org/jboss/as/threads/ManagedEnhancedQueueExecutor.java
  threads/src/main/java/org/jboss/as/threads/ThreadPoolManagementUtils.java
  threads/src/main/java/org/jboss/as/threads/ThreadsLogger.java
  threads/src/main/java/org/jboss/as/threads/ThreadsParser.java
  threads/src/main/resources/org/jboss/as/threads/LocalDescriptions.properties
Labels: deps-ok, ready-for-merge

#3898 [WFCORE-4605] Test applying legacy one-off patches to a slimmed insta…
  testsuite/patching/pom.xml
  testsuite/patching/src/test/java/org/jboss/as/test/patching/GalleonSlimmedOneOffPatchingScenariosTestCase.java
Labels: deps-ok, ready-for-merge

#3903 [WFCORE-4610] TestModule should not write modules in any *build/targe…
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/TestModule.java
Labels: deps-ok, ready-for-merge

#3909 [WFCORE-4614] Remove unneeded throws statement and related org.jboss.…
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/base/AbstractMgmtTestBase.java
Labels: deps-ok, ready-for-merge

#3907 [WFCORE-4612] ExternalModuleDependencySpecService should make depende...
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
Labels: deps-ok

#3913 [WFCORE-4597] Use PhaseContext target to start external module spec services being tracked by the stability monitor
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
Labels: deps-ok, ready-for-merge

#3915 [WFCORE-4620] Upgrade WildFly Elytron to 1.10.0.CR5
  pom.xml
Labels: Feature, deps-ok, ready-for-merge

#3868 [WFCORE-4562] Update the pre-recorded messages in CertificateAuthorit…
  elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/Readme.txt
  elytron/src/test/resources/org/wildfly/extension/elytron/account.keystore
Labels: deps-ok, ready-for-merge

#3890 [WFCORE-4375] Provide ability to easily apply certain JBoss module libraries to all deployments running in a server
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
Labels: deps-ok

#3912 Fix for WFCORE-4616, Layer for core security-realms and management layer update
  core-galleon-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
  core-galleon-pack/src/main/resources/feature_groups/management.xml
  core-galleon-pack/src/main/resources/layers/standalone/core-security-realms/layer-spec.xml
  core-galleon-pack/src/main/resources/layers/standalone/core-server/layer-spec.xml
  core-galleon-pack/src/main/resources/layers/standalone/legacy-management/layer-spec.xml
  core-galleon-pack/src/main/resources/layers/standalone/management/layer-spec.xml
  testsuite/layers/pom.xml
Labels: deps-ok, ready-for-merge

#3916 [WFCORE-4619] Upgrade JBoss Marshalling to 2.0.9.Final
  pom.xml
Labels: deps-ok

#3927 [WFCORE-4634] Upgrade WildFly Elytron to 1.10.0.CR6
  pom.xml
Labels: deps-ok, ready-for-merge

#3856 [WFCORE-4394] Enhanced Audit Logging for Elytron - RFC Support and Configuring Reconnects
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuditResourceDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SimpleSyslogServer.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/syslog-audit-logging.xml
Labels: Feature, deps-ok, ready-for-merge

#3825 [WFCORE-4496] Adding principal-transformer to aggregate-realm
  elytron/src/main/java/org/wildfly/extension/elytron/AggregateRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-2/f/i/firstUser.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-2/s/e/secondUser.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/security-realms.xml
Labels: 10.x, Feature

#3618 [WFCORE-4227] Add the ability for the CLI SSL security commands to be a…
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/InteractiveSecurityBuilder.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/AbstractEnableSSLCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/OptionActivators.java
  cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/ssl/command_resources.properties
  testsuite/embedded/pom.xml
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/AcmeMockServerBuilder.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessWrapper.java
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/management/cli/README.txt
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/management/cli/account.keystore
  testsuite/standalone/pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: 10.x, Feature, deps-ok, ready-for-merge

#3908 [WFCORE-4336] Add the ability for a user to add custom filters for loggers and log handlers
  logging/pom.xml
  logging/src/main/java/org/jboss/as/logging/CommonAttributes.java
  logging/src/main/java/org/jboss/as/logging/Element.java
  logging/src/main/java/org/jboss/as/logging/KnownModelVersion.java
  logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
  logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_8_0.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemWriter.java
  logging/src/main/java/org/jboss/as/logging/Namespace.java
  logging/src/main/java/org/jboss/as/logging/PropertyAttributeMarshaller.java
  logging/src/main/java/org/jboss/as/logging/filters/FilterReferenceRecorder.java
  logging/src/main/java/org/jboss/as/logging/filters/FilterResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/filters/Filters.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/loggers/LoggerOperations.java
  logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
  logging/src/main/resources/org/jboss/as/logging/LocalDescriptions.properties
  logging/src/main/resources/schema/jboss-as-logging_8_0.xsd
  logging/src/main/resources/subsystem-templates/logging.xml
  logging/src/test/java/org/jboss/as/logging/AbstractLoggingSubsystemTest.java
  logging/src/test/java/org/jboss/as/logging/FilterConversionTestCase.java
  logging/src/test/java/org/jboss/as/logging/FilterOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingTestEnvironment.java
  logging/src/test/java/org/jboss/as/logging/TestFilter.java
  logging/src/test/modules/javax/json/api/main/module.xml
  logging/src/test/modules/org/glassfish/javax/json/main/module.xml
  logging/src/test/modules/org/jboss/as/logging/test/main/module.xml
  logging/src/test/modules/org/jboss/logging/main/module.xml
  logging/src/test/modules/org/jboss/logmanager/main/module.xml
  logging/src/test/modules/org/wildfly/common/main/module.xml
  logging/src/test/resources/default-subsystem.xml
  logging/src/test/resources/empty-subsystem.xml
  logging/src/test/resources/expressions.xml
  logging/src/test/resources/expressions_7_0.xml
  logging/src/test/resources/logging.xml
  logging/src/test/resources/logging_7_0.xml
  logging/src/test/resources/operations.xml
  logging/src/test/resources/rollback-logging.xml
  logging/src/test/resources/simple-subsystem.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/TestFilter.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/filters/FilterTestCase.java
  testsuite/standalone/src/test/resources/org/jboss/as/test/integration/logging/module.xml
Labels: Feature, deps-ok, ready-for-merge

#3914 [WFCORE-4617] jboss-cli.sh does not error on invalid options
  cli/src/main/java/org/jboss/as/cli/impl/CliLauncher.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
Labels: deps-ok, ready-for-merge

#3917 [WFCORE-4624] Persist interfaces in alphabetical order
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/interfaces/domain.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/interfaces/host.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/interfaces/standalone.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/standalone.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/mgmt_interfaces/standalone_legacy.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/security/users-standalone.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/shipped/standalone.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/domain-transform.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/domain.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/host.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/socketbindinggroups/standalone.xml
  server/src/main/java/org/jboss/as/server/parsing/CommonXml.java
  server/src/main/java/org/jboss/as/server/parsing/InterfacesXml.java
  server/src/main/java/org/jboss/as/server/parsing/SocketBindingsXml.java
Labels: deps-ok, ready-for-merge

#3918 [WFCORE-4625] Expose a util method for standard marshalling of xml el…
  controller/src/main/java/org/jboss/as/controller/AttributeMarshaller.java
  controller/src/main/java/org/jboss/as/controller/DefaultAttributeMarshaller.java
Labels: deps-ok, ready-for-merge

#3928 [WFCORE-4633] Use the "gc.log" name for the IBM J9 JVM as it doesn't …
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
Labels: deps-ok, ready-for-merge

#3933 [WFCORE-4636] The class and module attributes should require all serv…
  logging/src/main/java/org/jboss/as/logging/CommonAttributes.java
Labels: deps-ok

#3931 [WFCORE-4637] Upgrade JBoss / Jakarta JACC to 2.0.0.CR2
  pom.xml
Labels: deps-ok

#3932 [WFCORE-4375] Implement a different comparator loading the jar files
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
  server/src/test/java/org/jboss/as/server/moduleservice/PathComparatorTestCase.java
Labels: deps-ok

#3937 [WFCORE-4640] Add a DUP to the Elytron subsystem that adds the 'javax.security.auth.message.api' and 'javax.security.jacc.api' modules to the deployment
  elytron/src/main/java/org/wildfly/extension/elytron/EESecurityDependencyProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#3938 [WFCORE-4641] Upgrade Undertow to 2.0.26.Final
  pom.xml
Labels: deps-ok

#3936 [WFCORE-4368] / [WFCORE-4369] WildFly Elytron Component Upgrades
  pom.xml
Labels: deps-ok
