Repository wildfly/wildfly-core, pull requests merged in 2019-12, with the labels that each got.

#4028 [WFCORE-3948] Make AttachmentList thread safe
  server/src/main/java/org/jboss/as/server/deployment/AttachmentList.java
Labels: deps-ok

#4025 [WFCORE-4759] Upgrade to Galleon and WFGP 4.2.1.Final
  core-galleon-pack/wildfly-feature-pack-build.xml
  pom.xml
Labels: deps-ok

#4029 [WFCORE-4765] Remove artifacts licenses
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-galleon-pack/pom.xml
Labels: deps-ok

#4032 [WFCORE-4769] Upgrade WildFly Elytron to 1.11.0.CR3
  pom.xml
Labels: deps-ok

#3976 [WFCORE-4704] WS integration with WildFly Elytron - AuthenticationClient for Authentication / SSL
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_9_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/AuthenticationClientTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
Labels: Feature

#4030 [WFCORE-4766] Report error if triggering rollback due to missing services.
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/management/ManagementInterfaceAddStepHandler.java
Labels: deps-ok

#3929 [WFCORE-4635] Introducing new CapabilityServiceBuilder.provides() method
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: deps-ok

#4033 [WFCORE-2356] Failure in a step ResultHandler should not always be reported as occurring during rollback
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Labels: deps-ok

#4035 [WFCORE-4771] Upgrade Elytron Web to 1.7.0.CR3
  pom.xml
Labels: deps-ok

#4034 [WFCORE-3948] Revert the CopyOnWriteArrayList approach in favor of Sy…
  server/src/main/java/org/jboss/as/server/deployment/AttachmentList.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
Labels: deps-ok

#3891 [WFCORE-4598] Migrating remoting maven module to new MSC API
  controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java
  controller/src/main/java/org/jboss/as/controller/remote/ModelControllerClientOperationHandlerFactoryService.java
  controller/src/main/java/org/jboss/as/controller/remote/ModelControllerOperationHandlerFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/MasterDomainControllerOperationHandlerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/NativeManagementServices.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractChannelOpenListenerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractOutboundConnectionService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractStreamServerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpListenerRegistryService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/InjectedNetworkBindingStreamServerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/InjectedSocketBindingStreamServerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionWriteHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingConnectorBindingInfoService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementChannelOpenListenerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementChannelRegistryService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java
  remoting/tests/src/test/java/org/jboss/as/remoting/AbstractRemotingSubsystemBaseTest.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
  server/src/main/java/org/jboss/as/server/operations/NativeManagementServices.java
  server/src/main/java/org/jboss/as/server/operations/NativeRemotingManagementAddHandler.java
Labels: deps-ok

#4037 [WFCORE-4773] Upgrade WildFly OpenSSL to 1.0.9.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4036 [WFCORE-1110] Tests for configuring custom headers
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpManagementConstantHeadersTestCase.java
Labels: deps-ok

#4039 Fix for WFCORE-4776, NPE in EmbeddedServer for version/help arguments
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
Labels: deps-ok

#4038 [WFCORE-4774] Avoid circular recursion searching for capability status
  controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
  controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
Labels: deps-ok

#4043 [WFCORE-4778] Fixing regression - partial revert of WFCORE-4487
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheService.java
Labels: deps-ok
