Repository wildfly/wildfly-core, pull requests merged in 2019-09, with the labels that each got.

#3940 [WFCORE-4375] Implement a different comparator loading the jar files
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
  server/src/test/java/org/jboss/as/server/moduleservice/PathComparatorTestCase.java
Labels: deps-ok

#3942 [WFCORE-4644] Upgrade JBoss / Jakarta JACC to 2.0.0.CR3
  pom.xml
Labels: 10.x, deps-ok

#3941 [WFCORE-4643] The secure-management layer should set up the /core-ser…
  core-galleon-pack/src/main/resources/layers/standalone/secure-management/layer-spec.xml
Labels: deps-ok

#3935 [WFCORE-4623] Intermittent failures in IdentityOperationsTestCase
  elytron/src/test/java/org/wildfly/extension/elytron/IdentityOperationsTestCase.java
Labels: deps-ok, ready-for-merge

#3944 [WFCORE-4647] Upgrade WildFly Elytron to 1.10.1.Final
  pom.xml
Labels: deps-ok

#3945 [WFCORE-4651] Upgrade WildFly Open SSL to 1.0.8.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3949 [WFCORE-4654] Upgrade to JBoss / Jakarta JASPI 2.0.0.CR2
  pom.xml
Labels: deps-ok, ready-for-merge

#3955 [WFCORE-4663] Upgrade JBoss MSC to 1.4.11.Final
  pom.xml
  server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
Labels: 10.x, deps-ok, ready-for-merge

#3956 [WFCORE-4664] Upgrade wildfly-build-tools to 1.2.12.Final
  pom.xml
Labels: 10.x, deps-ok, ready-for-merge

#3952 [WFCORE-4659] reverting change of not defining the static auth context
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
Labels: Blocker, deps-ok

#3957 [WFCORE-4669] Minor license cleanup
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/content/docs/licenses/gnu general public license version 2, with classpath exception.txt
Labels: deps-ok

#3958 [WFCORE-4631] Remove the reconnect tests which check if the operation…
  elytron/src/test/java/org/wildfly/extension/elytron/SyslogAuditLogTestCase.java
Labels: deps-ok

#3959 [WFCORE-4671] Upgrade WildFly Elytron to 1.10.2.Final
  pom.xml
Labels: 10.x, Blocker, deps-ok

#3960 [WFCORE-4677] Upgrade WildFly Elytron to 1.10.3.Final
  pom.xml
Labels: deps-ok
