Repository wildfly/wildfly-core, pull requests merged in 2019-06, with the labels that each got.

#3788 [WFCORE-4472] Upgrade Undertow to 2.0.21.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3796 [WFCORE-4490] [WFCORE-4491] Upgrade JBoss Remoting to 5.0.12.Final and Xnio to 3.7.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3797 [WFCORE-4489] Wrap setting the JAVA_OPTS in quotes for the batch script.
  core-feature-pack/src/main/resources/content/bin/standalone.bat
  testsuite/scripts/pom.xml
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/AddUserTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/Environment.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptProcess.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
Labels: deps-ok, ready-for-merge

#3799 [WFCORE-4500] Withdraw the security identity supplier when MBeanServerService stops
  jmx/src/main/java/org/jboss/as/jmx/MBeanServerService.java
Labels: deps-ok, ready-for-merge

#3800 WFLY-12126 Fix issue with Java installations containing a space character
  core-feature-pack/src/main/resources/content/bin/common.sh
Labels: deps-ok, ready-for-merge

#3792 [WFCORE-323] Skip domain mode special routing for composite steps tar…
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/OperationRouting.java
Labels: deps-ok, ready-for-merge

#3802 [WFCORE-4506] Upgrade JBoss MSC to 1.4.6.Final.
  pom.xml
Labels: deps-ok, ready-for-merge

#3803 [WFCORE-4507] Upgrade the Jackson version to 2.9.9
  pom.xml
Labels: deps-ok, ready-for-merge

#3804 [WFCORE-4508] Use the correct locking mechanism when reading the attr…
  controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
Labels: deps-ok, ready-for-merge

#3806 [WFCORE-4509] Upgrade JBoss MSC to 1.4.7.Final
  pom.xml
Labels: deps-ok

#3807 [WFCORE-4510] Configure the remoting subsystem endpoint by reading fr…
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
Labels: deps-ok

#3821 [WFCORE-4528] / [WFCORE-4529] WildFly Elytron Component Upgrades
  pom.xml
Labels: deps-ok, ready-for-merge

#3817 [WFCORE-4521] PropertyFileFinder should not validate perms for non-ex…
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinder.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinderPermissionsTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinderTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyTestHelper.java
Labels: deps-ok, ready-for-merge

#3818 [WFCORE-4518] Disable the testEndpointConfigurationViaDeprecatedChild…
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
Labels: deps-ok, ready-for-merge

#3820 [WFCORE-4526] Upgrade Undertow version to 2.0.22.Final
  pom.xml
Labels: deps-ok

#3798 [WFCORE-4440] Changes made via management operations in static-discovery are not reflec…
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/StaticDiscoveryResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/StaticDiscoveryWriteAttributeHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CLIDiscoveryOptionsTestCase.java
Labels: deps-ok, ready-for-merge

#3819 [WFCORE-4519] Fix content references management when a deployment is replaced
  deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/DeploymentFullReplaceHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/deployment/ServerGroupDeploymentReplaceHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
Labels: deps-ok, ready-for-merge

#3826 [WFCORE-4498] Only obtain the Provider[] once and re-use it.
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
Labels: deps-ok, ready-for-merge

#3827 [WFCORE-4531] Eliminating WildFly naming workaround
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/extension/io/main/module.xml
Labels: deps-ok, ready-for-merge

#3829 [WFCORE-4352] Enabling disabled tests since they started to pass on latest JDK13 ea b 25
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/auditlog/AuditLogToTLSSyslogTestCase.java
Labels: deps-ok, ready-for-merge

#3781 Capabilities Deprecated MSC API Cleanup
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolResourceDefinition.java
  io/subsystem/src/main/java/org/wildfly/extension/io/BufferPoolService.java
  io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
  io/subsystem/src/main/java/org/wildfly/extension/io/WorkerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemAdd.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/BindingGroupAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingService.java
  server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingService.java
  server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingService.java
  server/src/main/java/org/jboss/as/server/services/net/SocketBindingManagerService.java
  server/src/main/java/org/jboss/as/server/services/net/SocketBindingService.java
Labels: deps-ok

#3833 [WFCORE-4539] Upgrade JBoss MSC to 1.4.8.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3832 [WFCORE-4538] Disabling SSL & SASL failing tests for now on JDK13+
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosHttpMgmtSaslTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosNativeMgmtSaslTestCase.java
Labels: deps-ok, ready-for-merge

#3828 [WFCORE-4533] Upgrade jboss-logmanager from 2.1.11.Final to 2.1.13.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3823 [WFCORE-4362] Make the certificate authority used by a certificate-authority-account configurable
  elytron/src/main/java/org/wildfly/extension/elytron/AcmeAccountService.java
  elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
  elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
  elytron/src/main/java/org/wildfly/extension/elytron/CertificateAuthorityAccountDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/CertificateAuthorityDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-8.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
Labels: Feature, deps-ok, ready-for-merge

#3811 [WFCORE-4517] Add back the --add-modules=java.se argument for modular…
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: deps-ok, ready-for-merge

#3784 [WFCORE-4487] Migrate domain-management maven module to new MSC API
  domain-management/src/main/java/org/jboss/as/domain/management/CallbackHandlerFactory.java
  domain-management/src/main/java/org/jboss/as/domain/management/LegacyConfigurationChangeResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessIdentityResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionAddHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/AbstractKeyManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/AbstractPlugInService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/AbstractTrustManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/CallbackHandlerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/ClientCertCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/DomainManagedServerCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/FileKeyManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/FileTrustManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/JaasCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/KerberosCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/KeytabIdentityFactoryService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/KeytabService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapSearcherCache.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapSubjectSupplementalService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LocalCallbackHandlerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInAuthenticationCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInLoaderService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInSubjectSupplemental.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesFileLoader.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PropertiesSubjectSupplemental.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderKeyManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/ProviderTrustManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SSLContextService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecretIdentityService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SubjectSupplementalService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/UserDomainCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/UserPropertiesFileLoader.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/PropertyFileFinder.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/UpdatePropertiesHandler.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/KeytabIdentityFactoryServiceTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/LdapCacheServiceMockTest.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/PropertiesFileLoaderTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/SecurityRealmServiceUtilTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyPatternTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/adduser/PropertyTestHelper.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/realms/BaseLdapSuiteAuthenticationReferralsTest.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/realms/BaseLdapSuiteTest.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/realms/LdapAuthenticationSuiteTest.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/realms/SecurityRealmHelper.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/realms/SecurityRealmTestBase.java
  host-controller/src/main/java/org/jboss/as/host/controller/ServerInventoryService.java
Labels: deps-ok, ready-for-merge

#3801 WFCORE-4502 Unify line-endings of bat scripts (regression against WF15)
  .gitattributes
Labels: deps-ok, ready-for-merge

#3837 [WFCORE-4544] Generate license info for deps newly added in WF Core 9
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-galleon-pack/pom.xml
Labels: deps-ok, ready-for-merge

#3840 [WFCORE-4546] Upgrade WildFly Elytron to 1.10.0.CR2
  pom.xml
Labels: deps-ok, ready-for-merge

#3838 [WFCORE-4539] Upgrade JBoss MSC to 1.4.8.Final
  pom.xml
Labels: 9.x

#3750 [WFCORE-3947] Support SSL Certificate revocation using OCSP
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml
Labels: 10.x, Feature, deps-ok, ready-for-merge

#3831 [WFCORE-4501] Provide XML schema for credential-reference
  controller/src/main/resources/schema/README.md
  controller/src/main/resources/schema/wildfly-credential-reference_1_0.xsd
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
  server/src/main/resources/schema/wildfly-config_10_0.xsd
Labels: deps-ok, ready-for-merge

#3846 Minor license fixes
  core-feature-pack/src/license/core-feature-pack-licenses.xml
Labels: deps-ok, ready-for-merge

#3847 Minor license fixes
  core-feature-pack/src/license/core-feature-pack-licenses.xml
Labels: 9.x, ready-for-merge

#3822 [WFCORE-4495] Upgrade wildfly-openssl to 1.0.7.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#3843 [WFCORE-4543] Don't assume it's safe to use the system log context. I…
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
Labels: deps-ok, ready-for-merge

#3848 [WFCORE-4495] Upgrade wildfly-openssl to 1.0.7.Final
  pom.xml
Labels: 9.x

#3845 [WFCORE-4361] Add evidence decoders in the Elytron subsystem
  elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
  elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/DomainService.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser4_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/EvidenceDecoderDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_8_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/CustomEvidenceDecoder.java
  elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-8.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
Labels: 10.x, Feature, deps-ok, ready-for-merge
