Repository wildfly/wildfly-core, pull requests merged in 2020-06, with the labels that each got.

#4187 [WFCORE-4950] Regression: Legacy Ldap Realm securing EJB with JDK8 not working
  domain-management/src/main/java/org/jboss/as/domain/management/connections/ldap/LdapConnectionManagerService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/UserLdapCallbackHandler.java
Labels: deps-ok

#4220 [WFCORE-4899] Upgrade jboss-modules to 1.10.1.Final
  pom.xml
Labels: deps-ok

#4221 [WFCORE-4988] Upgrade Undertow to 2.1.2.Final
  pom.xml
Labels: deps-ok

#4222 [WFCORE-4990] Upgrade Undertow to 2.1.3.Final
  pom.xml
Labels: 12.x, Blocker, deps-ok

#4223 [WFCORE-4989] Upgrade WildFly Elytron to 1.12.1.Final
  pom.xml
Labels: 12.x, Blocker, deps-ok

#4209 Fix for WFCORE-4972, LayersTest doesn't follow module aliases
  testsuite/shared/src/main/java/org/jboss/as/test/layers/Scanner.java
Labels: deps-ok

#4226 [WFCORE-4991] Upgrade jboss-logmanager from 2.1.15.Final to 2.1.16.Final.
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/LoggingServiceActivator.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/handlers/RotatingFileHandlerTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/AbstractRotatingFileHandlerTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/PeriodicSizeRotatingFileHandlerTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/SizeRotatingFileHandlerTestCase.java
Labels: deps-ok

#4227 [WFCORE-4996] Upgrade WildFly Galleon Plugins from 4.2.6.Final to 4.2.8.Final
  pom.xml
Labels: deps-ok

#4217 Fix for WFCORE-4984, Upgrade tests to use wildfly-jar-maven-plugin Alpha3
  pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
Labels: deps-ok

#4230 [WFCORE-5002] Upgrade the minimum Maven version to 3.6.0 and default …
  .mvn/jvm.config
  .mvn/wrapper/maven-wrapper.properties
  README.md
  pom.xml
Labels: deps-ok

#4229 [WFCORE-5001] Upgrade WildFly Elytron to 1.13.0.CR1
  pom.xml
Labels: deps-ok

#4235 [WFCORE-4999] Remove Zanata configuration as the service is no longer…
  .gitignore
  checkstyle-suppressions.xml
  pom.xml
  zanata.xml
Labels: deps-ok

#4240 [WFCORE-5016] Have the feature pack 'source modules' produce zip arti…
  core-feature-pack/common/assembly.xml
  core-feature-pack/common/pom.xml
  core-feature-pack/ee-8-api/assembly.xml
  core-feature-pack/ee-8-api/pom.xml
  core-feature-pack/galleon-common/assembly.xml
  core-feature-pack/galleon-common/pom.xml
  core-feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#4131 [WFCORE-4748] Allow the MODULE_OPTS to be set
  controller/src/main/java/org/jboss/as/controller/parsing/Element.java
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
  core-feature-pack/common/src/main/resources/content/bin/standalone.ps1
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/jvm/JvmTransformersTestCase.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/jvm/domain-full.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/jvm/domain-with-expressions.xml
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/servergroup/servergroup.xml
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/JvmTransformers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmAttributes.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmElement.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmOptionsElement.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerRestartRequiredServerConfigWriteAttributeHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/JvmXml.java
  host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/logger/LauncherMessages.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  server/src/main/resources/schema/wildfly-config_14_0.xsd
  testsuite/scripts/pom.xml
  testsuite/scripts/src/test/java/org/wildfly/common/test/LoggingAgent.java
  testsuite/scripts/src/test/java/org/wildfly/common/test/ServerConfigurator.java
  testsuite/scripts/src/test/java/org/wildfly/common/test/ServerHelper.java
  testsuite/scripts/src/test/java/org/wildfly/launcher/test/LauncherTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
Labels: Feature, deps-ok

#4241 [WFCORE-5017] Upgrade jakarta.inject-api 1.0.1
  pom.xml
Labels: deps-ok

#4239 [WFCORE-4707] generate proper service name of capability if dynamic p…
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
Labels: deps-ok

#4242 [WFCORE-944] truststore path is ignored if provider is not JKS
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
  testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/SSLTruststoreUtil.java
Labels: deps-ok, ready-for-merge

#4236 [WFCORE-5004] TlsTestCase#testReloadTrustManager fails on IBM Java 8
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
Labels: deps-ok

#4244 [WFCORE-5019] Upgrade jboss-invocation 1.5.3.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4243 [WFCORE-5018] Upgrade woodstox:stax2-api 4.2.1
  pom.xml
Labels: deps-ok
