Repository wildfly/wildfly-core, pull requests merged in 2020-03, with the labels that each got.

#4088 [WFCORE-4824] Upgrade JBoss Modules from 1.9.2.Final to 1.10.0.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4085 Updating mockserver. Exclusion of dependency from xom.io7m
  elytron/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#4087 [WFCORE-4862] Return ServerEnvironmentStatus.ERROR in case of incorrect git server start argument values
  server/src/main/java/org/jboss/as/server/Main.java
Labels: deps-ok

#4094 [WFCORE-4825] Upgrade Undertow to 2.0.30.Final
  pom.xml
Labels: deps-ok

#4093 [WFCORE-4865] Upgrade Remoting JMX to 3.0.4.Final
  pom.xml
Labels: deps-ok

#4080 [WFCORE-4833] Allow TrivialAddHandler and AuthenticationFactories sta…
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationFactoryDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TrivialAddHandler.java
Labels: deps-ok

#4058 [WFCORE-4764] Enable web console just before starting the managed server when the domain controller is booting up
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailability.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailabilityService.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiCheckHandler.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
  domain-http/interface/src/test/java/org/jboss/as/domain/http/server/ConsoleAvailabilityUnitTestCase.java
  domain-http/interface/src/test/java/org/jboss/as/domain/http/server/TestModelControllerService.java
  host-controller/pom.xml
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/ApplicationServerService.java
  server/src/main/java/org/jboss/as/server/BootstrapListener.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Labels: deps-ok, ready-for-merge

#4061 [WFCORE-4803] EJB Client authentication does not work using SASL DIGEST-MD5 and EXTERNAL mechanisms in Legacy security
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/SecurityRealmServiceUtilTestCase.java
Labels: deps-ok

#4091 [WFCORE-4864] Bump jackson-databind from 2.9.10.1 to 2.10.1
  pom.xml
Labels: deps-ok

#4100 Remove patch-config xsds, they are not used here
  patching/src/main/resources/patch-config.xsd
  patching/src/main/resources/patch-config_1_1.xsd
  patching/src/main/resources/patch-config_1_2.xsd
Labels: deps-ok

#4098 [WFCORE-4878] Upgrade WildFly OpenSSL to 1.0.10.Final
  pom.xml
Labels: deps-ok

#4089 [WFCORE-4621] Create wildflyee.api static module to serve the Jakarta…
  core-feature-pack/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: 12.x, deps-ok

#4099 [WFCORE-4875] Provide common capability for Remoting connectors.
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorResource.java
Labels: deps-ok

#4101 [WFCORE-4881] Upgrade XNIO to 3.8.0.Final
  pom.xml
Labels: deps-ok

#4096 [WFCORE-4876] Upgrade JBoss Remoting to 5.0.18.Final
  pom.xml
Labels: deps-ok

#4069 WFCORE-4819 Add OperationDefinition generated by default SimpleResourceDefinition logic never contains parameters
  controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/OperationDescriptor.java
  controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
  controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
Labels: 12.x, deps-ok

#4097 Fix for WFCORE-4877, Move testsuite/layers in ts.layers profile
  testsuite/layers/pom.xml
  testsuite/pom.xml
Labels: deps-ok

#4092 [WFCORE-4653] Upgrade picketbox to 5.0.3.Final-redhat-00005
  pom.xml
Labels: deps-ok

#4102 [WFCORE-4874] Turn pre-computed annotation index loading error into a…
  server/src/main/java/org/jboss/as/server/deployment/annotation/ResourceRootIndexer.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: deps-ok

#4107 [WFCORE-4883] Fix CompositeOperationTestCase intermittent failures in…
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CompositeOperationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/SlowServiceActivator.java
Labels: deps-ok

#4113 Revert "[WFCORE-4653] Upgrade picketbox to 5.0.3.Final-redhat-00005"
  pom.xml
Labels: deps-ok

#4110 [WFCORE-4886] Upgrade httpclient 4.5.12
  pom.xml
Labels: deps-ok

#4108 [WFCORE-4884] Upgrade wildfly-common 1.5.4.Final
  pom.xml
Labels: deps-ok

#4109 [WFCORE-4885] Upgrade Jandex 2.1.3.Final
  pom.xml
Labels: deps-ok

#4116 [WFCORE-4890] Upgrade WildFly Elytron to 1.11.3.Final
  pom.xml
Labels: deps-ok

#4117 Upgrade slf4j to 1.7.30
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/ch/qos/cal10n/main/module.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/slf4j/ext/main/module.xml
  core-galleon-pack/pom.xml
  logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
  logging/src/main/java/org/jboss/as/logging/LoggingResourceDefinition.java
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-changed

#4112 [WFCORE-4860] If no deployments are defined with their own log contex…
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelector.java
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
Labels: deps-ok

#4120 [WFCORE-4860] Small follow up to original commit for a slight perform…
  logging/src/main/java/org/jboss/as/logging/logmanager/WildFlyLogContextSelectorImpl.java
Labels: deps-ok
