Repository wildfly/wildfly-core, pull requests merged in 2020-12, with the labels that each got.

#4397 Fix for WFCORE-5009, Enhance JBoss CLI generic "command" with support for existing resource
  cli/src/main/java/org/jboss/as/cli/handlers/CommandCommandHandler.java
  cli/src/main/java/org/jboss/as/cli/handlers/GenericTypeOperationHandler.java
  cli/src/main/resources/help/command.txt
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
Labels: Feature, deps-ok, ready-for-merge

#4396 [WFCORE-5197] Upgrade WildFly Elytron to 1.13.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4399 [WFLY-14114] Add module configuration phase for JDBC DriverManager ad…
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#4341 [WFCORE-5095] Add the ability to make use of an automatically generated self-signed certificate with Elytron
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-profile.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/elytron-app.xml
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser12_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_12_0.xsd
  elytron/src/main/resources/subsystem-templates/elytron.xml
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-12.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/SecurityCommandsTestCase.java
Labels: 14.x, Feature, deps-ok, ready-for-merge

#4382 [WFCORE-5181] Expression properties with trailing whitespaces are resolved to a trimmed value
  controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
  controller/src/test/java/org/jboss/as/controller/parsing/ParseUtilsTestCase.java
Labels: deps-ok

#4408 [WFCORE-5207] Add missing enums to host-release type
  server/src/main/resources/schema/wildfly-config_15_0.xsd
Labels: deps-ok

#4384 [WFCORE-482] Add log4j2 support. Added the log4j-api and an implement…
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/logging/log4j/api/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/logmanager/log4j2/main/module.xml
  logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
  logging/src/main/java/org/jboss/as/logging/LoggingModuleDependency.java
  logging/src/main/java/org/jboss/as/logging/LoggingResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingDependencyDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/stdio/LogContextStdioContextSelector.java
  pom.xml
  testsuite/embedded/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/standalone/pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/Log4j2ServiceActivator.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/AbstractLoggingProfilesTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Log4j2LoggingProfilesTestCase.java
Labels: Feature, deps-ok, ready-for-merge

#4409 [WFCORE-5208] Upgrade WildFly OpenSSL to 2.1.2.Final
  pom.xml
Labels: deps-ok

#4410 [WFCORE-5209] Upgrade WildFly Elytron to 1.14.0.Final
  pom.xml
Labels: deps-ok

#4402 [WFCORE-5171] Upgrade XNIO to 3.8.4.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4407 [WFCORE-5204] Upgrade jakarta.inject-api from 1.0.1 to 1.0.3
  pom.xml
Labels: deps-ok, ready-for-merge

#4403 [WFCORE-5188] Upgrade JBoss Modules from 1.10.2.Final to 1.11.0.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4394 WFCORE-5126 WARN if user tries to set unrealistic io subsystem stack-…
  io/subsystem/src/main/java/org/wildfly/extension/io/WorkerAdd.java
  io/subsystem/src/main/java/org/wildfly/extension/io/logging/IOLogger.java
Labels: deps-ok

#4388 [WFCORE-3090] Make script messages around process restarts consistent
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
Labels: deps-ok

#4353 [WFCORE-5151] dir-contexts referral-mode attribute upper/lower case discrepancy
  elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
Labels: deps-ok

#4414 [WFCORE-5210] Add new Phase ID STRUCTURE_EE_DEFAULT_BINDINGS_CONFIG.
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok, ready-for-merge

#4415 [WFCORE-5211] Add DUP Phases for base metrics & health subsystems
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok, ready-for-merge

#4417 [WFCORE-5213] Add 'org.bouncycastle:bcmail-jdk15on' to dependency management to ensure alignment with the other BouncyCastle dependencies defined in WildFly Core.
  pom.xml
Labels: deps-ok

#4199 WFCORE-4967 fix: RequestController drops queued tasks randomly during server start.
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
  request-controller/src/test/java/org/wildfly/extension/requestcontroller/WFCORE4967_TestCase.java
Labels: Stale, deps-ok

#4373 [WFCORE-5013] Remove the WildFly OpenSSL linux-i386, windows-i386, and solaris-x86_64 natives
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
  core-feature-pack/galleon-common/src/main/resources/packages/org.wildfly.openssl/pm/wildfly/tasks.xml
  core-feature-pack/legacy-feature-pack/feature-pack-build.xml
  elytron/pom.xml
  pom.xml
Labels: deps-ok, ready-for-merge

#4385 [WFCORE-4135] Support for read only server configuration directory
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFilePersistenceResource.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationPersister.java
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Labels: Feature, deps-ok

#4392 [WFCORE-5198] Ignore deployment failures such as duplicate classes
  server/src/main/java/org/jboss/as/server/deployment/DeploymentAddHandler.java
Labels: deps-ok, ready-for-merge

#4245 [WFCORE-4994] Add the ability to adjust the case of a user name using an Elytron principal transformer
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser10_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser12_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/PrincipalTransformerDefinitions.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_12_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/users-clear.properties
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/CasePrincipalTransformerTest.java
Labels: Feature, deps-ok, ready-for-merge

#4423 [WFCORE-5218] Upgrade JBoss Remoting to 5.0.20.Final
  pom.xml
Labels: deps-ok

#4422 [WFCORE-5173] Upgrade Undertow to 2.2.3.Final
  pom.xml
Labels: deps-ok

#4401 WFCORE-5202 Update Bouncycastle to 1.67
  pom.xml
Labels: deps-ok

#4425 WFCORE-5220 ibm.jdk module misses jsse and jsse2 paths
  core-feature-pack/common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml
Labels: deps-ok

#4424 [WFCORE-482] Improve the comment on why the privileged action is requ…
  logging/src/main/java/org/jboss/as/logging/stdio/LogContextStdioContextSelector.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Log4j2LoggingProfilesTestCase.java
Labels: deps-ok

#4418 Fix for WFCORE-5206, Remove workaround to access ModuleLoader.installMBeanServer
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
Labels: deps-ok

#4416 [WFCORE-5212] Remove Phase ID 'PARSE_EE_DEFAULT_BINDINGS_CONFIG' as it is replaced by 'STRUCTURE_EE_DEFAULT_BINDINGS_CONFIG'.
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#4428 Fix for WFCORE-5223 and WFCORE-5227, Galleon upgrades
  pom.xml
Labels: 14.x, deps-ok

#4391 [WFCORE-4294] Added java.awt.headless=true into ps1 and bat conf files
  core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
Labels: deps-ok, ready-for-merge
