Repository wildfly/wildfly-core, pull requests merged in 2020-09, with the labels that each got.

#4309 [WFCORE-5108] Drop duplicate FlexBase64 provided in a context that ha…
  remoting/subsystem/src/main/java/org/jboss/as/remoting/SimpleHttpUpgradeHandshake.java
Labels: deps-ok

#4306 Fix for WFCORE-5097, Add an option to the bootable JAR to display the Galleon config
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Constants.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
Labels: deps-ok

#4310 [WFCORE-5107 Provide an equivalent to RemotingConnectorInfo via org.j…
  network/src/main/java/org/jboss/as/network/ProtocolSocketBinding.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingConnectorBindingInfoService.java
Labels: deps-ok

#4308 [WFCORE-5105] Ensure that ProtocolConnectionUtils.connectSync cancels…
  host-controller/src/main/java/org/jboss/as/host/controller/RemoteDomainConnection.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/MasterDomainControllerOperationHandlerService.java
  protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
  protocol/src/test/java/org/jboss/as/protocol/mgmt/ConnectSyncUnitTestCase.java
Labels: deps-ok

#4312 Fix for WFCORE-5110, Bootable JAR doesn't setup the JAXP factories at boot
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Labels: deps-ok

#4313 [WFCORE-5111] Upgrading JBoss MSC from 1.4.11.Final to 1.4.12.Final
  pom.xml
  subsystem-test/framework/pom.xml
Labels: deps-ok

#4315 Fix for WFCORE-5116, Bootable JAR, JMX not properly initialized at boot.
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Labels: deps-ok

#4314 [WFCORE-5080] KeyStoresTestCase fails on IBM Java 8
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
Labels: deps-ok

#4318 [WFCORE-5117] Upgrade to xerces 2.12.0.SP03
  pom.xml
Labels: deps-ok

#4316 Bootable JAR Logging Updates
  bootable-jar/runtime/pom.xml
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Arguments.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableEnvironment.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Constants.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/PropertyUpdater.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Server.java
  bootable-jar/runtime/src/test/java/org/wildfly/core/jar/runtime/ArgumentsTestCase.java
  bootable-jar/runtime/src/test/resources/test-system.properties
Labels: deps-ok

#4317 Fix for WFCORE-5112, Upgrade bootable jar maven plugin to 2.0.0.Beta4
  pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
Labels: deps-ok

#4321 Fix for WFCORE-5119, Bootable JAR - Remove dependency on elytron-private
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Labels: deps-ok

#4250 [WFCORE-5010] Startup error messages caused by expression where expressions are not allowed are confusing
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Labels: 13.x, deps-ok, ready-for-merge

#4325 [WFCORE-5056] Upgrade XNIO to 3.8.2.Final
  pom.xml
Labels: 13.x, deps-ok

#4326 Fix for WFWIP-355, Bootable JAR - scripts in bin folder of the server installation directory are not executable
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
Labels: 13.x, deps-ok

#4327 [WFCORE-5091] / [WFCORE-5127] / [WFCORE-5128] Elytron Component Upgrades
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Labels: 13.x, deps-ok

#4330 [WFCORE-5102] Upgrade Undertow to 2.2.0.Final
  pom.xml
Labels: 13.x, deps-ok

#4328 Fix for WFCORE-5132, Bootable JAR, some tests require a start of the server
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlValidationTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/RcFileTestCase.java
Labels: 13.x, deps-ok

#4329 [WFCORE-5123] / [WFCORE-5124] / [WFCORE-5125] WildFly OpenSSL Component Upgrades
  pom.xml
Labels: 13.x, deps-ok

#4323 [WFCORE-5103] Adding non existent and not required keystore fails
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
Labels: 13.x, deps-ok

#4334 [WFCORE-5136] NPE in ModelControllerMBeanHelper
  jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
  jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
Labels: deps-ok

#4271 [WFCORE-4842] Add tests for TLS 1.3 that make use of the OpenSSL TLS provider
  elytron/pom.xml
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
Labels: 13.x, deps-ok, ready-for-merge

#4333 [WFCORE-5135] Add a test case to verify that banned modules are not provisioned
  testsuite/layers/pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
Labels: 13.x, deps-ok, ready-for-merge

#4336 Fix for WFCORE-5137, Bootable JAR - Security manager is not found
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Labels: 13.x, deps-ok, ready-for-merge

#4338 [WFCORE-5138] Upgrade JBoss Remoting to 5.0.19.Final
  pom.xml
Labels: 13.x, deps-ok, ready-for-merge

#4343 Fix for WFCORE-5142, Upgrade to Galleon 4.2.6.Final
  pom.xml
Labels: deps-ok

#4320 [WFCORE-5118] Cannot get resources from ContextClassLoader with Server Lifecycle Events
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/core-management/main/module.xml
  core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerResourceDefinition.java
  core-management/core-management-subsystem/src/main/java/org/wildfly/extension/core/management/ProcessStateListenerService.java
  testsuite/shared/src/main/java/org/wildfly/test/events/provider/TestListener.java
Labels: deps-ok
