Repository wildfly/wildfly-core, pull requests merged in 2020-04, with the labels that each got.

#4119 [WFCORE-4893] Expose the process state from the embedded server and controller
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcess.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcessImpl.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
Labels: deps-ok

#4118 [WFCORE-4894] Upgrade jackson databind to 2.10.3 ...
  pom.xml
Labels: deps-ok

#4127 [WFCORE-4903] Manually set BASIC authentication header.
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java
Labels: deps-ok

#4144 Dep tree analyser gh actions
  .github/workflows/dep-diff.yml
  .github/workflows/tmp.yml
Labels: deps-ok

#4149 [WFCORE-4921]: Remove unused product.conf
  dist/src/distribution/resources/bin/product.conf
  dist/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/wildfly-core/dir/META-INF/MANIFEST.MF
  dist/src/distribution/resources/modules/system/layers/base/org/jboss/as/product/wildfly-core/module.xml
Labels: deps-ok

#4146 WFCORE-4918 Optimize MMR logic within DiscardAttributeChecker.DEFAULT_VALUE
  controller/src/main/java/org/jboss/as/controller/transform/description/AttributeConverter.java
Labels: deps-ok

#4156 [WFCORE-4897] Upgrade the wildfly-maven-plugin to 2.0.2.Final and ren…
  pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/standalone/pom.xml
Labels: deps-ok

#4138 [11.0.x] [WFCORE-4878] Upgrade WildFly OpenSSL to 1.0.10.Final
  pom.xml
Labels: 11.x

#4158 [WFLY-4908] WriteAttributeHandler should better validate attribute na…
  controller/src/main/java/org/jboss/as/controller/operations/global/EnhancedSyntaxSupport.java
  controller/src/main/java/org/jboss/as/controller/operations/global/WriteAttributeHandler.java
  controller/src/test/java/org/jboss/as/controller/operation/global/EnhancedSyntaxTestCase.java
Labels: deps-ok

#4148 [WFCORE-4920] Remove the redundant "EAPRepositoryReachableUtil" and related calls as this is no longer used.
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/AbstractCoreModelTest.java
  model-test/src/main/java/org/jboss/as/model/test/EAPRepositoryReachableUtil.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractSubsystemTest.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/KernelServicesBuilder.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Labels: deps-ok

#4166 [WFCORE-4930] Upgrade jboss-logmanager to 2.1.15.Final
  pom.xml
Labels: deps-ok

#4169 PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: deps-ok

#4140 [WFCORE-4913] Upgrade wildfly-discovery-client to 1.2.1.Final
  pom.xml
Labels: deps-ok

#4137 Fix for WFCORE-4912, Upgrade galleon to 4.2.5.Final
  pom.xml
Labels: deps-ok

#4176 WFCORE-4941 Optimize MMR logic within DiscardAttributeChecker.DEFAULT_VALUE
  controller/src/main/java/org/jboss/as/controller/transform/description/DiscardAttributeChecker.java
Labels: deps-ok

#4170 [WFCORE-4935] if server is already in suspend mode, don't register any listener, just shut it down.
  server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
Labels: deps-ok

#4136 [WFCORE-4909] Correct GAV versions in ModelTestControllerVersion
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
Labels: 11.x

#4162 [WFCORE-4925] Correct GAV versions in ModelTestControllerVersion
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
Labels: deps-ok

#4142 [WFCORE-4915] Tighten up the dependency tree of subsystem-test
  model-test/pom.xml
  subsystem-test/framework/pom.xml
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/bridge/impl/ObjectSerializerImpl.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java
  subsystem-test/tests/pom.xml
Labels: deps-ok

#4084 [WFCORE-4841] Fix the capabilities for the logging subsystem.
  logging/src/main/java/org/jboss/as/logging/CommonAttributes.java
  logging/src/main/java/org/jboss/as/logging/Element.java
  logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_0.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_1.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_2.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_3.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_1_5.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_3_0.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemParser_6_0.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemWriter.java
  logging/src/main/java/org/jboss/as/logging/capabilities/Capabilities.java
  logging/src/main/java/org/jboss/as/logging/capabilities/LoggingProfileCapabilityRecorder.java
  logging/src/main/java/org/jboss/as/logging/capabilities/LoggingProfileNameMapper.java
  logging/src/main/java/org/jboss/as/logging/filters/FilterReferenceRecorder.java
  logging/src/main/java/org/jboss/as/logging/filters/FilterResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/filters/Filters.java
  logging/src/main/java/org/jboss/as/logging/handlers/AbstractHandlerDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/AsyncHandlerResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlersAttributeMarshaller.java
  logging/src/main/java/org/jboss/as/logging/handlers/LogHandlerListAttributeDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/SocketHandlerResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/loggers/LoggerAttributes.java
  logging/src/main/java/org/jboss/as/logging/loggers/LoggerOperations.java
  logging/src/main/java/org/jboss/as/logging/loggers/LoggerResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/loggers/RootLoggerResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
  logging/src/test/java/org/jboss/as/logging/AbstractLoggingSubsystemTest.java
  logging/src/test/java/org/jboss/as/logging/AbstractOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/CapabilityTestCase.java
  logging/src/test/java/org/jboss/as/logging/FilterOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/HandlerLegacyOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggerLegacyOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggerOperationsTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingOperationsSubsystemTestCase.java
  logging/src/test/java/org/jboss/as/logging/LoggingSubsystemRollbackTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/capabilities/CapabilityTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/capabilities/FilterCapabilityTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/capabilities/HandlerCapabilityTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/capabilities/LoggerCapabilityTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/capabilities/TestFilter.java
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/ModuleBuilder.java
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/TestModule.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Parameter.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ParameterDescription.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ParameterDescriptions.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Parameters.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildflyTestRunner.java
Labels: deps-ok

#4174 [WFCORE-4940] Upgrade JBoss DMR 1.5.1.Final
  pom.xml
Labels: deps-ok

#4178 [WFCORE-4943] Remove duplicate dependency to controller-client in wildfly-elytron-integration
  elytron/pom.xml
Labels: deps-ok

#4175 [WFCORE-4901] TCCL not set to application classloader when MBean Noti…
  jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java
  jmx/src/test/java/org/jboss/as/jmx/PluggableMBeanServerTestCase.java
Labels: deps-ok

#4167 [WFCORE-4922] Fix possible hang starting the embedded host and server
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcessImpl.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
Labels: deps-ok

#4133 [WFCORE-4906] Exclude commons-codec dep from httpclient.
  pom.xml
Labels: deps-ok, ready-for-merge

#4173 [WFCORE-4932] Reading of identity from security domain causes NPE
  elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronRuntimeOnlyHandler.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SecurityDomainTest.java
Labels: deps-ok

#4105 WFCORE-4882 correct minOccurts value for host element in XSD
  server/src/main/resources/schema/wildfly-config_13_0.xsd
Labels: deps-ok

#4130 [WFCORE-4911] Remove org.apache.xml-resolver (it has been moved to WildFly)
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-feature-pack/src/main/resources/modules/system/layers/base/org/apache/xml-resolver/main/module.xml
  core-galleon-pack/pom.xml
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: deps-changed, hold

#4180 Revert "[WFCORE-4905] Provide common capability for Remoting connectors."
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorResource.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorResource.java
Labels: 11.x, Blocker, deps-changed

#4171 [WFCORE-4934] Upgrade Undertow to 2.1.0.Final
  pom.xml
Labels: deps-ok

#4163 WFCORE-4924: add plain-text option to security command
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/SecurityCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/AbstractEnableAuthenticationCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/auth/OptionActivators.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/PropertiesRealmConfiguration.java
  cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/security/auth/command_resources.properties
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Labels: deps-ok, ready-for-merge

#4168 [WFCORE-4934] Upgrade Undertow to 2.1.0.Final
  pom.xml
Labels: 11.x, deps-ok

#4186 [11.0.x] [WFCORE-4946] / [WFCORE-4947] Elytron Component Upgrades
  pom.xml
Labels: 11.x, deps-ok

#4185 [WFCORE-4946] / [WFCORE-4947] Elytron Component Upgrades
  pom.xml
Labels: deps-ok
