Repository wildfly/wildfly-core, pull requests merged in 2020-01, with the labels that each got.

#4045 [WFCORE-4783] Upgrade WildFly Elytron to 1.11.0.CR4
  pom.xml
Labels: deps-ok

#4044 [WFCORE-4777] Upgrade JBoss Remoting to 5.0.17.Final
  pom.xml
Labels: deps-ok

#4047 Upgrade Undertow to 2.0.29.Final
  pom.xml
Labels: deps-ok

#4040 [WFCORE-4700] Adding MicroProfile JWT
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainProcessor.java
  pom.xml
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainMarkerUtility.java
Labels: deps-ok

#4046 [WFCORE-4782] HttpManagementConstantHeadersTestCase doesn't do assertions on headerList.contains
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpManagementConstantHeadersTestCase.java
Labels: deps-ok

#4048 [WFCORE-4779] Upgrade Woodstox to 6.0.3
  pom.xml
Labels: deps-changed

#4049 [WFCORE-4786] Upgrade jandex 2.1.2.Final
  pom.xml
Labels: deps-ok

#4051 [WFCORE-4790] Refactoring DeploymentScannerService to use undeprecated MSC API
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerService.java
Labels: deps-ok

#4052 [WFCORE-4793] / [WFCORE-4794] WildFly Elytron Component Upgrades
  pom.xml
Labels: deps-ok

#3815 [WFCORE-4172] Add support for TLS 1.3
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ServerSSLContext.java
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser9_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TlsParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_9_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-9.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/legacy-elytron-subsystem-8.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls.xml
  pom.xml
Labels: 11.x, Feature, deps-ok

#4053 [WFCORE-4697] / [WFCORE-4796] WildFly Elytron Component Upgrades
  pom.xml
Labels: deps-ok

#4002 [WFCORE-2147] Enable property replacements for permissions and jboss-permissions files
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/module/ExpressionStreamReaderDelegate.java
Labels: Feature, deps-ok, ready-for-merge

#4050 [WFCORE-4788] Upgrade httpclient 4.5.10
  pom.xml
Labels: deps-ok, hold

#4056 [WFLY-11566] Add EJB hibernate validator phase
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#4055 Fix for WFCORE-4797, Upgrade galleon to 4.2.3
  pom.xml
Labels: deps-ok

#4057 [WFCORE-4798] Add necessary module dependencies to elytron-private mo…
  core-feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
Labels: deps-ok

#4054 Additional boot ops
  cli/pom.xml
  cli/src/main/java/org/jboss/as/cli/impl/BootScriptInvoker.java
  cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/_private/BootScriptInvokerLogger.java
  cli/src/main/resources/META-INF/services/org.jboss.as.controller.client.impl.AdditionalBootCliScriptInvoker
  cli/src/test/java/org/jboss/as/cli/impl/BootScriptInvokerTestCase.java
  controller-client/src/main/java/org/jboss/as/controller/client/impl/AdditionalBootCliScriptInvoker.java
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ControlledProcessState.java
  controller/src/main/java/org/jboss/as/controller/TemporaryModuleLayer.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/test/java/org/jboss/as/controller/TestModelControllerService.java
  controller/src/test/java/org/jboss/as/controller/boot/cli/hook/BootCliHookTestCase.java
  controller/src/test/java/org/jboss/as/controller/boot/cli/hook/BootCliReloadHandler.java
  controller/src/test/java/org/jboss/as/controller/boot/cli/hook/BootCliShutdownHandler.java
  controller/src/test/java/org/jboss/as/controller/boot/cli/hook/ForceRestartRequiredHandler.java
  controller/src/test/java/org/jboss/as/controller/boot/cli/hook/TestAdditionalBootCliScriptInvoker.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
  core-feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
  server/src/main/java/org/jboss/as/server/ServerService.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/cli/boot/ops/CliBootOperationsTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/cli/boot/ops/test.cli
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AppendTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BatchFileTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BatchTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BatchWithHeadersTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliSpecialCharactersTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ifelse/BasicIfElseTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ifelse/BatchesInIfElseTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ifelse/NonExistingPathComparisonTestCase.java
Labels: Feature, deps-ok

#4062 [WFCORE-4736] Vault system property security attribute value is revealed on CLI 'reload' command
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
  server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTest.java
Labels: deps-ok

#4065 [WFCORE-4810] Upgrade WildFly Elytron to 1.11.1.Final
  pom.xml
Labels: deps-ok

#4063 [WFCORE-4791] Fix HttpManagementConstantHeadersTestCase - ensure that tests do proper environment clean up
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
Labels: deps-ok, ready-for-merge

#4059 [WFCORE-4802] Upgrade httpcomponents httpclient to 4.5.11 and httpcore to 4.4.13.
  pom.xml
Labels: deps-ok

#4070 [WFCORE-4818] Upgrade WildFly Elytron to 1.11.2.Final
  pom.xml
Labels: deps-ok

#4064 [WFCORE-4809] Do not acquire the Dc write lock for composite operations targeting to a single host
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/OperationCoordinatorStepHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CompositeOperationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/SlowServiceActivator.java
Labels: deps-ok

#4076 [WFCORE-4829] Ensure the pattern-formatter is always marshalled to th…
  logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
Labels: deps-ok

#4075 [WFCORE-4820] Get the CallbackHandlerService before checking it's type.
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
Labels: deps-ok
