Repository wildfly/wildfly-core, pull requests merged in 2020-05, with the labels that each got.

#4190 Restore WFCORE-4653
  pom.xml
Labels: deps-ok, hold

#4194 [WFCORE-4958] Create the ModelTestModelControllerService variants for the EAP 7.3.0 controllers
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
Labels: deps-ok

#4189 [WFCORE-4953] Upgrade WildFly Elytron to 1.12.0.CR1
  pom.xml
Labels: deps-ok

#4192 WFCORE-4957 Reduce heap footprint of single attribute write-attribute handlers
  controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java
  controller/src/main/java/org/jboss/as/controller/ModelOnlyWriteAttributeHandler.java
Labels: deps-ok

#4195 [WFCORE-4954] Add legacy controller for EAP 7.3
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  pom.xml
Labels: deps-ok

#4193 [WFCORE-4252]: JmxControlledStateNotificationsTestCase test cases fail with security manager on Java 11.
  testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
Labels: deps-ok

#4188 WFCORE-4949 Expose the original task in RequestController.QueuedTask
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/ControlPointTask.java
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
Labels: deps-ok

#4196 [WFCORE-4965] Error loading a PKCS12 keystore inside a security-realm when using a credential-reference
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmAddHandler.java
  testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfacePKCS12TestCase.java
  testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/CoreUtils.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/config/realm/RealmKeystore.java
Labels: deps-ok, ready-for-merge

#4024 [WFCORE-4725] Add the ability to make use of the IP address of a remote client when making authorization decisions
  elytron/src/main/java/org/wildfly/extension/elytron/DomainDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/DomainService.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser10_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser8_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/RoleDecoderDefinitions.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_10_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/DomainTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/MappersTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/domain-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-10.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/users-roles.properties
  testsuite/elytron/configure-elytron.cli
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AuthenticationWithSourceAddressRoleDecoderMatchTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AuthenticationWithSourceAddressRoleDecoderMismatchTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AggregateRoleDecoder.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimplePermissionMapper.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleSecurityDomain.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SourceAddressRoleDecoder.java
Labels: Feature, deps-ok

#4200 [WFCORE-4968] Upgrade to WildFly Elytron 1.12.0.CR2
  pom.xml
Labels: deps-ok

#4202 [WFCORE-4942] Upgrade Undertow to 2.1.1.Final
  pom.xml
Labels: deps-ok

#4204 [WFCORE-4969] Upgrade XNIO to 3.8.1.Final
  pom.xml
Labels: deps-ok

#4201 [WFCORE-4966] / [WFCORE-4730] Upgrade WildFly OpenSSL to 1.1.0.Final and include the linux-s390x binding
  core-feature-pack/feature-pack-build.xml
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-galleon-pack/pom.xml
  core-galleon-pack/src/main/resources/packages/org.wildfly.openssl/pm/wildfly/tasks.xml
  pom.xml
Labels: deps-changed

#4205 [WFCORE-4971] Upgrade WildFly Elytron to 1.12.0.CR3
  pom.xml
Labels: deps-ok

#4017 [WFCORE-4750] Using regex for role in Elytron
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/RegexAttributeDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_10_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/RoleMappersTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/compare-mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/groups.properties
  elytron/src/test/resources/org/wildfly/extension/elytron/mappers.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/role-mappers-test.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/users-clear.properties
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/RegexRoleMapperTest.java
Labels: Feature

#4214 [WFCORE-4976] Ensure the supplied CallbackHandler is used for the username, password, and realm.
  protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/ElytronModelControllerClientTestCase.java
Labels: deps-ok, ready-for-merge

#4212 [WFCORE-4974] Bump the org.wildfly.core.testrunner.Server start/stop …
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Labels: deps-ok, ready-for-merge

#4216 Fix for WFCORE-4983, Fix bootable jar failing tests
  testsuite/elytron/configure-elytron-bootable.cli
  testsuite/elytron/configure-elytron.cli
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
Labels: deps-ok

#4215 [WFCORE-4982] Convert DeploymentUnitPhaseService to use a for loop instead of a stream to capture known subsystem names.
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
Labels: deps-ok

#4210 [WFCORE-4937] Upgrade FasterXML Jackson to 2.10.4
  pom.xml
Labels: deps-ok

#4213 [WFCORE-4955] Create a wildfly-network OutboundConnection interface f…
  network/src/main/java/org/jboss/as/network/OutboundConnection.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractOutboundConnectionResourceDefinition.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/AbstractOutboundConnectionService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionResourceDefinition.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionWriteHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionResourceDefinition.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionWriteHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionWriteHandler.java
Labels: deps-ok

#4218 [WFCORE-4986] Upgrade WildFly Elytron to 1.12.0.Final
  pom.xml
Labels: Blocker, deps-ok
