Repository wildfly/wildfly-core, pull requests merged in 2020-10, with the labels that each got.

#4345 [WFCORE-5143]: Bouncycastle - Failing tests in RESTEasy TS.
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml
Labels: deps-ok, ready-for-merge

#4340 Fix for WFCORE-5139, Upgrade Bootable JAR Maven plugin to 2.0.0.Beta8
  pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
Labels: 13.x, deps-ok

#4346 [WFCORE-5144] Improve the IO worker max-pool-size description
  io/subsystem/src/main/resources/org/wildfly/extension/io/LocalDescriptions.properties
Labels: deps-ok

#4348 [WFCORE-4808]: Upgrade JGit to 5.9.0.202009080501-r
  pom.xml
  testsuite/manualmode/pom.xml
Labels: deps-ok

#4344 [WFCORE-5114] Use the file name and append constructor for file handl…
  logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
  logging/src/main/java/org/jboss/as/logging/handlers/AbstractFileHandlerDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/AbstractHandlerDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/SocketHandlerResourceDefinition.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/handlers/SocketHandlerTestCase.java
Labels: deps-ok

#4337 read-resource operation does not resolve expressions recursively code…
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java
  controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsTestCase.java
Labels: deps-ok

#4322 [WFCORE-5121] Add ability to ignore excluded extensions to FetchMissi…
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/FetchMissingConfigurationHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostInfo.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/MasterDomainControllerOperationHandlerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/SlaveChannelAttachments.java
Labels: deps-ok

#4347 WFCORE-5113: fix and ensure default formatter is removed
  logging/src/main/java/org/jboss/as/logging/formatters/PatternFormatterResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/test/java/org/jboss/as/logging/HandlerOperationsTestCase.java
Labels: deps-ok

#4354 [WFCORE-5153] Upgrade Undertow to 2.2.2.Final
  pom.xml
Labels: 13.x, Blocker, deps-ok

#4355 [WFCORE-5152] Upgrade WildFly Elytron to 1.13.1.Final
  pom.xml
Labels: deps-ok

#4357 [WFCORE-5155] Ensure that the LogContextConfiguration.prepare() is in…
  logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
  logging/src/main/java/org/jboss/as/logging/handlers/SocketHandlerResourceDefinition.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/handlers/SocketHandlerTestCase.java
Labels: deps-ok

#4367 [WFCORE-5155] Ensure that the LogContextConfiguration.prepare() is in…
  logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
  logging/src/main/java/org/jboss/as/logging/handlers/SocketHandlerResourceDefinition.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/handlers/SocketHandlerTestCase.java
Labels: 13.x

#4358 [WFCORE-5156] Upgrade JUnit to 4.13.1.
  pom.xml
Labels: deps-ok

#4361 [WFCORE-5158] Upgrade Apache HTTP Client to 4.5.13
  pom.xml
Labels: deps-ok

#4368 [WFCORE-5158] Upgrade Apache HTTP Client to 4.5.13
  pom.xml
Labels: 13.x, deps-ok

#4370 [WFCORE-5163] Don't reject EE 9 permissions.xml files
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
Labels: deps-ok

#4362 [WFCORE-5159] Upgrade PicketBox from 5.0.3.Final-redhat-00006 to 5.0.3.Final-redhat-00007
  pom.xml
Labels: deps-ok

#4363 [WFCORE-5161] Upgrade slf4j-jboss-logmanager to 1.1.0.Final
  pom.xml
Labels: deps-ok

#4351 WFCORE-5150 PolicyDefinitions#registerHandler uses double-check of the same thing
  elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
Labels: deps-ok, ready-for-merge

#4365 [WFCORE-5141] upgraded JBoss Marshalling to 2.0.10.Final
  pom.xml
Labels: deps-ok

#4350 [WFCORE-5148] Upgrade Bouncy Castle to 1.66
  pom.xml
Labels: 14.x, deps-ok

#4360 [WFCORE-5157] Upgrade Jackson to 2.11.3
  pom.xml
Labels: deps-ok

#4372 Fix for WFCORE-5165, Upgrade Bootable JAR Maven plugin to 2.0.1.Final
  pom.xml
Labels: deps-ok

#4374 [WFCORE-5168] Remove wildfly-core-feature-pack-common and wildfly-core-feature-pack-ee-8-api from licenses
  core-feature-pack/galleon-feature-pack/pom.xml
  core-feature-pack/legacy-feature-pack/pom.xml
Labels: deps-ok

#4379 [WFCORE-5174] Make the date comparisons more robust to handle differences caused by daylight saving.
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
Labels: deps-ok

#4380 [WFCORE-5174] Make the date comparisons more robust to handle differences caused by daylight saving.
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
Labels: deps-ok

#4375 [WFCORE-5167] Use individual ApacheDS dependencies to avoid beinging in additional shaded content.
  elytron/pom.xml
Labels: deps-ok

#4376 [WFCORE-5167] Use individual ApacheDS dependencies to avoid beinging in additional shaded content.
  elytron/pom.xml
Labels: deps-ok
