Repository wildfly/wildfly-core, pull requests merged in 2020-02, with the labels that each got.

#4074 Fix for WFCORE-4823, Upgrade to Galleon 4.2.4
  pom.xml
Labels: 11.x, deps-ok

#4079 Fix for WFCORE-4831, CLI boot, exception not thrown when error printed to error file
  cli/src/main/java/org/jboss/as/cli/impl/BootScriptInvoker.java
  cli/src/main/java/org/jboss/as/cli/impl/_private/BootScriptInvokerLogger.java
  cli/src/test/java/org/jboss/as/cli/impl/BootScriptInvokerTestCase.java
Labels: deps-ok

#4078 [WFCORE-4830] Do not acquire the write lock when starting servers to …
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/StartServersHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SlaveRegistrationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnHttpTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/respawn/RespawnTestCase.java
  testsuite/domain/src/test/resources/byteman-scripts/DelayServerRegistration.btm
Labels: deps-ok

#4083 Fix for WFCORE-4844, CommandLineArgumentUsage custom usage
  process-controller/src/main/java/org/jboss/as/process/CommandLineArgumentUsage.java
Labels: deps-ok

#4081 [WFCORE-4838] Upgrade slf4j-jboss-logmanager from 1.0.3.GA to 1.0.4.GA
  pom.xml
Labels: deps-ok, ready-for-merge

#4086 Fix for WFCORE-4854, Layers for application and management realms
  core-galleon-pack/src/main/resources/feature_groups/application-security-realm.xml
  core-galleon-pack/src/main/resources/feature_groups/base-security-realms.xml
  core-galleon-pack/src/main/resources/feature_groups/management-security-realm.xml
  core-galleon-pack/src/main/resources/feature_groups/standalone-application-security-realm.xml
  core-galleon-pack/src/main/resources/feature_groups/standalone-management-security-realm.xml
  core-galleon-pack/src/main/resources/feature_groups/standalone-security-realms.xml
  core-galleon-pack/src/main/resources/layers/standalone/application-security-realm/layer-spec.xml
  core-galleon-pack/src/main/resources/layers/standalone/core-security-realms/layer-spec.xml
  core-galleon-pack/src/main/resources/layers/standalone/management-security-realm/layer-spec.xml
  testsuite/layers/pom.xml
Labels: deps-ok
