Repository wildfly/wildfly-core, pull requests merged in 2020-08, with the labels that each got.

#4284 [WFCORE-4985] Upgrade jboss-invocation from 1.5.3.Final to 1.6.0.Final
  pom.xml
Labels: deps-ok

#4273 [WFCORE-5057] Upgrade jboss-threads to 2.4.0.Final
  pom.xml
Labels: deps-ok

#4247 [WFCORE-5023] A few tests don't work using IBM JDK because of mock-server 5.9.0
  elytron/pom.xml
  pom.xml
  testsuite/standalone/pom.xml
Labels: deps-ok

#4285 Add workflow action for closing stale PRs
  .github/workflows/stale.yml
Labels: deps-ok

#4290 [WFCORE-5073] ConsoleMode should not return true from hasConsole if t…
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleMode.java
Labels: deps-ok

#4289 [WFCORE-5074] Upgrade JBoss Modules to 1.10.2.Final
  pom.xml
Labels: deps-ok

#4006 [WFCORE-4484] Support SSH Authentication for git persistence
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/sshd/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/jgit/main/module.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/jboss/as/server/controller/git/ElytronClientSshdSessionFactory.java
  server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteHttpGitRepositoryTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java
  testsuite/manualmode/src/test/resources/git-persistence/.ssh/README.txt
  testsuite/manualmode/src/test/resources/git-persistence/.ssh/id_ecdsa
  testsuite/manualmode/src/test/resources/git-persistence/.ssh/id_ecdsa.pub
  testsuite/manualmode/src/test/resources/git-persistence/.ssh/id_ecdsa_pkcs.pub
  testsuite/manualmode/src/test/resources/git-persistence/.ssh/id_rsa.pub
  testsuite/manualmode/src/test/resources/git-persistence/wildfly-config.xml
Labels: Feature, deps-ok, ready-for-merge

#4298 [WFCORE-5075] Upgrade WildFly OpenSSL to 1.1.2.Final
  pom.xml
Labels: deps-ok, ready-for-merge

#4293 [WFCORE-4956] Move retrieving and setting the TCCL from the public AP…
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcess.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/SecurityActions.java
Labels: deps-ok

#4300 [WFLY-10879] Adding new EE deployment phase constant
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#4294 [WFCORE-5086] Embedded mode sets jboss.server.content.dir incorrectly
  embedded/src/main/java/org/wildfly/core/embedded/HostControllerSystemPropertyContext.java
  embedded/src/main/java/org/wildfly/core/embedded/StandaloneSystemPropertyContext.java
  embedded/src/main/java/org/wildfly/core/embedded/SystemPropertyContext.java
  embedded/src/test/java/org/wildfly/core/embedded/StandaloneSystemPropertyContextTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
Labels: deps-ok

#4291 [WFCORE-5076] The "remoting-http-upgrade-service" should be ACTIVE.
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/remoting/layer-spec.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/layers/standalone/legacy-remoting/layer-spec.xml
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
  testsuite/layers/pom.xml
Labels: deps-ok

#4295 [WFCORE-5079] Refactoring of "management" layers.
  core-feature-pack/galleon-common/src/main/resources/feature_groups/unsecured-management.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/core-server/layer-spec.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/core-tools/layer-spec.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/elytron/layer-spec.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/jmx-remoting/layer-spec.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/management/layer-spec.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/secure-management/layer-spec.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/configs/standalone/standalone.xml/config.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/layers/standalone/legacy-management/layer-spec.xml
  testsuite/layers/pom.xml
  testsuite/patching/pom.xml
Labels: deps-ok

#4304 [WFCORE-5090] Upgrade WildFly Elytron to 1.13.0.CR4
  pom.xml
Labels: deps-ok, ready-for-merge

#4302 [WFCORE-5089] FailedOperationTransformationConfig: correct all attrib…
  model-test/src/main/java/org/jboss/as/model/test/FailedOperationTransformationConfig.java
Labels: deps-ok, ready-for-merge

#4301 [WFCORE-5087] Add support for the -secmgr command line argument,
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/BootablePolicy.java
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Labels: deps-ok, ready-for-merge

#4303 [WFCORE-5088] Add validation for the credential-reference attribute
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
  elytron/src/test/java/org/wildfly/extension/elytron/CredentialStoreUpdatesTestCase.java
Labels: deps-ok

#4082 [WFCORE-4486] Support for multiple security realms - Failover
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/FailoverRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_11_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-11.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
Labels: Feature, deps-ok

#4307 [WFCORE-5100] Add missing distribution repo in core-feature-pack-common-licenses.xml license file
  core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
Labels: deps-ok, ready-for-merge
