Repository wildfly/wildfly-core, pull requests merged in 2020-07, with the labels that each got.

#4254 [WFCORE-5011] Remove wildfly-jar-boot license
  core-feature-pack/pom.xml
  core-feature-pack/src/license/core-feature-pack-licenses.xml
  core-galleon-pack/pom.xml
Labels: 12.x

#4253 [12.0.x] [WFCORE-5028] Don't make the CallbackHandler provided by the CLI preferred as it is only intended as a fallback if authentication can not be performed using the available configuration.
  cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
  protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionConfiguration.java
  protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/DefaultSaslConfigTestCase.java
Labels: 12.x, hold

#4252 [WFCORE-5028] Don't make the CallbackHandler provided by the CLI preferred as it is only intended as a fallback if authentication can not be performed using the available configuration.
  cli/src/main/java/org/jboss/as/cli/impl/CLIModelControllerClient.java
  protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionConfiguration.java
  protocol/src/main/java/org/jboss/as/protocol/ProtocolConnectionUtils.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/BasicOpsTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/DefaultSaslConfigTestCase.java
Labels: deps-ok

#4257 [WFCORE-5034] Upgrade log4j to 2.13.3
  testsuite/embedded/pom.xml
Labels: deps-ok

#4238 [WFCORE-5012] Upgrade Jboss Threads to 2.3.6
  pom.xml
Labels: deps-ok

#4255 [WFCORE-5030] Add API compatibility with embedded servers that dos no…
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcess.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcessImpl.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
Labels: deps-ok, ready-for-merge

#4246 [WCORE-5014] Remove the PropertySorter and specially handle the file parameter.
  logging/src/main/java/org/jboss/as/logging/LoggingOperations.java
  logging/src/main/java/org/jboss/as/logging/handlers/AbstractFileHandlerDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/AbstractHandlerDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/logmanager/PropertySorter.java
  pom.xml
Labels: deps-ok, ready-for-merge

#4258 [WFCORE-5015] Create 'core-specific' variants of Galleon feature grou…
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-host-excludes.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-interfaces.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-profile.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-host-master.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-host-slave.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-host.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-standalone-profile.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.docs.licenses.merge/package.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.docs.licenses.merge/pm/wildfly/merger.xsl
  core-feature-pack/galleon-common/src/main/resources/packages/core.docs.licenses.merge/pm/wildfly/tasks.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.misc.common/package.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.misc.common/pm/wildfly/tasks.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.misc.domain/package.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.misc.domain/pm/wildfly/tasks.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.misc.standalone/package.xml
  core-feature-pack/galleon-common/src/main/resources/packages/core.misc.standalone/pm/wildfly/tasks.xml
  core-feature-pack/galleon-common/src/main/resources/packages/docs.licenses.merge/package.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/domain-host-excludes.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/domain-interfaces.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/domain-profile.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/domain.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/host-master.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/host-slave.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/host.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/standalone-profile.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/docs.licenses.merge/package.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/misc.common/package.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/misc.domain/package.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/misc.standalone/package.xml
Labels: deps-ok, ready-for-merge

#4095 [WFCORE-4873]: Upgrade JGit to 5.7.0.202003090808-r
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/com/jcraft/jsch/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/com/jcraft/jzlib/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcprov/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/jgit/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/base-server/layer-spec.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/git-history/layer-spec.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
  server/src/main/java/org/jboss/as/server/controller/git/GitRepositoryConfiguration.java
  server/src/test/java/org/jboss/as/controller/persistence/GitPersistenceResourceTestCase.java
  server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/AbstractGitRepositoryTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteGitRepositoryTestCase.java
Labels: deps-ok, ready-for-merge

#4261 WFCORE-4817, WFCORE-5043, WFCORE-5045, WFCORE-5046 Test fixes
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
Labels: deps-ok, ready-for-merge

#4264 [WFCORE-5048] Tests HTTPSManagementInterfaceTestCase/HTTPSManagementInterfacePKCS12TestCase fail with -Delytron
  testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/HTTPSManagementInterfaceTestCase.java
Labels: deps-ok, ready-for-merge

#4268 Fix for WFCORE-5054, Allow to load bootable JAR provider during boot
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/RuntimeExtension.java
Labels: deps-ok

#4211 [WFCORE-4973] Increasing LongOutputTestCase timeout from 10 to 20 seconds
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/LongOutputTestCase.java
Labels: deps-ok, ready-for-merge

#3185 [WFCORE-3682] try to add other stage failure description in a RollbackHandler from context attachment.
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
  controller/src/test/java/org/jboss/as/controller/test/ReadResourceWithRuntimeResourceTestCase.java
Labels: deps-ok, ready-for-merge

#4114 [WFCORE-4485] Support for multiple security realms - Distributed Identities
  elytron/src/main/java/org/wildfly/extension/elytron/DistributedRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser11_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_11_0.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-11.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
Labels: Feature, ready-for-merge

#4233 [WFCORE-5007] Make use of the SocketAddressCallbackServerMechanismFactory to set the peer address during HTTP authentication
  domain-management/src/main/java/org/jboss/as/domain/management/security/SecurityRealmService.java
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/AuthenticationWithSourceAddressRoleDecoderMatchTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/mgmt/elytron/AuthenticationWithSourceAddressRoleDecoderMismatchTestCase.java
Labels: ready-for-merge

#4259 WFCORE-5029 Add propery read handler for MANAGED attirbute at server …
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainDeploymentResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/DeploymentResourceDefinition.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/ServerGroupDeploymentManagedAttributeTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java
Labels: deps-ok, ready-for-merge

#4275 Fix for WFCORE-5059, Upgrade bootable testsuite to use 2.0.0.Alpha6 maven plugin
  pom.xml
  testsuite/elytron/pom.xml
  testsuite/rbac/pom.xml
Labels: deps-ok

#4272 [WFCORE-5050] Upgrade WildFly OpenSSL to 1.1.1.Final
  pom.xml
Labels: deps-ok

#4277 [WFCORE-4863] Upgrade PicketBox from 5.0.3.Final-redhat-00005 to 5.0.3.Final-redhat-00006
  pom.xml
Labels: deps-ok

#4278 [WFCORE-5063] Upgrade jboss-parent pom to 37
  pom.xml
Labels: deps-ok, ready-for-merge

#4279 [WFCORE-5062] Ensure the parent directories are created for files bef…
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
Labels: deps-ok

#4249 [WFCORE-5024] RESTEasy integration with WildFly Elytron - Authenticat…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
Labels: Feature, deps-ok, ready-for-merge

#4276 [WFCORE-4962] / [WFCORE-4963] / [WFCORE-4981] DUP Refactoring to share service name of resolved SecurityDomain.
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/SecurityMetaDataProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainNameProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
  server/src/main/java/org/jboss/as/server/security/SecurityMetaData.java
Labels: deps-ok, ready-for-merge

#4280 [WFCORE-5064] Incorrect use of KeyManagerFactory.getDefaultAlgorithm instead of TrustManagerFactory
  domain-management/src/main/java/org/jboss/as/domain/management/security/FileTrustManagerService.java
Labels: deps-ok, ready-for-merge

#4260 WFCORE-5037 - Handle maps of complex objects in JMX Facade
  jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
  jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanHelper.java
  jmx/src/main/java/org/jboss/as/jmx/model/ModelControllerMBeanServerPlugin.java
  jmx/src/main/java/org/jboss/as/jmx/model/TypeConverters.java
  jmx/src/test/java/org/jboss/as/jmx/ComplexRuntimeAttributesExtension.java
  jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
  jmx/src/test/java/org/jboss/as/jmx/model/ExpressionTypeConverterUnitTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/model/LegacyTypeConverterUnitTestCase.java
Labels: deps-ok

#4281 [WFCORE-5065] Add an optionally implemented, ServiceLoader loadable i…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentAddHandler.java
  server/src/main/java/org/jboss/as/server/deployment/transformation/DeploymentTransformer.java
Labels: deps-ok

#4286 [WFCORE-5071] Extra spaces in DeploymentTransformer.java produces error at build
  server/src/main/java/org/jboss/as/server/deployment/transformation/DeploymentTransformer.java
Labels: deps-ok

#4288 [WFCORE-5072] Exclude export of the jakarta.* packages from the org.g…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/glassfish/jakarta/json/main/module.xml
Labels: deps-ok
