Repository wildfly/wildfly-core, pull requests merged in 2021-02, with the labels that each got.

#4469 [WFCORE-5266] Upgrade WildFly OpenSSL to 2.1.3.Final
  pom.xml
Labels: deps-ok

#4465 [WFCORE-5248 - WFCORE-5259] Upgrade jboss-logmanager to 2.1.18.Final.…
  pom.xml
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/AbstractLoggingTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/AbstractCustomModuleTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/CustomModuleFilterTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/CustomModuleFormatterTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/CustomModuleHandlerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/CustomModuleTestSuite.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/LoggingDeploymentServiceActivator.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/TestEnvironment.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/api/PropertyResolver.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/api/PropertyResolverFactory.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/api/Reflection.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingAppender.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingFileHandler.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingFilter.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingFormatter.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/SystemPropertyResolver.java
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/ModuleBuilder.java
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/ModuleDependency.java
Labels: deps-ok

#4471 [WFCORE-5251] Upgrade Undertow to 2.2.4.Final
  pom.xml
Labels: deps-ok

#4478 [WFCORE-5282] Upgrade WildFly Elytron to 1.14.2.Final
  pom.xml
Labels: deps-ok

#4458 [WFCORE-4291] Add support for non-graceful startup
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  controller/src/main/java/org/jboss/as/controller/parsing/Attribute.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTransformersTestCase.java
  core-model-test/tests/src/test/resources/org/jboss/as/core/model/test/servergroup/servergroup.xml
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/DomainTransformers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/ServerGroupTransformers.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServer.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootConfiguration.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_16.java
  host-controller/src/main/resources/org/jboss/as/domain/controller/resources/LocalDescriptions.properties
  process-controller/src/main/java/org/jboss/as/process/CommandLineConstants.java
  server/src/main/java/org/jboss/as/server/CommandLineArgumentUsageImpl.java
  server/src/main/java/org/jboss/as/server/Main.java
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/ServerEnvironmentResourceDescription.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/ServerStartTask.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
  server/src/main/resources/schema/wildfly-config_16_0.xsd
Labels: 15.x, Feature, deps-ok

#4481 [WFCORE-5290] / [WFCORE-5291] / [WFCORE-4584] Elytron Component Upgrades
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  core-feature-pack/pom.xml
  pom.xml
Labels: deps-changed

#4472 [WFCORE-5261] Add the ability to use a common script configuration file.
  core-feature-pack/common/src/main/resources/content/bin/add-user.bat
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.bat
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.sh
  core-feature-pack/common/src/main/resources/content/bin/jboss-cli.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/vault.bat
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptProcess.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/Shell.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
Labels: 15.x, Feature, deps-ok

#4484 [WFCORE-5292] Remove Java EE References from the i18n strings
  cli/src/main/resources/org/jboss/as/cli/impl/aesh/cmd/deployment/command_resources.properties
  domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
Labels: affects_i18n, deps-ok, ready-for-merge

#4496 [WFCORE-5288] Improve JMX subsystem tests
  jmx/src/main/java/org/jboss/as/jmx/JMXExtension.java
  jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java
  jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRootResource.java
  jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
  jmx/src/test/resources/org/jboss/as/jmx/subsystem-with-expressions.xml
Labels: deps-ok

#4460 [WFCORE-5253] Clean up remoting subsystem OSH use of 'operation'
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/ConnectorRemove.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/GenericOutboundConnectionWriteHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/HttpConnectorAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/LocalOutboundConnectionWriteHandler.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionAdd.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionWriteHandler.java
Labels: deps-ok, ready-for-merge

#4461 [WFCORE-5254] Fix domain-management module OSHs that are populating t…
  domain-management/src/main/java/org/jboss/as/domain/management/LegacyConfigurationChangeResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/audit/InMemoryAuditLogHandlerResourceDefinition.java
Labels: deps-ok, ready-for-merge

#4476 [WFCORE-5276]: Upgrade jgit to 5.10.0.202012080955-r
  pom.xml
  testsuite/manualmode/pom.xml
Labels: deps-ok, ready-for-merge

#4482 [WFCORE-5271] NullPointerException creating new KeyStore without type
  elytron/src/main/java/org/wildfly/extension/elytron/KeyStoreService.java
Labels: deps-ok, ready-for-merge

#4500 [WFCORE-5309] / [WFCORE-5310] Elytron Component Upgrades
  pom.xml
Labels: Blocker, deps-ok, ready-for-merge

#4497 [WFCORE-5297] Add a 'path' attribute to 'credential-store' and deprecate the use of 'location'.
  elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/CredentialStoreResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_13_0.xsd
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-subsystem-13.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-8.0.xml
Labels: 15.x, Critical, affects_i18n, deps-ok

#4490 [WFCORE-5300] Before generating a secret key check if the credential store already contains one under the specified alias.
  elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
Labels: 15.x, Critical, deps-ok

#4488 [WFCORE-5301] Use a descriptive error message if the secret key is not available from the credential store.
  elytron/src/main/java/org/wildfly/extension/elytron/expression/ElytronExpressionResolver.java
Labels: 15.x, Critical, deps-ok

#4494 [WFCORE-5306]: Clarifications needed for Message Translations II.
  platform-mbean/src/main/resources/org/jboss/as/platform/mbean/LocalDescriptions.properties
Labels: affects_i18n, deps-ok

#4491 [WFCORE-5303] Don't return improperly resolved expressions when manag…
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ResolveExpressionHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java
  controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/CustomVaultInModuleTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/vault/module/TestVaultSubsystemResourceDescription.java
Labels: affects_i18n, deps-ok

#4489 [WFCORE-5302] Correct the cast to avoid a ClassCastException.
  elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
Labels: 15.x, Critical, deps-ok

#4485 Fix for WFCORE-5293, Upgrade aesh-readline to 2.2
  pom.xml
Labels: deps-ok

#4464 WFCORE-5247 IllegalArgumentException and CLI crash with read-attribute in /system-property
  cli/src/main/java/org/jboss/as/cli/handlers/ReadAttributeHandler.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Labels: deps-ok
