Repository wildfly/wildfly-core, pull requests merged in 2021-08, with the labels that each got.

#4698 [WFCORE-5534] Upgrade wildfly-galleon-plugin to 5.2.2.Beta2
  pom.xml
Labels: deps-ok

#4688 [WFCORE-5520] Avoid Nullpointer (domain-http)
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/security/RealmIdentityManager.java
Labels: ready-for-merge, deps-ok

#4701 [WFCORE-5535] Upgrade JBoss Invocation to 1.6.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4696 [WFCORE-5520] Avoid Nullpointer (Server)
  server/src/main/java/org/jboss/as/server/controller/git/ElytronClientSshdSessionFactory.java
Labels: deps-ok

#4699 [WFCORE-4035] operation-requires-reload message is missing
  io/subsystem/src/main/java/org/wildfly/extension/io/WorkerResourceDefinition.java
Labels: deps-ok

#4679 [WFCORE-5521] Close Resource (Controller)
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
Labels: deps-ok

#4678 [WFCORE-5521] Close Resource (bootable-jar)
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
Labels: deps-ok

#4692 [WFCORE-5524] *ConfigurationChangesHistoryTestCase fails on Windows
  controller/src/main/java/org/jboss/as/controller/ConfigurationChangesCollector.java
Labels: deps-ok

#4704 [WFCORE-5541] Upgrade Undertow to 2.2.10.Final
  pom.xml
Labels: deps-ok

#4708 [WFCORE-5543] Operation-scoped caching of static module Jandex indices
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
  server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
  server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/AnnotationIndexSupport.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/logging/LoggingUtil.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/logging/TestLogHandlerSetupTask.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/JandexIndexCachingTestCase.java
Labels: deps-ok

#4714 Deprecate ModelTestControllerVersion-s older than EAP_7_4_0
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
Labels: deps-ok

#4702 [WFCORE-5536] list-snapshots() should include snapshot file with a cu…
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ModelPersistenceTestCase.java
Labels: deps-ok

#4713 WFCORE-5547 DistributableWebDeploymentProcessor should run before ModuleSpecProcessor
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#4715 [WFCORE-5552] Bring undertow-servlet-jakartaee9 and undertow-websocke…
  pom.xml
Labels: deps-ok

#4709 WFCORE-5502 Fix deprecated constructors
  jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
  jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
  server/src/main/java/org/jboss/as/server/ApplicationServerService.java
  threads/src/main/java/org/jboss/as/threads/ThreadFactoryWriteAttributeHandler.java
Labels: deps-ok

#4717 Fix for WFCORE-5556, Add back setAllowNull, required by Keycloak SAML…
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
Labels: deps-ok

#4711 [WFCORE-5545] Include module indices computed via class scanning in the ADDITIONAL_ANNOTATION_INDEXES attachment
  server/src/main/java/org/jboss/as/server/deployment/annotation/AnnotationIndexSupport.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
Labels: deps-ok

#4633 [WFCORE-5464] Upgrade JBoss DMR and test expressions resolved fro…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/dmr/main/module.xml
  pom.xml
  testsuite/standalone/pom.xml
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/ResolveExpressionFromEnvironmentVariableTestCase.java
Labels: Feature, missing-reqs, deps-ok

#4726 [WFCORE-5566] Fix FIPS detection so that it also works with Java 17
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
Labels: deps-ok

#4727 [WFCORE-5568]: Cleaning up deployments after running the test.
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/JandexIndexCachingTestCase.java
Labels: deps-ok

#4724 [WFCORE-5565] Upgrade SLF4J 1.7.32
  pom.xml
Labels: ready-for-merge, deps-ok

#4712 WFCORE-5546 JAVA_OPTS is not correctly set in standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
Labels: deps-ok

#4728 [WFCORE-5406] Add --add-opens to the SE 9+ VM launch for expected reflective access by the server (round 2)
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: deps-ok
