Repository wildfly/wildfly-core, pull requests merged in 2021-12, with the labels that each got.

#4866 [WFCORE-5708] Add a new "org.wildfly.security.http.sfbasic" module.
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/http/sfbasic/main/module.xml
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: ready-for-merge

#4883 [WFCORE-5731] Upgrade Elytron Web to 1.10.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4879 [WFCORE-5712] Update elytron-tool scripts to make use of jboss-modules
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.bat
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.ps1
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.sh
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/cli/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/commons/lang3/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-tool/main/module.xml
  core-feature-pack/galleon-common/src/main/resources/packages/tools/pm/wildfly/tasks.xml
  elytron-tool-wrapper/pom.xml
  elytron-tool-wrapper/src/main/java/org/wildfly/core/elytron/tool/wrapper/ElytronToolScriptWrapper.java
  elytron-tool-wrapper/src/main/java/org/wildfly/core/elytron/tool/wrapper/_private/ElytronToolWrapperMessages.java
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/common/test/ServerConfigurator.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
Labels: ready-for-merge, deps-changed

#4884 Fix for WFCORE-5726, CLI client shaded JAR doesn't aggregate services
  cli/pom.xml
Labels: ready-for-merge, deps-ok

#4885 Fix for WFCORE-5732, Missing modular options in bootable JAR manifest
  bootable-jar/boot/pom.xml
Labels: ready-for-merge, deps-ok

#4886 [WFCORE-5733] Upgrade Undertow version to 2.2.14.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4889 [WFCORE-5741] Upgrade WildFly Elytron to 1.18.1.Final
  pom.xml
Labels: deps-ok

#4888 [WFCORE-5651] Remove management identity's default security domain configuration
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/management/layer-spec.xml
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractMgmtSaslTestBase.java
Labels: deps-ok

#4890 [WFCORE-5742] Upgrade WildFly Galleon Plugin to 5.2.7.Final
  pom.xml
Labels: deps-ok

#4895 [WFCORE-5745] Upgrade JBoss VFS to 3.2.16.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4894 [WFCORE-5651] Remove management identity's default security domain configuration from testsuite
  testsuite/domain/enable-elytron.cli
  testsuite/shared/enable-elytron.cli
  testsuite/standalone/enable-elytron.cli
Labels: ready-for-merge, deps-ok

#4893 [WFCORE-5601] Update class javadoc for PluggableMBeanServerBuilder
  jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerBuilder.java
Labels: ready-for-merge, deps-ok

#4887 [WFCORE-5734] Set java.io.tmpdir for surefire
  pom.xml
  testsuite/pom.xml
Labels: ready-for-merge, deps-ok

#4898 [WFCORE-5750] Upgrade log4j to 2.16.0
  pom.xml
Labels: deps-ok

#4896 [WFCORE-5746] Bump Management API to 20.0.0
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
  version/src/main/java/org/jboss/as/version/Version.java
Labels: ready-for-merge, deps-ok

#4903 [18.x] [WFCORE-5750] Upgrade log4j to 2.16.0
  pom.xml
Labels: 18.x

#4899 Add ModelTestControllerVersion for XP 4
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  pom.xml
Labels: ready-for-merge, deps-ok

#4902 [WFCORE-5754] Upgrade log4j2-jboss-logmanager to 1.1.1.Final.
  pom.xml
Labels: ready-for-merge, deps-ok
