Repository wildfly/wildfly-core, pull requests merged in 2021-07, with the labels that each got.

#4636 [WFCORE-5467] Remove deprecated properties and methods
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/SimpleListAttributeDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
  elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/DiscoveryOptionsResourceDefinition.java
  io/subsystem/src/main/java/org/wildfly/extension/io/OptionAttributeDefinition.java
Labels: deps-ok, hold

#4609 WFCORE-5396 Remove the wildlfy-elytron-http-deprecated dependency module to no longer rely on deprecated classes
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
  pom.xml
Labels: deps-changed

#4623 [WFCORE-5450] TlsTestCase is failing on IBM JDK
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-ibm.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-sun.xml
Labels: deps-ok

#4625 [WFCORE-5457] Add missing permission for JmxControlledStateNotificationsTestCase on J9
  testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
Labels: deps-ok

#4645 [WFCORE-5495] Upgrade jboss-invocation from 1.6.0.Final to 1.6.1.Final
  pom.xml
Labels: deps-ok

#4646 [WFCORE-5496] Upgrading JBoss MSC from 1.4.12.Final to 1.4.13.Final
  pom.xml
Labels: deps-ok

#4653 [WFLY-5498] Upgrade commons-io to 2.10.0
  testbom/pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ModuleTestCase.java
Labels: deps-ok

#4642 [WFCORE-3825] Unify "-server" option usage for HostController and DomainController in domain.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.ps1
Labels: deps-ok

#4451 [WFCORE-3467] Require existence of the AttributeDefinition in AbstractWriteAttributeHandler
  controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java
  controller/src/main/java/org/jboss/as/controller/ReloadRequiredWriteAttributeHandler.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/operations/global/WriteAttributeHandler.java
  jmx/src/test/java/org/jboss/as/jmx/ModelControllerResourceDefinition.java
Labels: affects_i18n, deps-ok

#4648 [WFCORE-5480] Bouncyclastle provider module requires a dependency on …
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcprov/main/module.xml
Labels: deps-ok

#4656 [WFCORE-5503] Get rid of maven warning importing the testbom dependen…
  testsuite/standalone/pom.xml
Labels: deps-ok

#4654 [WFCORE-5482] Bouncycastle bcpkix module requires a dependency on java logging and java.naming
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpkix/main/module.xml
Labels: deps-ok

#4647 WFCORE-5353 Multiple syntax issues with 'wildfly-init-redhat.sh'
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
Labels: deps-ok

#4659 [WFCORE-5506] Make Bouncy Castle bcutil-jdk15on license to use explic…
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
Labels: deps-ok

#4664 [WFCORE-5510] Upgrade WildFly Elytron to 1.16.1.Final
  pom.xml
Labels: deps-ok

#4668 [WFCORE-5511] wildfly-core: Invalid Sensitivity Classification of Vault Expression
  controller/src/main/java/org/jboss/as/controller/access/constraint/SensitiveVaultExpressionConstraint.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/VaultExpressionSensitivityTestCase.java
Labels: deps-ok

#4669 [16.x] [WFCORE-5511] wildfly-core: Invalid Sensitivity Classification of Vault Expression
  controller/src/main/java/org/jboss/as/controller/access/constraint/SensitiveVaultExpressionConstraint.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/VaultExpressionSensitivityTestCase.java
Labels: 16.x

#4622 [WFCORE-1934] Make number of max thread size for ServerService Thread…
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ServerServiceThreadPoolTestCase.java
Labels: deps-ok

#4662 [WFCORE-5509] Upgrade to Byteman 4.0.16
  pom.xml
Labels: deps-ok

#4651 [WFCORE-5499] Fix JAVA_OPTS displaying for domain.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.ps1
Labels: deps-ok

#4657 [WFCORE-5504] Check emptiness with Collection.isEmpty() (domain-mng)
  domain-management/src/main/java/org/jboss/as/domain/management/access/RbacSanityCheckOperation.java
  domain-management/src/main/java/org/jboss/as/domain/management/parsing/AuditLogXml_5.java
  domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_4.java
  domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_5.java
  domain-management/src/main/java/org/jboss/as/domain/management/parsing/ManagementXml_Legacy.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/AuthenticationValidatingHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapAuthorizationResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapSubjectSupplementalService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/PlugInLoaderService.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/SSLServerIdentityResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/PromptPasswordState.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/StateValues.java
Labels: deps-ok

#4666 [WFCORE-5504] Check emptiness with Collection.isEmpty() (Controller)
  controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
  controller/src/main/java/org/jboss/as/controller/ExpressionResolverImpl.java
  controller/src/main/java/org/jboss/as/controller/MapAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
  controller/src/main/java/org/jboss/as/controller/PathAddress.java
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
  controller/src/main/java/org/jboss/as/controller/ValidateModelStepHandler.java
  controller/src/main/java/org/jboss/as/controller/access/management/AccessConstraintDescriptionProviderUtil.java
  controller/src/main/java/org/jboss/as/controller/audit/AuditLogHandler.java
  controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionResource.java
  controller/src/main/java/org/jboss/as/controller/interfaces/NotInterfaceCriteria.java
  controller/src/main/java/org/jboss/as/controller/interfaces/OverallInterfaceCriteria.java
  controller/src/main/java/org/jboss/as/controller/interfaces/ParsedInterfaceCriteria.java
  controller/src/main/java/org/jboss/as/controller/operations/common/OrderedChildTypesAttachment.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
  controller/src/main/java/org/jboss/as/controller/remote/BlockingQueueOperationListener.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathManagerService.java
  controller/src/main/java/org/jboss/as/controller/transform/RejectExpressionValuesTransformer.java
  controller/src/main/java/org/jboss/as/controller/transform/TransformersLogger.java
Labels: deps-ok

#4672 [WFCORE-5504] Check emptiness with Collection.isEmpty() (misc)
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/impl/DeploymentSetPlanImpl.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentPlanBuilderImpl.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/bridge/impl/ChildFirstClassLoaderKernelServicesFactory.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainUtil.java
Labels: deps-ok

#4667 [WFCORE-5504] Check emptiness with Collection.isEmpty() (CLI)
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  cli/src/main/java/org/jboss/as/cli/gui/component/StandaloneDeploymentTableModel.java
  cli/src/main/java/org/jboss/as/cli/handlers/DeploymentOverlayHandler.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/HelpSupport.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/ElytronUtil.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/InteractiveSecurityBuilder.java
Labels: deps-ok

#4671 [WFCORE-5515] Upgrade log4j-jboss-logmanager to 1.2.2.Final
  pom.xml
Labels: deps-ok

#4675 [WFCORE-5517] Upgrade Undertow to 2.2.9.Final
  pom.xml
Labels: deps-ok

#4670 [WFCORE-5513] Manage the BouncyCastle Jakarta Mail dependency with WildFly Core
  pom.xml
Labels: deps-ok

#4574 [WFCORE-2592] Special characters escaping in service.bat
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat
Labels: deps-ok, ready-for-merge

#4683 [WFCORE-5518] Upgrade JBoss Invocation to 1.6.2.Final
  pom.xml
Labels: deps-ok

#4681 [WFCORE-5520] Avoid Nullpointer (Controller)
  controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
  controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadChildrenTypesHandler.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathManagerService.java
Labels: deps-ok, ready-for-merge

#4680 [WFCORE-5521] Close Resource (CLI)
  cli/src/main/java/org/jboss/as/cli/handlers/ArchiveHandler.java
  cli/src/main/java/org/jboss/as/cli/util/SimpleTable.java
Labels: deps-ok

#4684 [WFCORE-2592] Procrun syntax characters escaping
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat
Labels: deps-ok

#4689 [WFCORE-5528] Missing EAP 7.4 host exclusion as a known release
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
Labels: deps-ok, ready-for-merge

#4691 [WFCORE-5347][WFCORE-5529] Replace WF23 ModelTestControllerVersion by 7.4.0.GA and correct it on Elytron transformer tests
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  pom.xml
Labels: deps-ok, ready-for-merge

#4674 [WFCORE-5516] If JBOSS_BASE_DIR variable is empty -Djboss.server.base.dir is not added in wildfly-init-redhat.sh and wildfly-init-debian.sh scripts.
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-debian.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
Labels: deps-ok
