Repository wildfly/wildfly-core, pull requests merged in 2021-04, with the labels that each got.

#4445 [WFCORE-5239] No suitable provider found for type 'PKCS11' on openjdk…
  elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
Labels: deps-ok, ready-for-merge

#4549 Fix for WFCORE-5365, cli-script option help text is missing a placeholder
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
Labels: deps-ok

#4545 [WFCORE-5360] Upgrade log4j2 to 2.14.1.
  pom.xml
Labels: deps-ok

#4547 Fix for WFCORE-5362, Upgrade galleon-plugins to 5.1.2
  pom.xml
Labels: deps-ok

#4548 [WFCORE-5363] Upgrade JBoss Remoting to 5.0.21.Final
  pom.xml
Labels: deps-ok

#4541 [WFCORE-5352] Updated README.md for user contributed init scripts
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/README.md
Labels: deps-ok

#4566 [WFCORE-5370] Properly associate authenticated user with current request
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
Labels: deps-ok

#4550 [WFCORE-5285] Utilize org.wildfly.common.Assert for Null-Checks (cli)
  cli/src/main/java/org/jboss/as/cli/CommandCompleter.java
  cli/src/main/java/org/jboss/as/cli/CommandRegistry.java
  cli/src/main/java/org/jboss/as/cli/RequestWithAttachments.java
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/accesscontrol/AccessRequirementBuilder.java
  cli/src/main/java/org/jboss/as/cli/accesscontrol/AccessRequirementSet.java
  cli/src/main/java/org/jboss/as/cli/accesscontrol/AddressAccessRequirement.java
  cli/src/main/java/org/jboss/as/cli/accesscontrol/BaseOperationAccessRequirement.java
  cli/src/main/java/org/jboss/as/cli/accesscontrol/ControllerModeAccess.java
  cli/src/main/java/org/jboss/as/cli/accesscontrol/PerNodeOperationAccess.java
  cli/src/main/java/org/jboss/as/cli/batch/impl/DefaultBatch.java
  cli/src/main/java/org/jboss/as/cli/batch/impl/DefaultBatchedCommand.java
  cli/src/main/java/org/jboss/as/cli/handlers/BaseOperationCommand.java
  cli/src/main/java/org/jboss/as/cli/handlers/CommandHandlerWithArguments.java
  cli/src/main/java/org/jboss/as/cli/handlers/CommandHandlerWithHelp.java
  cli/src/main/java/org/jboss/as/cli/handlers/FilenameTabCompleter.java
  cli/src/main/java/org/jboss/as/cli/handlers/GenericTypeOperationHandler.java
  cli/src/main/java/org/jboss/as/cli/handlers/ResourceCompositeOperationHandler.java
  cli/src/main/java/org/jboss/as/cli/handlers/SimpleTabCompleter.java
  cli/src/main/java/org/jboss/as/cli/handlers/ifelse/BaseOperation.java
  cli/src/main/java/org/jboss/as/cli/handlers/ifelse/IfElseControlFlow.java
  cli/src/main/java/org/jboss/as/cli/handlers/ifelse/ModelNodePathOperand.java
  cli/src/main/java/org/jboss/as/cli/handlers/ifelse/StringValueOperand.java
  cli/src/main/java/org/jboss/as/cli/handlers/loop/ForControlFlow.java
  cli/src/main/java/org/jboss/as/cli/handlers/module/ModuleConfigImpl.java
  cli/src/main/java/org/jboss/as/cli/handlers/module/ModuleDependency.java
  cli/src/main/java/org/jboss/as/cli/handlers/module/ResourceRoot.java
  cli/src/main/java/org/jboss/as/cli/impl/ArgumentWithoutValue.java
  cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandCandidatesProvider.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/DefaultCompleter.java
  cli/src/main/java/org/jboss/as/cli/impl/PermittedCandidates.java
  cli/src/main/java/org/jboss/as/cli/impl/RequestParamArgWithValue.java
  cli/src/main/java/org/jboss/as/cli/impl/ValueTypeCompleter.java
  cli/src/main/java/org/jboss/as/cli/impl/VaultConfig.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/AbstractControlledCommand.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthFactory.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/AuthSecurityBuilder.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/SSLSecurityBuilder.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/model/SecurityDomain.java
  cli/src/main/java/org/jboss/as/cli/operation/impl/ConcurrentRolloutPlanGroup.java
  cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationRequestBuilder.java
  cli/src/main/java/org/jboss/as/cli/operation/impl/ParsedRolloutPlanHeader.java
  cli/src/main/java/org/jboss/as/cli/operation/impl/SingleRolloutPlanGroup.java
  cli/src/main/java/org/jboss/as/cli/parsing/DefaultParsingState.java
  cli/src/main/java/org/jboss/as/cli/parsing/EnterStateCharacterHandler.java
  cli/src/main/java/org/jboss/as/cli/util/SimpleTable.java
  cli/src/main/java/org/jboss/as/cli/util/StrictSizeTable.java
  cli/src/test/java/org/jboss/as/cli/completion/mock/MockCommandContext.java
  cli/src/test/java/org/jboss/as/cli/completion/mock/MockOperationCandidatesProvider.java
Labels: deps-ok

#4551 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (controller)
  controller/src/main/java/org/jboss/as/controller/ModelControllerLock.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
  controller/src/main/java/org/jboss/as/controller/registry/RuntimePackageDependency.java
  controller/src/main/java/org/jboss/as/controller/security/InetAddressPrincipal.java
  controller/src/main/java/org/jboss/as/controller/services/path/AbstractPathService.java
  controller/src/test/java/org/jboss/as/controller/support/ChannelServer.java
Labels: deps-ok

#4552 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (testsuite-elytron)
  testsuite/elytron/src/test/java/org/jboss/as/test/shared/CliUtils.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AbstractConfigurableElement.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AbstractConstantHelper.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/AbstractUserRolesCapableElement.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/ConstantRealmMapper.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/ConstantRoleMapper.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/DirContext.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/IdentityMapping.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/KeyStoreRealm.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/LdapRealm.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/MechanismRealmConfiguration.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/NameValue.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/OtpCredentialMapper.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleConfigurableSaslServerFactory.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleKeyManager.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleSaslAuthenticationFactory.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/SimpleTrustManager.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/UserPasswordMapper.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/UserWithRoles.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/other/ClientMapping.java
Labels: deps-ok

#4553 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (manualmode)
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/TestEnvironment.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingAppender.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingFileHandler.java
Labels: deps-ok

#4554 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (testrunner)
  testsuite/test-runner/pom.xml
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Labels: deps-ok

#4555 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (security)
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/core-security/main/module.xml
  core-security/implementation/pom.xml
  core-security/implementation/src/main/java/org/jboss/as/core/security/AbstractRealmPrincipal.java
  core-security/implementation/src/main/java/org/jboss/as/core/security/SecurityRealmPrincipal.java
Labels: deps-ok

#4556 [WFCORE-5285] Utilize org.wildfly.common.Assert for Null-Checks (domainhttp)
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiHandler.java
Labels: deps-ok

#4557 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (network)
  network/src/main/java/org/jboss/as/network/ManagedBinding.java
  network/src/main/java/org/jboss/as/network/NetworkUtils.java
Labels: deps-ok

#4558 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (domain-management)
  domain-management/src/main/java/org/jboss/as/domain/management/security/password/simple/SimpleKeyboard.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/password/simple/SimplePasswordStrengthChecker.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/operations/CacheBuilder.java
Labels: deps-ok

#4560 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (securitymanager)
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/security/manager/main/module.xml
  security-manager/pom.xml
  security-manager/src/main/java/org/wildfly/extension/security/manager/DeferredPermissionFactory.java
Labels: deps-ok

#4563 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (process-controller)
  process-controller/src/main/java/org/jboss/as/process/stdin/BaseNCodecInputStream.java
  process-controller/src/main/java/org/jboss/as/process/stdin/BaseNCodecOutputStream.java
Labels: deps-ok

#4564 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (server)
  server/src/main/java/org/jboss/as/server/deploymentoverlay/DeploymentOverlayIndex.java
Labels: deps-ok

#4565 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (protocol)
  protocol/pom.xml
  protocol/src/test/java/org/jboss/as/protocol/mgmt/support/ChannelServer.java
Labels: deps-ok

#4561 [WFCORE-5334]: Deleting Configuration Data when Git connection is failed.
  server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/RemoteSshGitRepositoryTestCase.java
Labels: deps-ok

#4569 [WFCORE-5373] Fix missing resource handling
  domain-management/src/main/java/org/jboss/as/domain/management/access/RoleMappingRemove.java
Labels: deps-ok

#4567 [WFCORE-5285] Utilize o.w.common.Assert for Null-Checks (misc)
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/LegacyModelInitializerEntry.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  model-test/src/main/java/org/jboss/as/model/test/MavenUtil.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
  patching/src/main/java/org/jboss/as/patching/management/PatchResource.java
  patching/src/main/java/org/jboss/as/patching/tool/PatchOperationTarget.java
  patching/src/main/java/org/jboss/as/patching/tool/PatchingHistory.java
  patching/src/main/java/org/jboss/as/patching/validation/BasicArtifactProcessor.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/ControllerInitializer.java
  testsuite/shared/src/main/java/org/jboss/as/test/deployment/DeploymentInfoUtils.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ManagementClient.java
Labels: deps-ok

#4479 [WFCORE-5286] Remove deprecated javax.api usage from modules
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/httpcomponents/core/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/eclipse/jgit/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml
Labels: deps-ok

#4568 [WFCORE-5372] Use absolute path in permissions.xml in JMX test
  testsuite/shared/src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java
Labels: deps-ok

#4562 WFCORE-4162 Incorrect OperationContext.getCapabilityServiceName javadoc
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
Labels: deps-ok, ready-for-merge

#4528 WFCORE-5263 Update all projects with a dependency on wildfly-elytron to use individual modules
  cli/pom.xml
  controller-client/pom.xml
  controller/pom.xml
  core-feature-pack/common/pom.xml
  core-management/core-management-subsystem/pom.xml
  core-model-test/tests/pom.xml
  domain-http/interface/pom.xml
  domain-management/pom.xml
  elytron/pom.xml
  host-controller/pom.xml
  jmx/pom.xml
  logging/pom.xml
  network/pom.xml
  patching/pom.xml
  platform-mbean/pom.xml
  pom.xml
  process-controller/pom.xml
  protocol/pom.xml
  remoting/subsystem/pom.xml
  security-manager/pom.xml
  server/pom.xml
  subsystem-test/framework/pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/patching/pom.xml
  testsuite/pom.xml
  testsuite/shared/pom.xml
  testsuite/standalone/pom.xml
  testsuite/test-runner/pom.xml
Labels: 16.x, deps-changed, ready-for-merge

#4474 [WFCORE-5185] Update ProviderDefinition to use optimised service loading API
  elytron/src/main/java/org/wildfly/extension/elytron/ProviderDefinitions.java
Labels: deps-ok
