Repository wildfly/wildfly-core, pull requests merged in 2021-05, with the labels that each got.

#4533 [WFCORE-2925] Heap settings separation in standalone and domain conf scripts
  core-feature-pack/common/src/main/resources/content/bin/domain.conf
  core-feature-pack/common/src/main/resources/content/bin/domain.conf.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
Labels: deps-ok, ready-for-merge

#4579 Fix for WFCORE-5384, RemoveManagementRealmTestCase tests intermittently fail
  cli/src/main/java/org/jboss/as/cli/impl/ReadlineConsole.java
Labels: deps-ok

#4577 [WFCORE-5383] Fix test failure in LdapTestCase that happens with openjdk-1.8.0.292
  elytron/src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
Labels: deps-ok

#4570 [WFCORE-5367] Sync model handler wrapper does not take into account a…
  controller/src/main/java/org/jboss/as/controller/operations/common/Util.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncModelOperationHandlerWrapper.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/SyncModelOperationTestCase.java
Labels: deps-ok

#4576 [WFCORE-5382]: The same Additional Runtime Dependency can be added several times for a single resource definition.
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
  controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/RuntimePackageDependency.java
  controller/src/test/java/org/jboss/as/controller/test/ReadFeatureDescriptionTestCase.java
Labels: deps-ok

#4583 [WFCORE-5397] Upgrade galleon-plugins 5.1.3.Final
  pom.xml
Labels: deps-ok

#4587 WFCORE-5400 Upgrade Mockito to 3.10.0.
  pom.xml
Labels: deps-ok

#4588 [WFCORE-5401] Upgrade to Byteman 4.0.15
  pom.xml
Labels: deps-ok

#4589 [WFCORE-5402] Upgrade JBoss Marshalling to 2.0.12.Final
  pom.xml
Labels: deps-ok

#4586 Fix for WFCORE-4324, CommandTimeoutHandlerTestCase.testComandExecutor random failure
  cli/src/main/java/org/jboss/as/cli/impl/CommandExecutor.java
Labels: deps-ok

#4578 [WFCORE-5386] Increase container shutdown wait time for better CI results stability
  controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/util/AbstractControllerTestBase.java
  host-controller/src/test/java/org/jboss/as/host/controller/util/AbstractControllerTestBase.java
  jmx/src/test/java/org/jboss/as/jmx/test/util/AbstractControllerTestBase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServicesImpl.java
Labels: deps-ok

#4592 [WFCORE-5407] Account for the testbom in the Dependency Tree Input Bu…
  .github/workflows/dep-diff-pull_request.yml
Labels: deps-ok, ready-for-merge

#4575 WFCORE-5375 Update all projects with a dependency on deprecated Elytron modules to no longer rely on deprecated classes
  controller/pom.xml
  controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-private/main/module.xml
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/PrincipalDecoderDefinitions.java
  pom.xml
Labels: deps-changed, ready-for-merge

#4595 [WFCORE-5410] Update elytron subsystem to take modular jdk params into account
  elytron/pom.xml
  pom.xml
Labels: SE17, ready-for-merge

#4593 [WFCORE-5408] Update JBoss Classfilewriter to 1.2.5.Final
  pom.xml
Labels: SE17

#4599 [WFCORE-5414] / [WFCORE-5415] WildFly Elytron and Elytron Web Upgrades
  pom.xml
Labels: deps-ok

#4598 [WFCORE-5412] Upgrade WildFly OpenSSL to 2.1.4.Final
  pom.xml
Labels: deps-ok

#4600 [WFCORE-5416]: Jgit incorrect reference in org.jboss.as.controller module.
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
Labels: deps-ok

#4602 [WFCORE-5418] Minimal but complete set of modular JDK params needed to build WildFly Core and run its whole test suite
  pom.xml
Labels: deps-ok

#4601 [WFCORE-5417] Upgrade galleon-plugins to 5.2.0.Alpha1
  pom.xml
Labels: deps-ok

#4582 [WFCORE-5368] Specifically track operations considered to be part of boot
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerClientFactoryImpl.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/OperationFailuresDuringBootTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/RootResourceDefinition.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/extension/booterror/TestExtension.java
  testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/booterror/module.xml
  testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/booterror/org.jboss.as.controller.Extension
Labels: deps-ok

#4603 [WFCORE-5423][WFCORE-5424] Upgrade jboss-remoting to 5.0.23.Final and add test dependency from protocol to wildfly-elytron-security-manager
  pom.xml
  protocol/pom.xml
Labels: deps-ok

#4462 [WFCORE-5255] / [WFCORE-5169] Migrate all tests to use Apache DS AM26 and org.apache.directory.api 2.0.0
  elytron/pom.xml
  elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
Labels: deps-ok

#4604 [WFCORE-5425] Upgrade Undertow to 2.2.8.Final
  pom.xml
Labels: deps-ok

#4606 [WFCORE-5429] Require Java 8 when the deploy lifecycle phase is executed.
  pom.xml
Labels: deps-ok

#4605 [WFCORE-5427] Avoid ClassCastException when determining whether or not a self-signed certificate should be automatically generated
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/test/java/org/wildfly/extension/elytron/LdapTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
Labels: deps-ok

#4591 [WFCORE-5406] Add --add-opens to the SE 9+ VM launch for expected ref…
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: SE17, deps-ok

#4608 [WFCORE-5431] Upgrade jboss-logging to 3.4.2.Final.
  pom.xml
Labels: deps-ok
