Repository wildfly/wildfly-core, pull requests merged in 2021-11, with the labels that each got.

#4846 [WFCORE-5675] Avoid NPE sending transformed operation results in Oper…
  controller/src/main/java/org/jboss/as/controller/remote/BlockingQueueOperationListener.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/HostControllerUpdateTask.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/OperationTransformationTestCase.java
Labels: deps-ok, SE17

#4847 [WFCORE-5682] Fix testsuite failures on SE17 when byteman is used
  testsuite/domain/pom.xml
  testsuite/manualmode/pom.xml
Labels: ready-for-merge, deps-ok, SE17

#4849 [WFCORE-5566] Use com.sun.net.ssl.internal.ssl.Provider.isFIPS() method for FIPS detection if it exists
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
Labels: ready-for-merge, deps-ok

#4848 WFCORE-5688 Replace usages of getParameterTypes().length with getPara…
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
  server/src/main/java/org/jboss/as/server/deployment/reflect/ClassReflectionIndex.java
Labels: ready-for-merge, deps-ok

#4857 [WFCORE-5694] RealmsTestCase fails on Mac
  elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
Labels: deps-ok

#4863 Fix for WFCORE-5704, Upgrade galleon plugins to 5.2.6.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4860 [WFCORE-5703] Remove deprecated org.jboss.as.server.deployment.Attach…
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
Labels: ready-for-merge, deps-ok

#4855 [WFCORE-5695] Wrap stdout and stderr in a logger for the bootable JAR…
  bootable-jar/runtime/pom.xml
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
Labels: ready-for-merge, deps-ok

#4862 [WFCORE-5702] "StandardCharsets" constants (server)
  server/src/main/java/org/jboss/as/server/DomainServerMain.java
Labels: ready-for-merge, deps-ok

#4861 [WFCORE-5701] "StandardCharsets" constants (process-controller)
  process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
  process-controller/src/main/java/org/jboss/as/process/ProcessController.java
  process-controller/src/main/java/org/jboss/as/process/ProcessControllerClient.java
  process-controller/src/main/java/org/jboss/as/process/ProcessControllerServerHandler.java
Labels: ready-for-merge, deps-ok

#4859 [WFCORE-5700] "StandardCharsets" constants (host-controller)
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
Labels: ready-for-merge, deps-ok

#4858 [WFCORE-5699] "StandardCharsets" constants (controller)
  controller/src/main/java/org/jboss/as/controller/TemporaryModuleLayer.java
Labels: ready-for-merge, deps-ok

#4703 [WFCORE-2806] Global domain config for unique GC log file name and path
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerOperationsFactory.java
Labels: Feature, deps-ok

#4869 [WFCORE-5707] Add a default impl of DeploymentUnitProcessor.undeploy …
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationContextDependencyProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/DependencyProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/EESecurityDependencyProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLContextDependencyProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainNameProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainProcessor.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingDependencyDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingDeploymentResourceProcessor.java
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerDeploymentUnitProcessor.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsValidationProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/AnnotationIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CleanupAnnotationIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/dependencies/DeploymentDependenciesProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/integration/Seam2Processor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ClassFileTransformerProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/DeploymentVisibilityProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/DriverDependenciesProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestExtensionListProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestExtensionNameProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleClassPathProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleExtensionListProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleIdentifierProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/reflect/CleanupReflectionIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/service/ServiceActivatorDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/service/ServiceActivatorProcessor.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/simple/subsystem/SimpleSubsystemDeploymentProcessor.java
Labels: deps-ok

#4870 [WFCORE-5714] Remove dead code in process-controller and eliminate JBoss marshalling dependencies
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/process-controller/main/module.xml
  process-controller/pom.xml
  process-controller/src/main/java/org/jboss/as/process/logging/ProcessLogger.java
  process-controller/src/main/java/org/jboss/as/process/protocol/ByteDataInput.java
  process-controller/src/main/java/org/jboss/as/process/protocol/ByteDataOutput.java
  process-controller/src/main/java/org/jboss/as/process/protocol/ChunkyByteInput.java
  process-controller/src/main/java/org/jboss/as/process/protocol/ChunkyByteOutput.java
  process-controller/src/main/java/org/jboss/as/process/protocol/ProtocolUtils.java
  process-controller/src/main/java/org/jboss/as/process/protocol/SimpleByteDataInput.java
  process-controller/src/main/java/org/jboss/as/process/protocol/SimpleByteDataOutput.java
  process-controller/src/main/java/org/jboss/as/process/protocol/StreamUtils.java
  process-controller/src/test/java/org/jboss/as/process/protocol/ChunkyByteInputOutputTest.java
Labels: deps-ok

#4852 WFCORE-5676: remove incorrect description resolution
  controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java
Labels: deps-ok

#4873 [WFCORE-5719] Remove pointless ExpressionResolver allocations in Attr…
  controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
Labels: ready-for-merge, deps-ok

#4871 [WFCORE-5715] Fix permission check failures that occur in the properties realm with the security manager enabled
  elytron/src/main/java/org/wildfly/extension/elytron/PropertiesRealmDefinition.java
Labels: deps-ok

#4816 [WFCORE-5489] As a developer, I want to override management attribute…
  controller/pom.xml
  controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/EnvVarAttributeOverrider.java
  controller/src/test/java/org/jboss/as/controller/EnvVarAttributeOverrideModel.java
Labels: Feature, missing-reqs, deps-ok

#4872 [WFCORE-5717] Upgrade Undertow version to 2.2.13.Final
  pom.xml
Labels: deps-ok

#4868 [WFCORE-5709][WFCORE-5705] Make ElytronExpressionResolver useful in S…
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ExpressionResolver.java
  controller/src/main/java/org/jboss/as/controller/ExpressionResolverExtension.java
  controller/src/main/java/org/jboss/as/controller/ExpressionResolverImpl.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ResolveExpressionHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/validation/OperationValidator.java
  controller/src/test/java/org/jboss/as/controller/ExpressionResolverUnitTestCase.java
  elytron/src/main/java/org/wildfly/extension/elytron/ExpressionResolverResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/ElytronExpressionResolver.java
  elytron/src/test/java/org/wildfly/extension/elytron/ElytronSubsystem13_0TestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/ElytronSubsystem14_0TestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/ExpressionResolutionTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/ResolveExpressionAttributesTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/RuntimeExpressionResolver.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/expressions/AbstractSecureExpressionsTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/expressions/CredentialStoreExpressionsTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/expressions/module/TestSecureExpressionsExtension.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/org.jboss.as.controller.Extension
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/security-module.xml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/test-secure-expressions-module.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/SecureExpressionUtil.java
Labels: deps-ok

#4874 Fix for WFCORE-5722, Can't upgrade JBoss Modules artifact
  bootable-jar/boot/pom.xml
  pom.xml
Labels: deps-ok

#4850 [WFCORE-5685] KerberosHttpMgmtSaslTestCase & KerberosNativeMgmtSaslTestCase tests fail on JDK 18 EA
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/AbstractKrb5ConfServerSetupTask.java
  testsuite/elytron/src/test/resources/org/wildfly/test/security/common/kerberos/krb5.conf
Labels: ready-for-merge, deps-ok

#4875 [WFCORE-5725] Upgrade to Byteman 4.0.18
  pom.xml
Labels: deps-ok

#4877 [WFCORE-5727] Upgrade XNIO to 3.8.5.Final
  pom.xml
Labels: deps-ok

#4878 [WFCORE-5728] Upgrade WildFly Elytron to 1.18.0.Final
  pom.xml
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
Labels: deps-ok
