Repository wildfly/wildfly-core, pull requests merged in 2021-01, with the labels that each got.

#4430 [WFCORE-5231] Upgrade httpcomponents.httpcore 4.4.14
  pom.xml
Labels: deps-ok

#4434 WFCORE-5302 Update Google guava 30.1-jre
  model-test/pom.xml
  pom.xml
Labels: deps-ok

#4440 [WFCORE-5230] Upgrade Jandex 2.1.4.Final
  pom.xml
Labels: deps-ok

#4443 [WFCORE-5238] Set default KeyStore type to JKS.
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-profile.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/elytron-app.xml
  elytron/src/main/resources/subsystem-templates/elytron.xml
Labels: Blocker, deps-ok

#4435 [WFCORE-5233] Improve ability for WildFly Core consumers to use its Galleon source without depending on the wildfly-core feature pack
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/ee-8-api/src/main/resources/license/core-feature-pack-ee-8-api-licenses.xml
  core-feature-pack/galleon-common/src/main/resources/configs/domain/model.xml
  core-feature-pack/galleon-common/src/main/resources/configs/host/model.xml
  core-feature-pack/galleon-common/src/main/resources/configs/standalone/model.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-basic-profile.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-profile.xml
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-standalone-profile.xml
  core-feature-pack/galleon-feature-pack/pom.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/feature_groups/basic-profile.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/content/bin/product.conf
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/wildfly-core/module.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/package.xml
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/pm/wildfly/resources/modules/system/layers/base/org/jboss/as/product/wildfly-core/dir/META-INF/MANIFEST.MF
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/pm/wildfly/tasks.xml
  core-feature-pack/galleon-pruned/assembly.xml
  core-feature-pack/galleon-pruned/pom.xml
  core-feature-pack/galleon-pruned/src/main/resources/feature_groups/management-interfaces.xml
  core-feature-pack/galleon-pruned/src/main/resources/feature_groups/management-legacy-security.xml
  core-feature-pack/galleon-pruned/src/main/resources/layers/standalone/legacy-management/layer-spec.xml
  core-feature-pack/galleon-pruned/src/main/resources/layers/standalone/legacy-remoting/layer-spec.xml
  core-feature-pack/legacy-feature-pack/pom.xml
  core-feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#4441 [WFCORE-5236] Upgrade WildFly Elytron to 1.14.1.Final
  pom.xml
Labels: deps-ok

#4431 [WFCORE-5232] Use a new process to delete the install directory. JBos…
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/CleanupProcessor.java
  bootable-jar/boot/src/main/java/org/wildfly/core/jar/boot/Main.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableEnvironment.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/InstallationCleaner.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/bootable-jar/main/module.xml
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
Labels: deps-ok

#4448 Fix for WFCORE-5199, CLI, shaded jar can't start embedded when logging json formater configured
  cli/pom.xml
Labels: deps-changed

#4454 Fix for WFCORE-5244, Upgrade tests to bootable JAR 3.0.0.Final
  pom.xml
Labels: deps-ok

#4421 [WFCORE-5216] jboss-cli.sh script should use eval instead of exec
  core-feature-pack/common/src/main/resources/content/bin/jboss-cli.sh
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
Labels: deps-ok

#4442 [WFCORE-5237] Upgrade bouncycastle to 1.68
  pom.xml
Labels: deps-ok

#4459 [WFCORE-5252] Log WARN if wildfly.config.url is set on the server.
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
  server/src/main/java/org/jboss/as/server/ApplicationServerService.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: deps-ok

#4463 [WFCORE-5256] fix console-enabled attribute in http interface
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_16.java
Labels: deps-ok

#4356 [WFCORE-2687] Addition of getCurrentOperationName() and getCurrentOperationParameter(String name) methods
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemParsingTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
Labels: Stale, deps-ok

#4378 [WFCORE-3825] Unify -server option in windows scripts (ps1, bat) for domain mode (and its servers) on all JDKs
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.ps1
Labels: deps-ok

#4455 [WFCORE-4516] Updated the description of 'core.management.security-realm.server-identity.secret.value' attribute.
  controller/src/main/resources/org/jboss/as/controller/descriptions/common/LocalDescriptions.properties
Labels: deps-ok
