Repository wildfly/wildfly-core, pull requests merged in 2021-06, with the labels that each got.

#4612 [WFCORE-5406] Fixing typo
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
Labels: deps-ok

#4610 [WFCORE-5255] / [WFCORE-5169] Revert WFCORE-5255 and WFCORE-5169
  elytron/pom.xml
  elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
Labels: deps-ok

#4614 [WFCORE-5438] For modular VMs include --add-exports=java.naming/com.s…
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: deps-ok

#4620 [WFCORE-5448] Upagde JavaEWAH 1.1.12
  pom.xml
Labels: deps-ok

#4619 [WFCORE-5446] Upgrade WildFly Galleon Plugons 5.2.0.Alpha2
  pom.xml
Labels: deps-ok

#4594 [WFCORE-5409]: Upgrade JGit to 5.11.1.202105131744-r
  deployment-repository/src/main/java/org/jboss/as/repository/PathUtil.java
  pom.xml
  server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
Labels: deps-ok

#4626 [WFCORE-5452] Sync updates to TLS configuration and minor changes for Java 17.
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/tls-oracle13plus.xml
  pom.xml
Labels: deps-ok

#4624 Fix for WFCORE-5447, Upgrade galleon-plugins to 5.2.0.Final
  pom.xml
Labels: 16.x, Blocker, deps-ok

#4621 Fix for WFCORE-5453, Include add-opens and add-exports to Bootable JAR runtime manifest
  bootable-jar/boot/pom.xml
  core-feature-pack/common/src/main/resources/content/bin/common.sh
Labels: 16.x, Blocker, deps-ok

#4627 [WFCORE-5460] Upgrade WildFly Elytron to 1.16.0.Final
  pom.xml
Labels: 16.x, Blocker, deps-ok

#4629 Fix for WFCORE-5462, Upgrade to Bootable JAR plugin 5.0.0.Beta1
  pom.xml
Labels: deps-ok

#4611 [WFCORE-5434] Update ide-config to Eclipse 2021-03
  ide-configs/eclipse/wildfly-cleanup.xml
  ide-configs/eclipse/wildfly-formatter.xml
  ide-configs/eclipse/wildfly-templates.xml
Labels: deps-ok

#4637 WFCORE-5471 Broken links in README
  README.md
Labels: deps-ok

#4618 [WFCORE-5445] Short circuit logic for boolean eval
  controller/src/main/java/org/jboss/as/controller/access/constraint/AbstractSensitivity.java
  patching/src/main/java/org/jboss/as/patching/runner/AbstractPatchingTask.java
  patching/src/main/java/org/jboss/as/patching/tool/ContentPolicyBuilderImpl.java
Labels: deps-ok

#4631 [WFCORE-5444] Remove unused code
  controller/src/main/java/org/jboss/as/controller/remote/ModelControllerClientOperationHandler.java
  controller/src/main/java/org/jboss/as/controller/remote/OperationMessageHandlerProxy.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolOperationHandler.java
  jmx/src/main/java/org/jboss/as/jmx/model/MutabilityChecker.java
Labels: deps-ok

#4617 [WFCORE-5443] JMX MBeanInfoFactory OR Statement has same comparision
  jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
Labels: deps-ok

#4616 [WFCORE-5442] Math operands should be cast before assignment
  cli/src/main/java/org/jboss/as/cli/handlers/ReloadHandler.java
  cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  cli/src/main/java/org/jboss/as/cli/impl/aesh/cmd/security/ssl/ManagementDisableSSLCommand.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/ZipCompletionScanner.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/cors/CorsHttpHandler.java
  patching/src/main/java/org/jboss/as/patching/runner/PatchModuleInvalidationUtils.java
Labels: deps-ok

#4615 [WFCORE-5441] Logic in try/finally blocks hides exceptions
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/TemporaryModuleLayer.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/LdapCacheService.java
Labels: deps-ok, ready-for-merge

#4641 [WFCORE-5217] Add Phase constants for MP Reactive Messaging and RSO
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok
