Repository wildfly/wildfly-core, pull requests merged in 2022-02, with the labels that each got.

#4952 [WFCORE-5555] Reenable CLIEmbedHostControllerTestCase and CLIEmbedSer…
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedUtil.java
Labels: deps-ok

#4945 [WFCORE-5786] / [WFCORE-5787] WildFly OpenSSL Component Upgrades
  pom.xml
Labels: ready-for-merge, deps-ok

#4946 [18.x][WFCORE-5786] / [WFCORE-5787] WildFly OpenSSL Component Upgrades
  pom.xml
Labels: ready-for-merge

#4948 [WFCORE-5788] Require a minimum of Java 11
  cli/pom.xml
  component-matrix-builder/pom.xml
  core-feature-pack/common/src/main/resources/content/bin/domain.conf.ps1
  core-feature-pack/common/src/main/resources/content/bin/standalone.conf.ps1
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-add-user/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/host-controller/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/process-controller/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/standalone/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/msc/main/module.xml
  deployment-scanner/pom.xml
  elytron/src/test/java/org/wildfly/extension/elytron/JdkUtils.java
  elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/OpenSslTlsTestCase.java
  testsuite/pom.xml
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/JdkModuleDependencyTestCase.java
Labels: ready-for-merge, deps-ok

#4954 [WFCORE-5797] Upgrade XNIO to 3.8.6.Final
  pom.xml
Labels: deps-ok

#4950 WFCORE-5794 Make StandardResourceDescriptionResolver#getVariableBundl…
  controller/src/main/java/org/jboss/as/controller/descriptions/StandardResourceDescriptionResolver.java
  threads/src/main/java/org/jboss/as/threads/ThreadPoolResourceDescriptionResolver.java
Labels: deps-ok

#4957 [WFCORE-5801] Upgrade Undertow to 2.2.15.Final
  pom.xml
Labels: deps-ok

#4956 WFCORE-5800 Remove unused Charset Map Variable and Method in ManagementHttpServer class
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
Labels: deps-ok

#4959 [WFCORE-5804] Move the log4j 1 test dependency to testbom
  pom.xml
  testbom/pom.xml
  testsuite/client-old-server/pom.xml
  testsuite/elytron/pom.xml
  testsuite/embedded/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/standalone/pom.xml
Labels: deps-ok

#4960 [18.x][WFCORE-5804] Move test dep from log4j:log4j to ch.qos.reload4j:reload4j and move it to testbom
  pom.xml
  testbom/pom.xml
  testsuite/client-old-server/pom.xml
  testsuite/elytron/pom.xml
  testsuite/embedded/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/standalone/pom.xml
Labels: 18.x

#4962 [WFCORE-5806] Remove maven.repository.redhat.com repository.
  pom.xml
Labels: ready-for-merge, deps-ok

#4964 [WFCORE-5801] Upgrade Undertow to 2.2.16.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4949 WFCORE-5793 Disable java-class-based resource bundle and disable fall…
  controller/src/main/java/org/jboss/as/controller/descriptions/StandardResourceDescriptionResolver.java
Labels: deps-ok

#4972 [WFCORE-5813] Eliminating unused CapabilityServiceBuilder.addInjection() method
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: ready-for-merge, deps-ok

#4973 [WFCORE-5812] Removing dead code in PathsTestCase
  controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java
Labels: ready-for-merge, deps-ok

#4843 [WFCORE-5600] Move AcmeMockServerBuilder out of testsuite/shared; eli…
  pom.xml
  testbom/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/shared/pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/AcmeMockServerBuilder.java
  testsuite/standalone/src/test/resources/org/jboss/as/test/integration/management/cli/README.txt
  testsuite/standalone/src/test/resources/org/jboss/as/test/integration/management/cli/account.keystore
Labels: ready-for-merge, deps-ok

#4975 WFCORE-5814 Use EnumMap in place of HashMap for enum keys; code cleanup
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Labels: ready-for-merge, deps-ok

#4967 [WFCORE-5807] Update logback test dependency to 1.2.9 (CVE-2021-42550)
  testsuite/embedded/pom.xml
Labels: ready-for-merge, deps-ok

#4968 [18.x][WFCORE-5807] Update logback test dependency to 1.2.9 (CVE-2021-42550)
  testsuite/embedded/pom.xml
Labels: ready-for-merge, 18.x

#4977 WFCORE-5817 README.md contains broken link to contributing doc, and i…
  README.md
Labels: ready-for-merge, deps-ok
