Repository wildfly/wildfly-core, pull requests merged in 2022-06, with the labels that each got.

#5102 [WFCORE-5912] [blacklist/whitelist] Find and replace occurrences in d…
  remoting/subsystem/src/main/resources/org/jboss/as/remoting/LocalDescriptions.properties
Labels: ready-for-merge, deps-ok

#5016 [WFCORE-5843] [primary/secondary] Find and replace occurrences in the…
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
  elytron/src/test/java/org/wildfly/extension/elytron/CredentialStoreUtility.java
  host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
  host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
  process-controller/src/main/java/org/jboss/as/process/CommandLineConstants.java
  process-controller/src/main/java/org/jboss/as/process/logging/ProcessLogger.java
Labels: ready-for-merge, deps-ok

#5118 [WFCORE-5929] Prepare io.undertow.core module for upcoming upgrade of Undertow in WildFly preview
  core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
Labels: ready-for-merge, deps-ok

#5117 [WFCORE-5918]: Adding SSO to application security domain via YamlConfigurationExtension doesn't work.
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
Labels: ready-for-merge, deps-ok

#5120 WFCORE-5932 Incorrect values for keys in LocalDescriptions.properties files
  core-management/core-management-subsystem/src/main/resources/org/wildfly/extension/core/management/LocalDescriptions.properties
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
Labels: ready-for-merge, deps-ok

#5122 [WFCORE-5934] Fixing DeletionCollisionTest byteman rule file to properly match method signature
  deployment-repository/src/test/resources/lockDeployment.btm
Labels: ready-for-merge, deps-ok

#5121 [WFCORE-5933] JUnit assertions should not be used in "run" methods
  controller/src/test/java/org/jboss/as/controller/ModelControllerLockTestCase.java
Labels: ready-for-merge, deps-ok

#5017 WFCORE-2852/WFCORE-5853: CLI autocomplete suggests non-existent subsystems
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadChildrenNamesHandler.java
  controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
  logging/src/main/java/org/jboss/as/logging/LoggingExtension.java
Labels: ready-for-merge, deps-ok

#5123 [WFCORE-5936] Ldap autentication using referrals fails on JDK 17 with ApacheDS
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
Labels: ready-for-merge, deps-ok

#5110 [WFCORE-5917] Duplicating -Djboss.server.base.dir if defined in more than one place
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
Labels: ready-for-merge, deps-ok

#5125 [WFCORE-5943] Exclude undertow-servlet transitive dependencies
  pom.xml
Labels: ready-for-merge, deps-ok

#5127 [WFCORE-5946] Upgrade Undertow to 2.2.18.Final (fixes CVE-2022-1319)
  pom.xml
Labels: ready-for-merge, deps-ok

#5129 [WFCORE-5931] Upgrade JBoss Remoting to 5.0.25.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4686 WFCORE-5527: ensure content folder is deleted on undeploy
  deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
  deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
  deployment-repository/src/test/java/org/jboss/as/repository/DeletionCollisionTest.java
  deployment-repository/src/test/java/org/jboss/as/repository/PathUtilTest.java
  deployment-repository/src/test/resources/testfile.xhtml
Labels: ready-for-merge, deps-ok, Stale

#5049 WFCORE-1960: replace list of properties with map of strings
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentService.java
  deployment-scanner/src/test/java/org/jboss/as/server/deployment/scanner/FileSystemDeploymentServiceUnitTestCase.java
  domain-management/src/main/java/org/jboss/as/domain/management/controller/ActiveOperationResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
Labels: ready-for-merge, deps-ok

#5133 [WFCORE-5949]: Adding meta-data to json-logger via YamlConfigurationExtension results in ClassCastException.
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
Labels: ready-for-merge, deps-ok

#5132 [WFCORE-5948]: Upgrade JGit to 6.2.0.202206071550-r
  pom.xml
Labels: ready-for-merge, deps-changed

#5138 [WFCORE-5951] Upgrade JBoss Marshalling to 2.1.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5137 [WFLY-5950] Update client-side modular args to standard set that we s…
  elytron/pom.xml
  jakartaee/elytron-jakarta/pom.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#5139 WFCORE-5953/WFCORE-5954: Fixing several YAML extension issues
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml
Labels: ready-for-merge, deps-ok

#5115 WFCORE-5927 Misleading message for embedded server configuration file.
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
Labels: ready-for-merge, deps-ok

#5141 [WFCORE-5956] Align Jakarta Authorization and Authentication versions…
  jakartaee/pom.xml
Labels: ready-for-merge, deps-ok

#5140 [WFCORE-5781] Remove log4j 1.x support. This removes the module, the …
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/log4j/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/logging/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/log4j/logmanager/main/module.xml
  embedded/src/main/java/org/wildfly/core/embedded/Configuration.java
  logging/pom.xml
  logging/src/main/java/org/jboss/as/logging/LoggingModuleDependency.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingDependencyDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/logmanager/Log4jAppenderHandler.java
  logging/src/test/java/org/jboss/as/logging/logmanager/Log4jAppenderTestCase.java
  pom.xml
  testbom/pom.xml
  testsuite/client-old-server/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
  testsuite/elytron/pom.xml
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/AbstractKrb5ConfServerSetupTask.java
  testsuite/embedded/pom.xml
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/Log4jHostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/Log4jStandaloneTestCase.java
  testsuite/embedded/src/test/resources/log4j.properties
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/Log4j2ServiceActivator.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/Log4jAppenderTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/Log4jServiceActivator.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/LoggingDependenciesTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/CustomModuleHandlerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/TestEnvironment.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/module/impl/AppendingAppender.java
  testsuite/standalone/pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/operations/Log4jCustomHandlerTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/JBossLog4jXmlTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/Log4jPropertiesTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/perdeploy/Log4jXmlTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Log4jLoggingProfilesTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/HttpManagementConstantHeadersTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/http/XCorrelationIdTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/secmgr/InvalidPermissionTestCase.java
Labels: ready-for-merge, deps-changed

#5142 [WFCORE-5959] Upgrade Jandex to 2.4.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok
