Repository wildfly/wildfly-core, pull requests merged in 2022-03, with the labels that each got.

#4971 WFCORE-5811 Improvement to NonResolvingResourceDescriptionResolver.ge…
  controller/src/main/java/org/jboss/as/controller/descriptions/NonResolvingResourceDescriptionResolver.java
Labels: ready-for-merge, deps-ok

#4976 WFCORE-5815 StringBuilder op in CommandContextImpl is created and updated but never used
  cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
Labels: ready-for-merge, deps-ok

#4982 [WFCORE-5818]: !remove might not work properly with some resources
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_parent_remove.yml
Labels: ready-for-merge

#4988 [18.x][WFCORE-5769] Adjust chmod to 644 for dev content
  core-feature-pack/common/src/main/resources/content/bin/add-user.sh
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.bat
  core-feature-pack/common/src/main/resources/content/bin/jboss-cli.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-debian.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly.conf
  domain-http/error-context/src/main/resources/index.html
  domain-http/error-context/src/main/resources/normalize.css
  domain-http/error-context/src/main/resources/normalize.min.css
Labels: 18.x

#4985 WFCORE-5745 WFCORE-5751 WFCORE-5779 WFCORE-5785 WFCORE-5797 Port component upgrades from main to 18.x
  pom.xml
Labels: 18.x

#4990 [WFCORE-5824] Upgrade log4j2 2.17.2
  pom.xml
Labels: deps-ok

#4910 WFCORE-5760 Replace deprecated EnumValidator constructors and methods
  controller/src/main/java/org/jboss/as/controller/operations/global/QueryOperationHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceDescriptionHandler.java
  controller/src/test/java/org/jboss/as/controller/SimpleAttributeDefinitionUnitTestCase.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/PrincipalResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/audit/SyslogAuditLogHandlerResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/controller/ActiveOperationResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/SaslServerDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/DomainServerLifecycleHandlers.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/DomainControllerWriteAttributeHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/RemoteDomainControllerAddHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/resources/ServerConfigResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/AsyncHandlerResourceDefinition.java
  logging/src/main/java/org/jboss/as/logging/handlers/ConsoleHandlerResourceDefinition.java
  platform-mbean/src/main/java/org/jboss/as/platform/mbean/CommonAttributes.java
  platform-mbean/src/main/java/org/jboss/as/platform/mbean/MemoryPoolResourceDefinition.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemoteOutboundConnectionResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/DeploymentAttributes.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java
  threads/src/main/java/org/jboss/as/threads/KeepAliveTimeAttributeDefinition.java
Labels: ready-for-merge, deps-ok

#4994 [WFCORE-5826] Upgrade WildFly Common to 1.6.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4989 [18.x][WFCORE-5766] Upgrading to JBoss Modules 2.0.1.Final
  core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
  pom.xml
Labels: ready-for-merge, 18.x

#4991 [18.x][WFCORE-5824] Upgrade log4j2 2.17.2
  pom.xml
Labels: ready-for-merge, 18.x

#4992 [WFCORE-5825] Upgrade slf4j 1.7.36
  pom.xml
Labels: deps-ok

#4998 [WFCORE-5790] Upgrade jboss-parent from 37 to 39
  pom.xml
Labels: 18.x

#4993 [18.x][WFCORE-5825] Upgrade slf4j 1.7.36
  pom.xml
Labels: 18.x

#4995 [18.x][WFCORE-5826] Upgrade WildFly Common to 1.6.0.Final
  pom.xml
Labels: 18.x

#4996 [WFCORE-5827] Add elytron-tool to the core-tools layer definition
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/core-tools/layer-spec.xml
Labels: ready-for-merge, deps-ok

#4947 WFLY-5792: ensure configuration files are inside the configuration directory
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java
Labels: ready-for-merge, deps-ok

#4999 [WFCORE-5828] WildFly-Common 1.6 depends on java.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/common/main/module.xml
Labels: deps-ok

#5000 [18.x][WFCORE-5828] WildFly-Common 1.6 depends on java.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/common/main/module.xml
Labels: 18.x

#4997 [18.x][WFCORE-5827] Add elytron-tool to the core-tools layer definition
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/core-tools/layer-spec.xml
Labels: 18.x

#4955 [WFCORE-5798] Restore ReloadRedirectTestCase.testReloadwithRedirect
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
Labels: ready-for-merge, deps-ok

#5003 [18.x][WFCORE-5798] Restore ReloadRedirectTestCase.testReloadwithRedirect
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIAuthenticationTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadRedirectTestCase.java
Labels: 18.x

#5004 WFCORE-5833 Fix warnings from deprecated method Assert.assertEquals(O…
  controller/src/test/java/org/jboss/as/controller/test/OrderedChildResourceTestCase.java
Labels: deps-ok

#4772 [WFCORE-5594] Restriction of XML External Entity Reference (XXE)
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  cli/src/main/java/org/jboss/as/cli/impl/CliConfigImpl.java
  controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/XmlCompletionScanner.java
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/S3Util.java
  model-test/src/main/java/org/jboss/as/model/test/MavenSettings.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SchemaValidator.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Labels: ready-for-merge, deps-ok

#5009 [WFCORE-5834]: The deployent-scanner needs org.wildfly.common
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml
Labels: deps-ok

#5010 [WFCORE-5834]: The deployent-scanner needs org.wildfly.common
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/deployment-scanner/main/module.xml
Labels: 18.x

#5018 [WFCORE-5778][WFCORE-5782] JDK18 Security Manager Backports
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  process-controller/src/main/java/org/jboss/as/process/Main.java
Labels: ready-for-merge, 18.x

#4951 [WFCORE-4314] - verbose and recursive parameter in read-alias(es)
  elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
  elytron/src/main/java/org/wildfly/extension/elytron/CertificateChainAttributeDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/ModifiableKeyStoreDecorator.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/test/java/org/wildfly/extension/elytron/KeyStoresTestCase.java
Labels: Feature, deps-ok

#5024 [WFCORE-5752] Use WildFly 26 as a placeholder for EAP XP 4
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
Labels: ready-for-merge, Critical, 18.x

#5021 WFCORE-5765 Unable to check the result containing whitespace with the…
  cli/src/main/java/org/jboss/as/cli/handlers/ifelse/ConditionArgument.java
  cli/src/test/java/org/jboss/as/cli/parsing/ifelse/test/EqualsTestCase.java
Labels: ready-for-merge, 18.x

#5019 [WFCORE-4867] Highlight the config name in start message
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
  server/src/main/java/org/jboss/as/server/BootstrapListener.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: ready-for-merge, 18.x

#5025 [WFCORE-5858] Move away from the deprecated GSSCredentialSecurityFactory.
  elytron/src/main/java/org/wildfly/extension/elytron/KerberosSecurityFactoryDefinition.java
Labels: deps-ok

#5022 WFCORE-5793 Disable java-class-based resource bundle and disable fall…
  controller/src/main/java/org/jboss/as/controller/descriptions/StandardResourceDescriptionResolver.java
Labels: 18.x

#5026 [WFCORE-5854] Upgrade WildFly Elytron to 1.19.0.Final
  pom.xml
Labels: deps-ok

#5020 [18.x][WFCORE-5490] Integrate Elytron credential expressions into system-property resource handling
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ExpressionResolver.java
  controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
  controller/src/main/java/org/jboss/as/controller/extension/ExpressionResolverExtension.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/extension/ResolverExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
  elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
  elytron/src/main/java/org/wildfly/extension/elytron/ExpressionResolverResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/DeploymentExpressionResolverProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/ElytronExpressionResolver.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/ExpressionResolverRuntimeHandler.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/RuntimeExpressionResolver.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/operations/SystemPropertyAddHandler.java
  server/src/main/java/org/jboss/as/server/operations/SystemPropertyDeferredProcessor.java
  server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
  server/src/test/java/org/jboss/as/server/operations/SystemPropertyAddHandlerUnitTestCase.java
  server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractKernelServicesImpl.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/expression/SystemPropertyExpressionTestCase.java
Labels: 18.x

#4983 [WFCORE-5530] Add encryption support to FilesystemSecurityRealm
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser15_1.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_15_1.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-expressions.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/M/MF2HI4TJMJ2XIZKVONSXE.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4Q.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4RR.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4SFOZSXE6LUNBUW4ZY.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mycredstore.cs
  elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml
Labels: Feature

#5014 [18.x][WFCORE-5530] Add encryption support to FilesystemSecurityRealm
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser15_1.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/main/resources/schema/wildfly-elytron_15_1.xsd
  elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-expressions.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/M/MF2HI4TJMJ2XIZKVONSXE.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4Q.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4RR.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/filesystem-realm-5/O/OBWGC2LOKVZWK4SFOZSXE6LUNBUW4ZY.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/mycredstore.cs
  elytron/src/test/resources/org/wildfly/extension/elytron/realms-test.xml
Labels: Feature, 18.x

#4987 [18.x][WFCORE-5777] Upgrading to JBoss Modules 2.0.2.Final
  pom.xml
Labels: 18.x

#4970 WFCORE-5810 Fix license in wildfly-cli jar.
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
Labels: ready-for-merge, deps-ok

#4909 [WFCORE-5759] Upgrade bouncycastle from 1.69 to 1.70
  pom.xml
Labels: ready-for-merge

#5030 [WFCORE-5829] Upgrade JBoss Remoting to 5.0.24.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5033 typo fix
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
Labels: ready-for-merge, deps-ok

#5037 [18.x] [WFCORE-5810] Fix license in wildfly-cli jar.
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
Labels: ready-for-merge, 18.x

#5039 [18.x][WFCORE-5829] Upgrade JBoss Remoting to 5.0.24.Final
  pom.xml
Labels: ready-for-merge, 18.x

#5038 [18.x][WFCORE-5563] Remove commons-lang(2) usage, use commons-lang3.
  elytron/pom.xml
  pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/JmxRBACProviderHostScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/JmxRBACProviderServerGroupScopedRolesTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/AbstractJmxNonCoreMBeansSensitivityTestCase.java
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/integration/security/common/AbstractBaseSecurityRealmsServerSetupTask.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/TestSuiteEnvironment.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ForLoopTestCase.java
Labels: ready-for-merge, 18.x
