Repository wildfly/wildfly-core, pull requests merged in 2022-01, with the labels that each got.

#4747 [WFCORE-4867] Highlight the config name in start message
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
  server/src/main/java/org/jboss/as/server/BootstrapListener.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: ready-for-merge, deps-ok

#4914 [WFCORE-5766] Upgrading to JBoss Modules 2.0.1.Final
  core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#4911 [WFCORE-5764] Can't write/acquire credentials from a store using the elytron-tool script
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-tool/main/module.xml
Labels: ready-for-merge, deps-ok

#4917 [WFCORE-5767] Add the Elytron OIDC Client related dependencies to Core
  pom.xml
Labels: ready-for-merge, deps-ok

#4918 [18.x][WFCORE-5767] Add the Elytron OIDC Client related dependencies to Core
  pom.xml
Labels: ready-for-merge, 18.x

#4908 Fix for WFCORE-5756, Upgrade bootable jar to 7.0.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#4920 [WFCORE-5768] Change default behaviour to resolve jboss parent pom
  pom.xml
Labels: deps-ok

#4922 [18.x][WFCORE-5770] Upgrade log4j 2 to 2.17.1
  pom.xml
Labels: ready-for-merge, 18.x

#4919 [WFCORE-5758] Fix RealmsTestCase & TlsTestCase on IBM JDK8
  elytron/src/test/java/org/wildfly/extension/elytron/RealmsTestCase.java
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
Labels: deps-ok

#4766 [WFCORE-5343]: YAML support for configuration customization.
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Arguments.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
  controller/pom.xml
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/ObjectListAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/ParsedBootOp.java
  controller/src/main/java/org/jboss/as/controller/PrimitiveListAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/SimpleListAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationExtension.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationExtensionFactory.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/main/java/org/jboss/as/controller/resource/InterfaceDefinition.java
  controller/src/test/java/org/jboss/as/controller/ListAttributeDefinitionTestCase.java
  controller/src/test/java/org/jboss/as/controller/TestModelControllerService.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/META-INF/services/org.jboss.as.controller.persistence.ConfigurationExtension
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_delete_add.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_list.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_list_add.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_list_merge.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_overwrite.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_remove.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_undefine.yml
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/dir/.gitkeep
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/yaml/snakeyaml/main/module.xml
  domain-http/interface/src/test/java/org/jboss/as/domain/http/server/TestModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerConfigurationPersister.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
  pom.xml
  server/src/main/java/org/jboss/as/server/CommandLineArgumentUsageImpl.java
  server/src/main/java/org/jboss/as/server/Main.java
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/ServerStartTask.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  server/src/test/java/org/jboss/as/controller/persistence/GitPersistenceResourceTestCase.java
  server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AbstractLogFieldsOfLogTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTest.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/LoggingDependenciesTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ReloadOpsTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/bootable-groups.properties
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/bootable-users.properties
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.cli
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Labels: Feature, deps-changed

#4927 [WFCORE-5771] Upgrade jboss-logging to 3.4.3.Final.
  pom.xml
Labels: 18.x

#4926 [WFCORE-5771] Upgrade jboss-logging to 3.4.3.Final.
  pom.xml
Labels: deps-ok

#4915 WFCORE-5765 Unable to check the result containing whitespace with the…
  cli/src/main/java/org/jboss/as/cli/handlers/ifelse/ConditionArgument.java
  cli/src/test/java/org/jboss/as/cli/parsing/ifelse/test/EqualsTestCase.java
Labels: ready-for-merge, deps-ok

#4929 [WFCORE-5772] Upgrade WildFly Elytron to 1.18.2.Final
  pom.xml
Labels: deps-ok

#4931 [WFCORE-5776] Upgrade WildFly Elytron to 1.18.3.Final
  pom.xml
Labels: deps-ok

#4935 WFCORE-5779 Upgrade jandex to 2.4.2.Final
  pom.xml
Labels: deps-ok

#4933 [WFCORE-5777] Upgrading to JBoss Modules 2.0.2.Final
  pom.xml
Labels: deps-ok

#4921 [WFCORE-5769] Adjust chmod to 644 for dev content
  core-feature-pack/common/src/main/resources/content/bin/add-user.sh
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/elytron-tool.bat
  core-feature-pack/common/src/main/resources/content/bin/jboss-cli.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-debian.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly-init-redhat.sh
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/init.d/wildfly.conf
  domain-http/error-context/src/main/resources/index.html
  domain-http/error-context/src/main/resources/normalize.css
  domain-http/error-context/src/main/resources/normalize.min.css
Labels: deps-ok

#4925 [WFCORE-5490] Integrate Elytron credential expressions into system-pr…
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ExpressionResolver.java
  controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
  controller/src/main/java/org/jboss/as/controller/extension/ExpressionResolverExtension.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/extension/ResolverExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/TestModelControllerService.java
  elytron/src/main/java/org/wildfly/extension/elytron/Capabilities.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
  elytron/src/main/java/org/wildfly/extension/elytron/ExpressionResolverResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/DeploymentExpressionResolverProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/ElytronExpressionResolver.java
  elytron/src/main/java/org/wildfly/extension/elytron/expression/ExpressionResolverRuntimeHandler.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/RuntimeExpressionResolver.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/operations/SystemPropertyAddHandler.java
  server/src/main/java/org/jboss/as/server/operations/SystemPropertyDeferredProcessor.java
  server/src/main/java/org/jboss/as/server/parsing/SystemPropertiesXml.java
  server/src/test/java/org/jboss/as/server/operations/SystemPropertyAddHandlerUnitTestCase.java
  server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractKernelServicesImpl.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/expression/SystemPropertyExpressionTestCase.java
Labels: deps-ok

#4882 [WFCORE-5590]: Provide a separate javax.* namespace Jakarta JSON api …
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/internal/javax/json/api/ee8/main/module.xml
  pom.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: hold, deps-changed, Critical

#4939 [WFCORE-5778] Reset 'java.security.manager' default value back to "allow" by default in launcher
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: ready-for-merge, deps-ok

#4936 [WFCORE-5782] Reset 'java.security.manager' default value back to "allow" by default in WildFly shell scripts
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
  process-controller/src/main/java/org/jboss/as/process/Main.java
Labels: ready-for-merge, deps-ok

#4944 Fix for WFCORE-5785, Upgrade galleon plugins to 5.2.10.Final
  pom.xml
Labels: deps-ok

#4940 [WFCORE-5783] Upgrade log4j-jboss-logmanager to 1.3.0.Final.
  pom.xml
Labels: deps-ok

#4941 [WFCORE-5783] Upgrade log4j-jboss-logmanager to 1.3.0.Final.
  pom.xml
Labels: 18.x

#4942 [WFCORE-5784] Deprecate the org.jboss.log4j.logmanager module. Also a…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/log4j/main/module.xml
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
Labels: deps-ok

#4943 [WFCORE-5784] Deprecate the org.jboss.log4j.logmanager module. Also a…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/apache/log4j/main/module.xml
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/handlers/HandlerOperations.java
  logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
Labels: 18.x
