Repository wildfly/wildfly-core, pull requests merged in 2022-12, with the labels that each got.

#5302 WFCORE-6145/WFCORE-6146 SocketBindingManager fixes wrt socket channels
  network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
  server/src/main/java/org/jboss/as/server/services/net/BindingRuntimeHandlers.java
Labels: ready-for-merge, deps-ok, 20.x

#5301 [WFCORE-6133] Remove deprecated Extension API members
  controller/src/main/java/org/jboss/as/controller/ExtensionContext.java
  controller/src/main/java/org/jboss/as/controller/SubsystemRegistration.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/transform/description/ChainedTransformationDescriptionBuilder.java
  controller/src/main/java/org/jboss/as/controller/transform/description/ChainedTransformationDescriptionBuilderImpl.java
  controller/src/main/java/org/jboss/as/controller/transform/description/TransformationDescription.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/NewExtension.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/map_to_child_resource/OldExtension.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/TransformerSubsystemTestCase.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtension2.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtensionCommon.java
  subsystem-test/tests/src/test/resources/META-INF/services/org.jboss.as.controller.transform.ExtensionTransformerRegistration
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/ExtensionSetup.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/extension/VersionedExtension2.java
Labels: ready-for-merge, deps-ok

#5286 [WFCORE-6130] Bootstrap Exceptions unchained
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/BootstrapListener.java
  server/src/main/java/org/jboss/as/server/ServerService.java
Labels: ready-for-merge, deps-ok

#5263 [WFCORE-6108] Add a new Phase constant to install global EJB client interceptors
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: ready-for-merge, deps-ok

#5303 WFCORE-6145/WFCORE-6146 SocketBindingManager fixes wrt socket channels
  network/src/main/java/org/jboss/as/network/SocketBindingManagerImpl.java
  server/src/main/java/org/jboss/as/server/services/net/BindingRuntimeHandlers.java
Labels: ready-for-merge, 19.x

#5309 [WFCORE-6152] Implement Support for MicroProfile Telemetry
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: ready-for-merge, deps-ok

#5311 [WFCORE-6141][WFCORE-6156][WFCORE-6157][WFCORE-6158] Server Stability Fixes
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  server/src/main/java/org/jboss/as/server/ExternalManagementRequestExecutor.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/OtherServicesSubsystemTestCase.java
Labels: ready-for-merge, deps-ok

#5319 [WFCORE-6169]: Disable YAML deserialization in the YAML Configuration Extension
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
Labels: ready-for-merge, deps-ok

#5320 [WFCORE-6169]: Disable YAML deserialization in the YAML Configuration Extension
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
Labels: ready-for-merge, 19.x

#5307 [WFCORE-6166] max-outbound-channels setting in remoting subsystem is not honored
  remoting/subsystem/src/main/java/org/jboss/as/remoting/EndpointService.java
Labels: deps-ok

#5312 [WFCORE-6160] Upgrade JBoss Remoting to 5.0.27.Final
  pom.xml
Labels: deps-ok

#5322 [19.x][WFCORE-6168] Write server configuration files using UTF-8 encoding a…
  controller/src/main/java/org/jboss/as/controller/persistence/AbstractConfigurationPersister.java
  controller/src/main/java/org/jboss/as/controller/persistence/UTF8XmlStringWriterDelegate.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/EncodingPersistenceTestCase.java
Labels: 19.x

#5315 [WFCORE-6099] Upgrade Byteman to 4.0.20
  pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
  testsuite/domain/src/test/resources/byteman-scripts/byteman.policy
Labels: ready-for-merge, 19.x

#5305 [WFCORE-6150] Remove deprecated CommonXml methods
  server/src/main/java/org/jboss/as/server/parsing/CommonXml.java
Labels: deps-ok

#5323 [WFCORE-6170] Update SNICombinedWithALPNTestCase to be compliant with…
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
Labels: ready-for-merge, deps-ok

#5326 [WFCORE-6174] Remove deprecated deployment plan builder methods
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/InitialDeploymentPlanBuilder.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/InitialDeploymentSetBuilder.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/domain/impl/InitialDeploymentSetBuilderImpl.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/DeploymentPlanBuilder.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/InitialDeploymentPlanBuilder.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/standalone/impl/DeploymentPlanBuilderImpl.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ExplodedDeploymentTestCase.java
Labels: deps-ok

#5329 WFCORE-6116 Remove deprecated Phase constants.
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: deps-ok

#5304 [WFCORE-2218] Ability to ask testrunner ServerController to wait for server process exit and get the exit code
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ShutdownRestartTestCase.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Labels: ready-for-merge, deps-ok

#5328 [WFCORE-6175] move the plexus-utils dependency to testbom and upgrade
  model-test/pom.xml
  pom.xml
  testbom/pom.xml
Labels: ready-for-merge, deps-ok

#5334 [19.x][WFCORE-6177] Remove test property added by EncodingPersistenceTestCase
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/EncodingPersistenceTestCase.java
Labels: ready-for-merge, 19.x

#5335 Fix WFCORE-6181, Upgrade to Galleon 5.0.7.Final, Galleon plugins 6.2.2.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5336 [WFCORE-6182] Await service container stability before KernelServices are provided
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Labels: ready-for-merge, deps-ok

#5337 [WFCORE-6183] Remove PersistentResourceDefinition.Parameters
  controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
Labels: ready-for-merge, deps-ok

#5289 [WFCORE-2209] Rework InterdependentDeploymentTestCase once special system prop enablement of WFCORE-2192 fix isn't needed
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/InterdependentDeploymentTestCase.java
Labels: ready-for-merge, deps-ok

#5333 [WFCORE-6180] Remove deprecated wildfly-embedded classes
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedManagedProcess.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedProcessStartException.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedServerReference.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/ServerEnvironment.java
  embedded/src/main/java/org/wildfly/core/embedded/ServerStartException.java
Labels: ready-for-merge, deps-ok

#5341 WFCORE-6185 Upgrade github actions to avoid github action warnings
  .github/workflows/dep-diff-pull_request.yml
  .github/workflows/dep-diff-workflow_run.yml
  .github/workflows/stale.yml
Labels: ready-for-merge, deps-ok

#5340 Keeping the actions up to date with Dependabot
  .github/dependabot.yml
Labels: ready-for-merge, deps-ok
