Repository wildfly/wildfly-core, pull requests merged in 2022-08, with the labels that each got.

#5162 [WFCORE-5945][WFCORE-5941][WFCORE-5976] WildFly OpenSSL Component Upgrades
  pom.xml
Labels: ready-for-merge, deps-ok

#5158 [WFCORE-5973] Update BufferPool to use Undertow's
  core-feature-pack/galleon-common/src/main/resources/feature_groups/io.xml
Labels: ready-for-merge, deps-ok

#5164 [WFCORE-5981] Upgrade WildFly OpenSSL to 2.2.5.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5166 [WFCORE-5984] Modify description in request controller subsystem to p…
  request-controller/src/main/resources/org/wildfly/extension/requestcontroller/LocalDescriptions.properties
Labels: ready-for-merge, deps-ok

#5144 [WFCORE-5960] Fix bug initializing Domain Base Dir for path Manager
  host-controller/src/main/java/org/jboss/as/host/controller/HostPathManagerService.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CoreResourceManagementTestCase.java
Labels: ready-for-merge, deps-ok

#5054 [WFCORE-5873] Add tests for WFCORE-5861 InaccessibleObjectException w…
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  core-feature-pack/galleon-common/src/main/resources/packages/tools/pm/wildfly/tasks.xml
  launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Environment.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/JbossCliClientJarJPMSSettingsTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/jpms/JPMSTestActivator.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessBuilder.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/cli/CliProcessWrapper.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/CustomCLIExecutor.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/JBossCliXmlConfigTestCase.java
Labels: ready-for-merge, deps-ok

#5156 WFCORE-5970 Server does not start when configuration file is a soft link to a file outside of the server configuration directory
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  controller/src/test/java/org/jboss/as/controller/persistence/PersistanceResourceTestCase.java
Labels: ready-for-merge, deps-ok

#5168 WFCORE-5983 JPMS properties test configuration not in sync with scrip…
  pom.xml
Labels: ready-for-merge, deps-ok

#5169 [WFCORE-6024]Upgrade Undertow to 2.2.19.Final
  pom.xml
Labels: deps-ok

#5170 [WFCORE-6024]Upgrade Undertow to 2.2.19.Final (fixes CVE-2022-1319, CVE-2022-2053)
  pom.xml
Labels: 18.x

#5172 WFCORE-4611 Complete AttributeDefinition.getImmutableFlags() -> getFlags() transition
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/AbstractWriteAttributeHandler.java
  controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/PersistentResourceDefinition.java
  controller/src/main/java/org/jboss/as/controller/registry/AttributeAccess.java
  controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java
Labels: deps-ok

#5177 [WFCORE-6030] Eliminating deprecated and unused CapabilityServiceTarget.addCapability(RuntimeCapability,Service) method
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: ready-for-merge, deps-ok

#5176 [WFCORE-6029] Eliminating deprecated and unused DeploymentPhaseContext.addDependency(ServiceName,Class,Injector) method
  server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java
Labels: ready-for-merge, deps-ok

#5167 [WFCORE-5986] Fixing StabilityMonitor usages in tests
  controller/src/test/java/org/jboss/as/controller/services/path/PathsTestCase.java
  domain-management/src/test/java/org/jboss/as/domain/management/security/util/ManagementControllerTestBase.java
  jmx/src/test/java/org/jboss/as/jmx/auditlog/JmxAuditLogHandlerTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
Labels: ready-for-merge, deps-ok

#5178 [WFCORE-5978] Mitigate issues getting the process exist code on AdminOnlyPolicyTestCase
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyPolicyTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainLifecycleUtil.java
Labels: deps-ok

#5179 [WFCORE-6032] Ignore AdminOnlyPolicyTestCase
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyPolicyTestCase.java
Labels: deps-ok

#5013 [WFCORE-5851] Null pointers should not be dereferenced (jmx)
  jmx/src/main/java/org/jboss/as/jmx/model/MBeanInfoFactory.java
Labels: ready-for-merge, deps-ok

#5181 [WFCORE-6033] Upgrade WildFly Elytron to 1.20.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5180 Yaml backport
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml
Labels: 18.x

#5130 [WFCORE-5931] Upgrade JBoss Remoting to 5.0.25.Final
  pom.xml
Labels: Stale, 18.x

#5165 [18.x][WFCORE-5916] Upgrade JBoss VFS to 3.2.17.Final
  pom.xml
Labels: 18.x

#5182 [18.x][WFCORE-5939] Upgrade WildFly Elytron to 1.19.1.Final
  pom.xml
Labels: 18.x

#5185 [WFCORE-5936] Ldap autentication using referrals fails on JDK 17 with…
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
Labels: 18.x
