Repository wildfly/wildfly-core, pull requests merged in 2022-05, with the labels that each got.

#5067 [WFCORE-5883] Remove wildfly-elytron-jwt from dependency management.
  pom.xml
Labels: ready-for-merge, deps-ok

#5083 [WFCORE-3407] Close log contexts created for deployments by adding a …
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemAdd.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingCleanupDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingConfigDeploymentProcessor.java
  logging/src/main/java/org/jboss/as/logging/logging/LoggingLogger.java
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: ready-for-merge, deps-ok

#5089 [WFCORE-5713] Migrate the WildFly Event Logger to use the internal JS…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/event/logger/main/module.xml
  event-logger/pom.xml
Labels: ready-for-merge, deps-ok

#5086 [18.x][WFCORE-5649] Assertion arguments should be passed correct (cli)
  cli/src/test/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProviderTestCase.java
  cli/src/test/java/org/jboss/as/cli/parsing/test/PropertyReplacementTestCase.java
  cli/src/test/java/org/jboss/as/cli/parsing/test/ValueTypeCompletionTestCase.java
  cli/src/test/java/org/jboss/as/cli/parsing/test/VariablesTestCase.java
Labels: ready-for-merge, 18.x

#5087 [WFCORE-5896] Remove AuthConfigFactory wrapping, this was used to co-exist with PicketBox.
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
Labels: ready-for-merge, deps-ok

#5091 [WFCORE-5890] There is a possible typo in Management Realm definition in default host.xml configuration
  core-feature-pack/galleon-common/src/main/resources/feature_groups/host-profile.xml
  testsuite/domain/src/test/resources/host-configs/host-master-elytron-no-legacy-realms.xml
  testsuite/domain/src/test/resources/host-configs/host-master-ssl-1way-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-master-ssl-2way-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-elytron-no-legacy-realms.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-ssl-1way-elytron.xml
  testsuite/domain/src/test/resources/host-configs/host-slave-ssl-2way-elytron.xml
  testsuite/domain/src/test/resources/host-configs/respawn-master-http.xml
  testsuite/domain/src/test/resources/host-configs/respawn-master.xml
Labels: ready-for-merge, deps-ok

#5070 [WFCORE-5320] ModelTestKernelServices providing BootErrorCollector info
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/boot/StandaloneBootErrorsTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServices.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Labels: ready-for-merge, deps-ok

#5094 [WFCORE-5904] Fix typo in some Handler filenames.
  controller/src/main/java/org/jboss/as/controller/audit/InMemoryAuditLogHandler.java
  controller/src/main/java/org/jboss/as/controller/audit/ManagedAuditLoggerImpl.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationDomainSlaveConfigHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationProviderWriteAttributeHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationUseIdentityRolesWriteAttributeHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/RoleIncludeAllWriteAttributeHandler.java
  domain-management/src/main/java/org/jboss/as/domain/management/access/RoleMappingResourceDefinition.java
  domain-management/src/main/java/org/jboss/as/domain/management/audit/InMemoryAuditLogHandlerResourceDefinition.java
Labels: ready-for-merge, deps-ok

#5096 WFCORE-5906 Expand set of utility methods for creating generic operations
  controller/src/main/java/org/jboss/as/controller/operations/common/Util.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ListOperations.java
  controller/src/main/java/org/jboss/as/controller/operations/global/MapOperations.java
  controller/src/test/java/org/jboss/as/controller/operations/common/UtilTest.java
Labels: ready-for-merge, deps-ok

#5099 [WFCORE-5909] Upgrade WildFly OpenSSL to 2.2.1.Final
  pom.xml
Labels: deps-ok

#5100 [18.x][WFCORE-5909] Upgrade WildFly OpenSSL to 2.2.1.Final
  pom.xml
Labels: 18.x

#5095 [WFCORE-5905] Don't reject EE 10 permissions.xml files
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
Labels: ready-for-merge, deps-ok

#5097 WFCORE-5907: fix runtime handling of secret-key-credential-store
  elytron/src/main/java/org/wildfly/extension/elytron/AbstractCredentialStoreResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/SecretKeyCredentialStoreDefinition.java
Labels: ready-for-merge, deps-ok

#5103 [WFCORE-5915] Upgrading to JBoss Modules 2.0.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5104 [WFCORE-5916] Upgrade JBoss VFS to 3.2.17.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5056 [WFCORE-5869] standalone.bat script does not parse JAVA_OPTS containing '|' symbol properly
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  testsuite/scripts/src/test/java/org/wildfly/common/test/ServerConfigurator.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
Labels: ready-for-merge, deps-ok

#5098 WFCORE-5841 [primary/secondary] Review the documentation of affected CLI management operations
  cli/src/main/resources/help/reload.txt
Labels: ready-for-merge, deps-ok

#5112 [WFCORE-5922] Ignore RemotingLegacySubsystemTestCase#testSubsystemWit…
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
Labels: ready-for-merge, deps-ok

#5107 WFCORE-5919 Duplicate Properties in mgmt-user
  testsuite/domain/src/test/resources/mgmt-users/mgmt-groups.properties
Labels: ready-for-merge, deps-ok

#5114 [WFCORE-5926] Upgrade to Byteman 4.0.19
  pom.xml
Labels: ready-for-merge, deps-ok

#5106 [WFCORE-5914] Elytron - key-size of secret-key-credential-store is not validated
  controller/src/main/java/org/jboss/as/controller/operations/validation/IntAllowedValuesValidator.java
  elytron/src/main/java/org/wildfly/extension/elytron/SecretKeyCredentialStoreDefinition.java
Labels: ready-for-merge, deps-ok

#5111 Fix for WFCORE-5911, Upgrade to Galleon 5.0.1.Final and Galleon plugins 6.0.0.Alpha2
  pom.xml
Labels: ready-for-merge, deps-ok

#5109 [WFCORE-5920] fix inconsistency in JDK17 JAVA_OPTS from domain.bat an…
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
Labels: ready-for-merge, deps-ok
