Repository wildfly/wildfly-core, pull requests merged in 2023-10, with the labels that each got.

#5689 [WFCORE-6524] Do not duplicate managed deployment in content repository in tmp/vfs/temp directory
  server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestClassPathProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/deployment/DeploymentDuplicationTestCase.java
Labels: ready-for-merge, deps-ok

#5695 Fix license headers introduced by WFCORE-6472
  remoting/subsystem/src/main/java/org/jboss/as/remoting/InsecureOutboundConnection.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemModel.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemSchema.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformerTestCase.java
Labels: ready-for-merge, deps-ok

#5696 [WFCORE-6528] Upgrading JBoss MSC to 1.5.2.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5697 [WFCORE-6516] Upgrading JBoss Marshalling to 2.1.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5672 WFCORE-6505 Avoid creating duplicate thread groups on server reload
  cli/src/main/java/org/jboss/as/cli/gui/JConsoleCLIPlugin.java
  controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerAdd.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
  host-controller/src/main/java/org/jboss/as/host/controller/ProcessControllerConnectionService.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/ServerToHostOperationHandlerFactoryService.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentMountProvider.java
  server/src/main/java/org/jboss/as/server/deployment/module/TempFileProviderService.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainControllerClientConfig.java
  threads/src/main/java/org/jboss/as/threads/ThreadFactoryService.java
Labels: ready-for-merge, deps-ok

#5415 [WFCORE-4916] Unclear attribute name completion for LIST type
  cli/src/main/java/org/jboss/as/cli/impl/AttributeNamePathCompleter.java
  cli/src/main/java/org/jboss/as/cli/operation/OperationRequestCompleter.java
  cli/src/main/java/org/jboss/as/cli/operation/impl/DefaultOperationCandidatesProvider.java
  cli/src/test/java/org/jboss/as/cli/parsing/test/AttributeNamePathCompletionTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
Labels: ready-for-merge, deps-ok

#5702 Fix for WFCORE-6486, CLIEmbedHostControllerTestCase fails randomly with JDK 17 Jobs
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
Labels: ready-for-merge, deps-ok, 22.x

#5703 [WFCORE-6544] CVE-2023-4061 Management RBAC permission allows unexpected reading of system-properties via resolve-expression
  controller/src/main/java/org/jboss/as/controller/access/constraint/SensitivityClassification.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ResolveExpressionHandler.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ResolveExpressionTestCase.java
Labels: Blocker, deps-ok, 22.x

#5659 [WFCORE-6383] throwing boot errors if super.boot fails
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/BootErrorCollector.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/deployment/StandaloneDeploymentUnicityTestCase.java
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/servergroup/DomainServerGroupTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTestCase.java
Labels: hold, deps-ok, 22.x

#5709 [WFCORE-6552] Add missing search for WARNING to Windows package avail…
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
Labels: deps-ok

#5708 [WFCORE-6551] Upgrade XNIO to 3.8.11.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5704 [WFCORE-6547] Upgrading JBoss Marshalling to 2.1.3.SP1
  pom.xml
Labels: ready-for-merge, deps-changed, 23.x

#5688 [WFCORE-6527]: Upgrade JGit from 6.6.0.202305301015-r to 6.7.0.202309050840-r
  pom.xml
Labels: ready-for-merge, deps-ok, 23.x

#5710 [WFCORE-6555] CVE-2023-3223 Upgrade Undertow to 2.3.9.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5711 [WFCORE-6556] Fixing JDK11 illegal access warnings in Elytron tests
  elytron/pom.xml
Labels: ready-for-merge, deps-ok

#5700 [WFCORE-6542]: Upgrade the Windows service tools.
  core-feature-pack/common/assembly.xml
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/amd64/wildfly-service.exe
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/wildfly-mgr.exe
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/wildfly-service.exe
  core-feature-pack/galleon-feature-pack/pom.xml
  pom.xml
Labels: ready-for-merge, deps-changed, 23.x

#5705 [WFCORE-6548] Unify test logging in elytron module
  elytron/src/test/resources/logging.properties
Labels: ready-for-merge, deps-ok

#5713 [WFCORE-6552] Add missing search for WARNING to Windows package avail…
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
Labels: ready-for-merge, 22.x

#5715 [22.x][WFCORE-6557] CVE-2023-44487 Upgrade Netty to 4.1.100.Final
  pom.xml
Labels: ready-for-merge, 22.x

#5716 [WFCORE-6538] ClosedChannelException is thrown intermittently instead of SaslException when using GS2_KRB5 with TLS
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
Labels: ready-for-merge, deps-ok

#5720 [22.x][WFCORE-6551] Upgrade XNIO to 3.8.11.Final
  pom.xml
Labels: 22.x

#5701 [WFCORE-6541] Patch high level command should be completely disabled …
  patching/src/main/java/org/jboss/as/patching/cli/PatchApply.java
  patching/src/main/java/org/jboss/as/patching/cli/PatchCommand.java
  patching/src/main/java/org/jboss/as/patching/cli/PatchHistory.java
  patching/src/main/java/org/jboss/as/patching/cli/PatchInfo.java
  patching/src/main/java/org/jboss/as/patching/cli/PatchInspect.java
  patching/src/main/java/org/jboss/as/patching/cli/PatchRollbackActivator.java
  patching/src/main/resources/org/jboss/as/patching/cli/command_resources.properties
  patching/src/test/java/org/jboss/as/patching/cli/CLIPatchInfoUtil.java
  patching/src/test/java/org/jboss/as/patching/cli/ContentConflictsUnitTestCase.java
  patching/src/test/java/org/jboss/as/patching/cli/LocalPatchInfoPatchIdUnitTestCase.java
  patching/src/test/java/org/jboss/as/patching/cli/PatchInspectUnitTestCase.java
  patching/src/test/java/org/jboss/as/patching/cli/ResetConfigurationUnitTestCase.java
  patching/src/test/java/org/jboss/as/patching/cli/RollbackLastUnitTestCase.java
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CliCompletionTestCase.java
  testsuite/standalone/pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliCompletionTestCase.java
Labels: ready-for-merge, deps-ok, 23.x

#5719 [22.x][WFCORE-6555] CVE-2023-3223 Upgrade Undertow to 2.3.9.Final
  pom.xml
Labels: ready-for-merge, 22.x

#5712 [22.x][WFCORE-6547] Upgrading JBoss Marshalling to 2.1.3.SP1
  pom.xml
Labels: ready-for-merge, hold, 22.x

#5706 [WFCORE-6532] Add security manager to script tests
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
Labels: ready-for-merge, deps-ok

#5726 [WFCORE-6564] Upgrade Undertow to 2.3.10.Final (CVE-2023-44487)
  pom.xml
Labels: deps-ok

#5727 [WFCORE-6564] Upgrade Undertow to 2.3.10.Final (CVE-2023-44487)
  pom.xml
Labels: Blocker, 22.x

#5730 [WFCORE-6567] Upgrade Installation Manager API to 1.0.2.Final
  pom.xml
  testsuite/shared/src/main/java/org/wildfly/test/installationmanager/TestInstallationManager.java
Labels: deps-ok

#5734 [WFCORE-6572] Upgrade XNIO to 3.8.12.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5733 [WFCORE-6476-fix]: Reducing logging level for failed internal read-on…
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
Labels: ready-for-merge, deps-ok

#5725 [WFCORE-6562] Upgrade Galleon to 5.2.1.Final and Galleon plugins to 6…
  pom.xml
Labels: ready-for-merge, deps-ok

#5729 [WFCORE-6568] - Modify description in elytron subsystem
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
Labels: ready-for-merge, deps-ok

#5721 [WFCORE-6559] Allow Remove-Item command to delete directories with lo…
  core-feature-pack/common/src/main/resources/content/bin/installation-manager.ps1
Labels: deps-ok

#5741 [WFCORE-6574] Upgrade JBoss Parent to 40
  core-feature-pack/common/pom.xml
  core-feature-pack/galleon-feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#5740 [WFCORE-6563] remove obsolete pre-Galleon WildFly build and provisioning tools
  pom.xml
Labels: ready-for-merge, deps-ok

#5745 [WFCORE-6573][WFCORE-6575] Json upgrades
  pom.xml
Labels: deps-ok

#5735 [WFCORE-6445] Update ModuleSpecification.getMutableUserDependencies
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
Labels: ready-for-merge, deps-ok
