Repository wildfly/wildfly-core, pull requests merged in 2023-06, with the labels that each got.

#5534 [WFCORE-6373] Upgrade WildFly Elytron EE to 3.0.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5531 [WFCORE-6368] Upgrading JBoss MSC to 1.5.1.Final
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  pom.xml
Labels: ready-for-merge, deps-ok

#5536 [WFCORE-6382] Have OperationContext impls clean up internal state at …
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationStepHandler.java
  controller/src/main/java/org/jboss/as/controller/transform/ContextAttachments.java
Labels: ready-for-merge, deps-ok

#5478 WFCORE-6328 Add AbstractSubsystemTest subclass for use with tests parameterized via SubsystemSchema
  discovery/src/test/java/org/wildfly/extension/discovery/DiscoverySubsystemTestCase.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AbstractSubsystemSchemaTest.java
Labels: ready-for-merge, deps-ok

#5539 [WFCORE-6286] Document the purpose of the wildflyee.api module in its…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
Labels: ready-for-merge, deps-ok

#5529 [WFCORE-6370] Remove duplicate jakarta.xml.ws.api module declaration …
  core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
Labels: ready-for-merge, deps-ok

#5540 [WFCORE-6386][WFCORE-6380][WFCORE-6381] Reduce peak memory use during recursive read-resource operations
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/CompositeOperationHandler.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadAttributeHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractGlobalOperationsTestCase.java
Labels: deps-ok

#5533 [WFCORE-6379] Upgrade Jakarta JSON Processing to 2.1.1 and Eclipse Pa…
  pom.xml
Labels: ready-for-merge, deps-ok

#5542 [WFCORE-6386] Ensure that read-only op handlers that incorrectly do w…
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
Labels: ready-for-merge, deps-ok

#5545 [WFCORE-6392] Eliminating deprecated and unused CapabilityServiceBuilder.addCapabilityRequirement() methods
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: ready-for-merge, deps-ok

#5544 [WFCORE-6390] Removing the victims-scan profile
  pom.xml
Labels: ready-for-merge, deps-ok

#5514 WFCORE-6361 Replace VersionedURN subclasses with factory methods
  controller/src/main/java/org/jboss/as/controller/LegacySubsystemURN.java
  controller/src/main/java/org/jboss/as/controller/SubsystemSchema.java
  controller/src/main/java/org/jboss/as/controller/SubsystemURN.java
  controller/src/main/java/org/jboss/as/controller/xml/IntVersionSchema.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedNamespace.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedSchema.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedURN.java
  controller/src/main/java/org/jboss/as/controller/xml/XMLAttributeSchema.java
  controller/src/main/java/org/jboss/as/controller/xml/XMLElementSchema.java
  controller/src/test/java/org/jboss/as/controller/xml/VersionedNamespaceTestCase.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemSchema.java
  server/src/main/java/org/jboss/as/server/deployment/jbossallxml/JBossAllSchema.java
Labels: ready-for-merge, deps-ok

#5543 WFCORE-6391: correct declared licenses
  core-feature-pack/common/src/main/resources/content/docs/licenses/bsd 3-clause new or revised license.html
  core-feature-pack/common/src/main/resources/content/docs/licenses/common development and distribution license 1.1.txt
  core-feature-pack/common/src/main/resources/content/docs/licenses/creative commons attribution 2.5.html
  core-feature-pack/common/src/main/resources/content/docs/licenses/eclipse public license 1.0.txt
  core-feature-pack/common/src/main/resources/content/docs/licenses/gnu general public license v2.0 only.html
  core-feature-pack/common/src/main/resources/content/docs/licenses/gnu general public license, version 2 with the classpath exception.txt
  core-feature-pack/common/src/main/resources/content/docs/licenses/public domain.txt
  core-feature-pack/common/src/main/resources/content/docs/licenses/the bsd license.txt
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/galleon-common/src/main/resources/packages/docs.licenses/content/docs/licenses/licenses.xsl
Labels: ready-for-merge, deps-ok

#5537 [WFCORE-6384] When shuting down to perform an installation CLI is dis…
  cli/src/main/java/org/jboss/as/cli/CommandLineMain.java
  cli/src/main/java/org/jboss/as/cli/Util.java
  cli/src/main/java/org/jboss/as/cli/handlers/ShutdownHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HostShutdownHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerShutdownHandler.java
Labels: ready-for-merge, deps-ok

#5549 Revert "[WFCORE-6386] Ensure that read-only op handlers that incorrectly do w…"
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
Labels: deps-ok

#5550 [WFCORE-6384] Do not initialize the logger before the log manager is …
  cli/src/main/java/org/jboss/as/cli/CommandLineMain.java
Labels: ready-for-merge, deps-ok

#5551 [WFCORE-6403] Upgrade WildFly Elytron to 2.2.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5552 [WFCORE-3792] Make the org.jboss.remoting and org.jboss.xnio modules …
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/remoting/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/xnio/main/module.xml
Labels: deps-ok

#5554 Revert "Revert "[WFCORE-6386] Ensure that read-only op handlers that incorrectly do w…""
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
Labels: ready-for-merge, deps-ok

#5553 [WFCORE-6395] Clean up Operation Context only for server processes
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: deps-ok

#5557 [WFCORE-6405] Make the org.wildfly.extension.elytron module private
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/main/module.xml
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
Labels: deps-ok

#5556 [WFCORE-6313] fixed the package name of NativeManagementRemoveHandler…
  host-controller/src/main/java/org/jboss/as/host/controller/resources/NativeManagementResourceDefinition.java
Labels: ready-for-merge, deps-ok

#5250 [WFCORE-6096] ModelTestModelControllerService does not set error when init capabilities are missing
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
Labels: ready-for-merge, deps-ok

#5559 [WFCORE-6409] Make org.jboss.marshalling module private
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml
Labels: deps-ok

#5558 [WFCORE-6408] Introducing new DEPENDENCIES_JDBC_DRIVER phase
  server/src/main/java/org/jboss/as/server/deployment/Phase.java
Labels: ready-for-merge, deps-ok

#5560 [WFCORE-6412]: Update JGit to 6.6.0.202305301015-r
  pom.xml
Labels: ready-for-merge, deps-ok

#5562 [WFCORE-6413] Upgrade JBoss VFS to 3.3.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5565 [WFCORE-6305] Upgrade to Jandex 3.1.1
  pom.xml
Labels: deps-ok

#5566 [WFCORE-6414] Upgrade bouncycastle from 1.73 to 1.75
  pom.xml
Labels: deps-ok

#5568 [WFCORE-6417] Upgrade Jandex to 3.1.2
  pom.xml
Labels: ready-for-merge

#5353 [WFCORE-6154] Log reasons for implicit module dependencies
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependency.java
Labels: ready-for-merge, deps-ok, 21.x
