Repository wildfly/wildfly-core, pull requests merged in 2023-12, with the labels that each got.

#5777 [WFCORE-6612][WFCORE-6613][WFCORE-6614][WFCORE-6615] Allow use of WildFly Channels when running the testsuite
  core-feature-pack/channel/pom.xml
  core-feature-pack/channel/src/main/resources/wildfly-core-channel.yaml
  core-feature-pack/galleon-feature-pack/pom.xml
  core-feature-pack/manifest/assembly.xml
  core-feature-pack/manifest/pom.xml
  core-feature-pack/pom.xml
  dist/pom.xml
  pom.xml
  testsuite/client-old-server/pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/embedded/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/provisioning/ProvisioningConsistencyTestCase.java
  testsuite/pom.xml
  testsuite/rbac/pom.xml
  testsuite/scripts/pom.xml
  testsuite/standalone/pom.xml
  testsuite/standalone/src/test/resources/fp-config.xml
Labels: deps-ok

#5785 [WFCORE-6636] Upgrade log42-jboss-logmanager to 1.1.2.Final.
  pom.xml
Labels: ready-for-merge, deps-ok

#5790 [WFCORE-6638] Local variables referenced from a lambda expression must be final or effectively final
  controller/src/main/java/org/jboss/as/controller/SecurityActions.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolOperationHandler.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DefaultDeploymentOperations.java
  host-controller/src/main/java/org/jboss/as/host/controller/SecurityActions.java
  server/src/main/java/org/jboss/as/server/deployment/ContentRepositoryCleaner.java
  server/src/main/java/org/jboss/as/server/mgmt/domain/HostControllerClient.java
Labels: ready-for-merge, deps-ok

#5788 [WFCORE-6637] Upgrade commons-lang3 from 3.13.0 to 3.14.0
  pom.xml
Labels: ready-for-merge, deps-ok

#5413 WFCORE-6221 Add formal experimental/preview mode to management model
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
  controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironmentWrapper.java
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostInfo.java
  process-controller/src/main/java/org/jboss/as/process/CommandLineArgumentUsageImpl.java
  process-controller/src/main/java/org/jboss/as/process/Main.java
  server/src/main/java/org/jboss/as/server/CommandLineArgumentUsageImpl.java
  server/src/main/java/org/jboss/as/server/Main.java
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  version/src/main/java/org/jboss/as/version/ProductConfig.java
Labels: Feature, deps-ok

#5795 [WFCORE-6642] Remove obsolete eap-repo profile in test
  model-test/src/test/resources/org/jboss/as/model/test/settings-empty-local-repo.xml
Labels: ready-for-merge, deps-ok

#5789 [WFCORE-6579] Allow process controller log file capture initial manag…
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
  process-controller/src/main/java/org/jboss/as/process/CommandLineConstants.java
  process-controller/src/main/java/org/jboss/as/process/ManagedProcess.java
  process-controller/src/main/java/org/jboss/as/process/ProcessController.java
  server/src/main/java/org/jboss/as/server/DomainServerMain.java
Labels: ready-for-merge, deps-ok

#5800 [WFCORE-6644] Upgrade log4j2 from 2.19.0 to 2.22.0
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/profiles/Log4j2LoggingProfilesTestCase.java
Labels: ready-for-merge, deps-ok

#5798 [WFCORE-6643] Upgrade JGit from 6.7.0.202309050840-r to 6.8.0.2023112…
  pom.xml
Labels: ready-for-merge, deps-ok

#5806 WFCORE-6347 Drop redundant getCapabity() method.
  subsystem/src/main/java/org/wildfly/subsystem/resource/capability/RuntimeCapabilityProvider.java
Labels: deps-ok

#5809 WFCORE-6347 Add convenience method for generating a composite ResourceServiceConfigurator.
  subsystem/src/main/java/org/wildfly/subsystem/service/ResourceServiceConfigurator.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ResourceServiceInstaller.java
Labels: deps-ok

#5808 WFCORE-6651 Update generic Extension implemention in wildfly-subsystem to only register parsers for schemas enabled by the current stability level.
  controller/src/main/java/org/jboss/as/controller/FeatureRegistry.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
  subsystem/src/main/java/org/wildfly/subsystem/SubsystemConfiguration.java
  subsystem/src/main/java/org/wildfly/subsystem/SubsystemExtension.java
  subsystem/src/main/java/org/wildfly/subsystem/SubsystemPersistence.java
Labels: deps-ok

#5811 WFCORE-6347 Consolidate ResourceServiceValueRegistry and ServiceValueRegistry
  subsystem/src/main/java/org/wildfly/subsystem/service/capture/ResourceServiceValueExecutorRegistry.java
  subsystem/src/main/java/org/wildfly/subsystem/service/capture/ResourceServiceValueRegistry.java
  subsystem/src/main/java/org/wildfly/subsystem/service/capture/ServiceValueRegistry.java
Labels: ready-for-merge, deps-ok

#5813 WFCORE-6347 Create better distinction between start task, and service value captor.
  service/src/main/java/org/wildfly/service/Installer.java
  service/src/test/java/org/wildfly/service/DefaultServiceInstallerTestCase.java
  service/src/test/java/org/wildfly/service/DefaultServiceTestCase.java
Labels: deps-ok

#5816 WFCORE-6347 Replace separate defaultable service descriptor interfaces with static factory methods.
  discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderServiceConfigurator.java
  service/src/main/java/org/wildfly/service/ChildTargetService.java
  service/src/main/java/org/wildfly/service/Installer.java
  service/src/main/java/org/wildfly/service/ServiceInstaller.java
  service/src/main/java/org/wildfly/service/descriptor/BinaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/DefaultableBinaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/DefaultableQuaternaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/DefaultableServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/DefaultableTernaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/DefaultableUnaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/QuaternaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/TernaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/UnaryServiceDescriptor.java
  service/src/test/java/org/wildfly/service/ChildTargetServiceTestCase.java
  service/src/test/java/org/wildfly/service/DefaultServiceInstallerTestCase.java
  service/src/test/java/org/wildfly/service/descriptor/DefaultServiceDescriptorTestCase.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
  subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java
Labels: deps-ok
