Repository wildfly/wildfly-core, pull requests merged in 2023-02, with the labels that each got.

#5369 WFCORE-6218 Add Stream variant to PersistentResourceXMLDescription.PersistentResourceXMLBuilder
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
Labels: ready-for-merge, deps-ok

#5331 [WFCORE-6178] Upgrading JBoss MSC to 1.5.0.Beta5
  pom.xml
Labels: ready-for-merge, deps-ok

#5339 Adding CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: ready-for-merge, deps-ok

#5368 [WFCORE-5846][primary/secondary] Adapt S3Discovery mechanism to new l…
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/DomainControllerData.java
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/S3Discovery.java
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/S3Util.java
Labels: ready-for-merge, deps-ok

#5370 [WFCORE-5605] Remove the prompt for checking if this is a server to server process.
  domain-management/src/main/java/org/jboss/as/domain/management/logging/DomainManagementLogger.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/AddUser.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/AddUserState.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/DisplaySecret.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/StateValues.java
  domain-management/src/main/java/org/jboss/as/domain/management/security/adduser/UpdateUser.java
Labels: ready-for-merge, deps-ok

#5374 [WFCORE-6217] Upgrade Undertow to 2.3.4.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5373 [WFCORE-6226] Dropping tests for TransformerSubsystemTestCase using deprecated ModelTestControllerVersion and creating test case against EAP_7_4_0
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/TransformerSubsystemTestCase.java
Labels: ready-for-merge, deps-ok

#5375 Fix for WFCORE-6228, Upgrade galleon-plugins to 6.3.0.Final
  core-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#5366 [WFCORE-6214] Fixed Flaky Tests in HelpSupportTestCase.testStandalone and BootScriptInvokerTestCase
  cli/src/main/java/org/jboss/as/cli/impl/aesh/SynopsisGenerator.java
  cli/src/test/java/org/jboss/as/cli/impl/BootScriptInvokerTestCase.java
Labels: ready-for-merge, deps-ok

#5380 [WFCORE-6232] Eliminating ModuleSpecification deprecated methods
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
Labels: ready-for-merge, deps-ok

#5378 [WFCORE-5557] Remove setAllowNull deprecated API
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
Labels: ready-for-merge, deps-ok

#5381 [WFCORE-6233] Upgrading JBoss MSC to 1.5.0.CR1
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  pom.xml
Labels: ready-for-merge

#5382 [WFCORE-6234] Eliminating deprecated DeploymentUnit methods
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnit.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitImpl.java
Labels: ready-for-merge, deps-ok

#5385 [WFCORE-6238] Eliminating dead code in org.jboss.as.cli.impl.SecurityActions class
  cli/src/main/java/org/jboss/as/cli/impl/SecurityActions.java
Labels: ready-for-merge, deps-ok

#5388 [WFCORE-6243] Upgrade WildFly Elytron to 2.1.0.Final
  core-feature-pack/common/pom.xml
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
  pom.xml
  testsuite/elytron/pom.xml
Labels: ready-for-merge, deps-changed

#5387 [WFCORE-6240] Upgrade Bouncycastle OpenPGP from 1.72.1 to 1.72.2
  pom.xml
Labels: ready-for-merge, deps-ok

#5384 [WFCORE-6237] Eliminating usage of deprecated javax.api aggregation module
  core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
  core-feature-pack/ee-10-api/src/main/resources/modules/system/layers/base/jakarta/security/auth/message/api/main/module.xml
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/shared/src/main/resources/jmx-listener-module.xml
  testsuite/shared/src/main/resources/org/jboss/as/test/integration/management/extension/dependent/module.xml
  testsuite/shared/src/main/resources/org/wildfly/test/jmx/events/module.xml
  testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/booterror/module.xml
  testsuite/standalone/src/test/resources/org/wildfly/core/test/standalone/extension/remove/module.xml
Labels: ready-for-merge, deps-ok

#5383 [WFCORE-6236]: Revert "[WFCORE-5343]: Disabling the feature"
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/dir/.gitkeep
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/controller/main/dir/META-INF/services/org.jboss.as.controller.persistence.ConfigurationExtension
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml
Labels: ready-for-merge, deps-ok
