Repository wildfly/wildfly-core, pull requests merged in 2023-05, with the labels that each got.

#5491 [WFCORE-6342] The jmx-remoting dependeny on management needs to be mandatory.
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/jmx-remoting/layer-spec.xml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5488 WFCORE-6336 Remove deprecated OperationDefinition and SimpleOperationDefinition API
  controller/src/main/java/org/jboss/as/controller/OperationDefinition.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5487 [WFCORE-6330] Make deprecated MountHandler constructor private and undeprecate it
  server/src/main/java/org/jboss/as/server/deployment/module/MountHandle.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5486 [WFCORE-6337] Remove deprecated PersistentResourceXmlDescription API;…
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5483 [WFCORE-6333] Remove deprecated Path resource API elements
  controller/src/main/java/org/jboss/as/controller/services/path/PathAddHandler.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathRemoveHandler.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathResourceDefinition.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5492 [WFCORE-6344] Ensure structured formatters are correctly configured i…
  logging/src/main/java/org/jboss/as/logging/formatters/StructuredFormatterResourceDefinition.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5476 [20.x][WFCORE-6326] Revert the removal of the org.jboss.vfs module on deplo…
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
Labels: ready-for-merge, Blocker, 20.x

#5493 [20.x][WFCORE-6344] Ensure structured formatters are correctly configured i…
  logging/src/main/java/org/jboss/as/logging/formatters/StructuredFormatterResourceDefinition.java
Labels: ready-for-merge, 20.x

#5489 [WFCORE-6338]: A resource name can't match an attribute name of this resource.
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5443 [WFCORE-6290] Failure to handle errors loading process-uuid file
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5479 [WFCORE-6329] Remove deprecated ServerEnvironment API
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/ServerEnvironmentResourceDescription.java
  server/src/main/java/org/jboss/as/server/ServerStartTask.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5490 WFCORE-6331 Remove deprecated ProductConfig constructor
  testsuite/patching/src/test/java/org/jboss/as/test/patching/ProductInfo.java
  version/src/main/java/org/jboss/as/version/ProductConfig.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5495 [WFCORE-6345] Add missing JavaDoc and ensure the --yaml argument is a…
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
Labels: deps-ok

#5498 [WFCORE-6346] Module java.base must open java.net package to all unnamed modules
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5500 [WFCORE-6346] Module java.base must open java.net package to all unnamed modules
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
Labels: ready-for-merge, 20.x

#5484 [WFCORE-6334] Remove deprecated management model test framework API
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/LegacyKernelServicesImpl.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/MainKernelServicesImpl.java
  jmx/src/test/java/org/jboss/as/jmx/PluggableMBeanServerTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServices.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/bridge/impl/LegacyControllerKernelServicesProxy.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/AdditionalInitialization.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/KernelServices.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/KernelServicesBuilder.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/LegacyKernelServicesImpl.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/MainKernelServicesImpl.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TransformerAttachmentGrabber.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5507 [WFCORE-6302] CVE-2022-1259 Upgrade Undertow to 2.3.6.Final
  pom.xml
Labels: ready-for-merge, Blocker, deps-ok, 21.0.0.Beta1

#5508 [20.x][WFCORE-6302] CVE-2022-1259 Upgrade Undertow to 2.3.6.Final
  pom.xml
Labels: ready-for-merge, Blocker, 20.x

#5504 [WFCORE-6320] Remove deprecated ModelController methods
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/ModelController.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/test/java/org/jboss/as/controller/MetricsRegistrationTestCase.java
  controller/src/test/java/org/jboss/as/controller/MetricsUndefinedValueUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/MockModelController.java
  controller/src/test/java/org/jboss/as/controller/ModelControllerClientTestCase.java
  controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/OperationTimeoutUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/TestModelControllerService.java
  controller/src/test/java/org/jboss/as/controller/notification/GlobalNotificationsTestCase.java
  controller/src/test/java/org/jboss/as/controller/notification/NotificationCompositeOperationTestCase.java
  controller/src/test/java/org/jboss/as/controller/notification/OperationWithManyStepsTestCase.java
  controller/src/test/java/org/jboss/as/controller/notification/OperationWithNotificationTestCase.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractControllerTestBase.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServicesImpl.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
  platform-mbean/src/test/java/org/jboss/as/platform/mbean/PlatformMBeanResourceUnitTestCase.java
  platform-mbean/src/test/java/org/jboss/as/platform/mbean/PlatformMBeanTestModelControllerService.java
  server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5506 WFCORE-6354 Remove obsolete org.jboss.msc dependency from org.jboss.as.network
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/network/main/module.xml
  network/pom.xml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5505 [WFCORE-6339]: Define remote name as origin if none is defined.
  server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
  server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5494 [WFCORE-6341]: YAML: MapAttributeDefinition not properly processed for existing resources.
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple.yml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5513 [WFCORE-6360] Remove deprecated ManagementResourceRegistration relate…
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/registry/AliasEntry.java
  controller/src/main/java/org/jboss/as/controller/registry/AliasResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/ManagementResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/ProxyControllerRegistration.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5518 [WFCORE-6364][WFCORE-6363] WildFly Elytron component upgrades
  pom.xml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5502 [WFCORE-6348]: Invalid YAML configuration fails silently.
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_child.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_child_error.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/simple_error.yml
Labels: ready-for-merge, deps-ok, affects_i18n, 21.0.0.Beta1

#5510 [WFCORE-6357] Remove deprecated AttributeDefinition API
  controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/AttributeParser.java
  controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
  controller/src/main/java/org/jboss/as/controller/DefaultAttributeMarshaller.java
  controller/src/main/java/org/jboss/as/controller/ListAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/ObjectTypeAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/PropertiesAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/SimpleAttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/operations/global/XMLReportAttacher.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathAddHandler.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathRemoveHandler.java
  controller/src/test/java/org/jboss/as/controller/InterleavedSubsystemTestCase.java
  controller/src/test/java/org/jboss/as/controller/RemoveNonExistingResourceTestCase.java
  controller/src/test/java/org/jboss/as/controller/persistence/PersistentResourceXMLParserTestCase.java
  controller/src/test/java/org/jboss/as/controller/registry/ExtendWildCardRegistrationUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/test/AliasResourceTestCase.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerParser_1_1.java
  deployment-scanner/src/main/java/org/jboss/as/server/deployment/scanner/DeploymentScannerParser_2_0.java
  domain-management/src/main/java/org/jboss/as/domain/management/parsing/AccessControlXml.java
  elytron/src/main/java/org/wildfly/extension/elytron/AdvancedModifiableKeyStoreDecorator.java
  elytron/src/main/java/org/wildfly/extension/elytron/CertificateAuthorityAccountDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/FileSystemRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmAttributes.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_16.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_4.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_5.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_Legacy.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_10.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_11.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_18.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_20.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_4.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_5.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_6.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_Legacy.java
  logging/src/main/java/org/jboss/as/logging/LoggingSubsystemWriter.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystem11Parser.java
  server/src/main/java/org/jboss/as/server/controller/resources/CapabilityRegistryResourceDefinition.java
  server/src/main/java/org/jboss/as/server/parsing/CommonXml.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_11.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_18.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_4.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_5.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_6.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_Legacy.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5509 [WFCORE-6352] Add the ability to secure the management interface using a virtual HTTP authentication factory if available
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/security/AdvancedSecurityMetaData.java
  server/src/main/java/org/jboss/as/server/security/SecurityMetaData.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainMarkerUtility.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainUtil.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5503 [WFCORE-6351] The publish-configuration command doesn't throw an error when the git location is invalid
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  server/src/main/java/org/jboss/as/server/controller/git/GitConfigurationPersister.java
  server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/GitRepositoryTestCase.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5528 [WFCORE-6365] RestartParent OperationStepHandler implementations are incompatible with service built via CapabilityServiceTarget
  controller/src/main/java/org/jboss/as/controller/RestartParentResourceAddHandler.java
  controller/src/main/java/org/jboss/as/controller/RestartParentResourceHandlerBase.java
  controller/src/main/java/org/jboss/as/controller/RestartParentResourceRemoveHandler.java
Labels: deps-ok
