Repository wildfly/wildfly-core, pull requests merged in 2023-03, with the labels that each got.

#5396 Fix for WFCORE-6252, Upgrade Galleon to 5.0.8.Final and galleon Plugins to 6.3.2.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5394 [WFCORE-6251] Use standard java.xml JPMS module instead of deprecated javax.xml.stream.api
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/security-module.xml
Labels: ready-for-merge, deps-ok

#5395 [WFCORE-6250] Don't include org.jboss.vfs module to all deployments by default
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
Labels: ready-for-merge, deps-ok

#5113 [WFCORE-785] Improving capability related error messages
  controller/src/main/java/org/jboss/as/controller/CapabilityRegistry.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Labels: deps-ok, 21.x

#5398 [WFCORE-6254] Eliminating deprecated CapabilityServiceBuilder.addCapabilityRequirement(String,Class) method
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
Labels: ready-for-merge, deps-ok

#5392 [WFCORE-6246] Upgrade snakeyaml from 1.33 to 2.0
  pom.xml
Labels: ready-for-merge, deps-changed

#5390 [WFCORE-6241] Adding 'quickly' profile for fast maven builds with quick profile
  pom.xml
  testsuite/scripts/pom.xml
Labels: ready-for-merge, deps-ok

#5400 WFCORE-6256 Upgrade staxmapper to 1.4.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5355 [WFCORE-6202] Don't set `-server` option for IBM i
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.bat
  core-feature-pack/common/src/main/resources/content/bin/domain.ps1
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.bat
  core-feature-pack/common/src/main/resources/content/bin/standalone.ps1
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
Labels: ready-for-merge, deps-ok

#5405 [WFCORE-6260] TestModule should check the path in consistent manner
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/TestModule.java
Labels: ready-for-merge, deps-ok

#5401 WFCORE-6257 Refactor Schema related interfaces from wildfly-clustering-common into wildfly-controller
  controller/src/main/java/org/jboss/as/controller/LegacySubsystemURN.java
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescription.java
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescriptionReader.java
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLDescriptionWriter.java
  controller/src/main/java/org/jboss/as/controller/PersistentResourceXMLParser.java
  controller/src/main/java/org/jboss/as/controller/PersistentSubsystemSchema.java
  controller/src/main/java/org/jboss/as/controller/SubsystemSchema.java
  controller/src/main/java/org/jboss/as/controller/SubsystemURN.java
  controller/src/main/java/org/jboss/as/controller/xml/Schema.java
  controller/src/main/java/org/jboss/as/controller/xml/SimpleNamespace.java
  controller/src/main/java/org/jboss/as/controller/xml/SimpleVersionedNamespace.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedNamespace.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedSchema.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedURN.java
  controller/src/main/java/org/jboss/as/controller/xml/XMLAttributeSchema.java
  controller/src/main/java/org/jboss/as/controller/xml/XMLElementSchema.java
  controller/src/test/java/org/jboss/as/controller/xml/VersionedURNTestCase.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemSchema.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemXMLDescriptionFactory.java
  discovery/src/main/java/org/wildfly/extension/discovery/StaticDiscoveryProviderDefinition.java
  discovery/src/test/java/org/wildfly/extension/discovery/DiscoverySubsystemTestCase.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuditLoggingParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemParser1_0.java
  elytron/src/main/java/org/wildfly/extension/elytron/RealmParser.java
  server/src/main/java/org/jboss/as/server/deployment/jbossallxml/JBossAllSchema.java
Labels: ready-for-merge, deps-ok

#5402 WFCORE-6258 Refactor Model interface from wildfly-clustering-common into wildfly-controller
  controller/src/main/java/org/jboss/as/controller/SubsystemModel.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtensionTransformerRegistration.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemModel.java
  discovery/src/test/java/org/wildfly/extension/discovery/DiscoveryTransformersTestCase.java
Labels: ready-for-merge, deps-ok

#5403 WFCORE-6259 Refactor SubsystemResourceDescriptionResolver implementation from wildfly-clustering-common to wildfly-controller
  controller/pom.xml
  controller/src/main/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolver.java
  controller/src/main/java/org/jboss/as/controller/descriptions/ParentResourceDescriptionResolver.java
  controller/src/main/java/org/jboss/as/controller/descriptions/SubsystemResourceDescriptionResolver.java
  controller/src/test/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolverTestCase.java
  discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderDefinition.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoveryExtension.java
  discovery/src/main/java/org/wildfly/extension/discovery/DiscoverySubsystemDefinition.java
  discovery/src/main/java/org/wildfly/extension/discovery/StaticDiscoveryProviderDefinition.java
Labels: ready-for-merge, deps-ok

#5407 [WFCORE-6261]: org.jboss.as.test.manualmode.management.persistence.YamlExtensionTestCase is flaky
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml
Labels: ready-for-merge, deps-ok

#5404 [WFCORE-5947] fix test for IBM JDK Semeru 11
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/KerberosTestUtils.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/Krb5LoginConfiguration.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
Labels: ready-for-merge, deps-ok

#5409 WFCORE-6262 Enhance ParentResourceDescriptionResolver to support nested children and arbitrary keys
  controller/src/main/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolver.java
  controller/src/main/java/org/jboss/as/controller/descriptions/ParentResourceDescriptionResolver.java
  controller/src/main/java/org/jboss/as/controller/descriptions/SubsystemResourceDescriptionResolver.java
  controller/src/test/java/org/jboss/as/controller/descriptions/ChildResourceDescriptionResolverTestCase.java
Labels: ready-for-merge, deps-ok

#5408 [WFCORE-6142] Remove deprecated AbstractAddStepHandler methods
  controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/AbstractBoottimeAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/AbstractRemoveStepHandler.java
  controller/src/main/java/org/jboss/as/controller/ReloadRequiredAddStepHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/common/InterfaceAddHandler.java
  controller/src/test/java/org/jboss/as/controller/CapabilityRegistryTestCase.java
  elytron/src/main/java/org/wildfly/extension/elytron/BaseAddHandler.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ProfileAddHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ServerGroupAddHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerAddHandler.java
  jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemAdd.java
  jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorAdd.java
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestControllerSubsystemAdd.java
  request-controller/src/test/java/org/wildfly/extension/requestcontroller/WFCORE4967_TestCase.java
  server/src/main/java/org/jboss/as/server/services/net/InterfaceAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingResourceDefinition.java
  server/src/main/java/org/jboss/as/server/services/net/OutboundSocketBindingResourceDefinition.java
  server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingResourceDefinition.java
  server/src/main/java/org/jboss/as/server/services/net/SocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/SpecifiedInterfaceAddHandler.java
Labels: ready-for-merge, deps-ok

#5410 WFCORE-6263 Add ExtensionParsingContext convenience method for registering a set of schemas
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
Labels: ready-for-merge, deps-ok

#5416 [WFCORE-6267] Remove domain.xml host-exclude entries for releases pri…
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-host-excludes.xml
Labels: ready-for-merge, deps-ok

#5419 Revert "[WFCORE-6267] Remove domain.xml host-exclude entries for releases pri…"
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-host-excludes.xml
Labels: deps-ok

#5414 [WFCORE-6266]: Make the YamlExtensionTestCase less fragile.
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml
Labels: ready-for-merge, deps-ok

#5423 [WFCORE-6273] Upgrade SLF4J to 2.0.7
  pom.xml
Labels: ready-for-merge, deps-ok

#5418 Fix for WFCORE-6270, Bootable JAR, Security providers are not registered during boot
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
Labels: ready-for-merge, deps-ok

#5417 [WFCORE-6268] Remove use of deprecated ModelTestControllerVersion enums
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  discovery/src/test/java/org/wildfly/extension/discovery/DiscoveryTransformersTestCase.java
  discovery/src/test/resources/org/wildfly/extension/discovery/discovery-transform-1.0.0.xml
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-1.2.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-4.0.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-8.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-8.0.xml
  io/tests/src/test/java/org/wildfly/extension/io/IOSubsystemTransformerTestCase.java
  io/tests/src/test/resources/org/wildfly/extension/io/io-2.0-transformer.xml
  io/tests/src/test/resources/org/wildfly/extension/io/io-3.0-transformer.xml
  io/tests/src/test/resources/org/wildfly/extension/io/io-reject.xml
  logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingSubsystemTransformersTestCase.java
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-transformers.xml
  remoting/tests/src/test/resources/org/jboss/as/remoting/remoting-with-expressions-and-good-legacy-protocol.xml
  security-manager/src/test/java/org/wildfly/extension/security/manager/SecurityManagerSubsystemTestCase.java
  security-manager/src/test/resources/org/wildfly/extension/security/manager/security-manager-reject.xml
Labels: ready-for-merge, deps-ok

#5422 [WFCORE-6272] CVE-2022-4492 CVE-2023-1108 Upgrade Undertow to 2.3.5.Final
  pom.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
Labels: deps-ok

#5425 [WFCORE-6267] Remove domain.xml host-exclude entries for releases pri…
  core-feature-pack/galleon-common/src/main/resources/feature_groups/core-domain-host-excludes.xml
Labels: deps-ok

#5424 [WFCORE-5553] Prune ProxyStepHandler and GlobalOperationHandlers isWFCORE621Needed and executeWFCORE621 logic
  controller/src/main/java/org/jboss/as/controller/ProxyStepHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/global/GlobalOperationHandlers.java
Labels: ready-for-merge, deps-ok

#5431 [WFCORE-6281] Explicitly close log Context on LoggingSubsystemTestCase
  logging/src/test/java/org/jboss/as/logging/LoggingSubsystemTestCase.java
Labels: ready-for-merge, deps-ok

#5427 WFCORE-6278 Overload EnumValidator.create(...) to avoid redundant set copy
  controller/src/main/java/org/jboss/as/controller/operations/validation/EnumValidator.java
Labels: ready-for-merge, deps-ok

#5429 [WFCORE-6276] RegexRoleMapperTest does not clean up resources
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/RegexRoleMapperTest.java
Labels: ready-for-merge, deps-ok
