Repository wildfly/wildfly-core, pull requests merged in 2023-07, with the labels that each got.

#5570 [WFCORE-6418] Upgrade Elytron Web to 4.0.0.Final
  pom.xml
Labels: ready-for-merge, deps-changed

#5535 WFCORE-6369 Eliminate unnecessary collection copying in AbstractAddStepHandler constructors
  controller/src/main/java/org/jboss/as/controller/AbstractAddStepHandler.java
Labels: ready-for-merge, deps-ok

#5573 [WFCORE-6421] Wait until the server is fully started before starting …
  server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
Labels: deps-ok

#5574 Fix for WFCORE-6424, Generic command argument value issue with List containing Object
  cli/src/main/java/org/jboss/as/cli/parsing/arguments/ArgumentValueCallbackHandler.java
  cli/src/test/java/org/jboss/as/cli/parsing/test/ArgumentValueConverterTestCase.java
Labels: ready-for-merge, deps-ok

#5578 [WFCORE-6426] Upgrade to Remoting JMX 3.1.0.Final.
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#5577 WFCORE-6425 Domain testsuite uses invalid remoting configuration
  testsuite/domain/src/test/resources/domain-configs/domain-config-changes.xml
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
Labels: ready-for-merge, deps-ok

#5530 [WFCORE-6290] Tests if the server starts when the process UUID is invalid or removed.
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/ProcessUuidTestCase.java
Labels: ready-for-merge, deps-ok

#5575 [WFCORE-6285] Document how to move off the sun.jdk module in its modu…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/jdk/main/module.xml
Labels: ready-for-merge, deps-ok

#5580 [WFCORE-6285] Document how to move off remaining deprecated modules in their module.xml files
  core-feature-pack/common/src/main/resources/modules/system/layers/base/ibm/jdk/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/api/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/sql/api/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/javax/xml/stream/api/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/scripting/main/module.xml
Labels: ready-for-merge, deps-ok

#5581 WFCORE-6428 Error occurred in starting fork when running with jacoco profile
  pom.xml
Labels: ready-for-merge, deps-ok

#5583 [WFCORE-6429] Upgrade Eclipse Parsson from 1.1.2 to 1.1.3.
  pom.xml
Labels: ready-for-merge, deps-ok, 21.x

#5585 [WFCORE-6430] Update the SECURITY.md document
  SECURITY.md
Labels: deps-ok

#5546 [WFCORE-6371][WFCORE-6393][WFCORE-6394] Adding support for o.j.m.s.ServiceTarget.addService() method plus deprecated methods cleanup
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ContainerStateMonitor.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ServiceVerificationHelper.java
  controller/src/main/java/org/jboss/as/controller/remote/AbstractModelControllerOperationHandlerFactoryService.java
  controller/src/main/java/org/jboss/as/controller/services/path/PathAddHandler.java
  controller/src/test/java/org/jboss/as/controller/ModelControllerImplUnitTestCase.java
  elytron/src/main/java/org/wildfly/extension/elytron/ModifiableRealmDecorator.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/InjectedSocketBindingStreamServerService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingHttpUpgradeService.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingServices.java
  server/src/main/java/org/jboss/as/server/deployment/AbstractDeploymentUnitService.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentStatusHandler.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
  server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
  server/src/main/java/org/jboss/as/server/deployment/SubDeploymentProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
  server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
Labels: ready-for-merge, deps-ok, 22.x

#5579 WFCORE-6427 Upgrade jboss-logging from 3.4.3.Final to 3.5.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok, 22.x

#5548 WFCORE-6397/WFCORE-6398/WFCORE-6399 CapabilityServiceTarget/CapabilityServiceBuilder enhancements
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
  controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
  discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderAddHandler.java
  discovery/src/main/java/org/wildfly/extension/discovery/StaticDiscoveryProviderAddHandler.java
Labels: ready-for-merge, deps-ok, 22.x

#5586 [WFCORE-6431]: Use InputStream.nullInputStream.
  deployment-repository/src/main/java/org/jboss/as/repository/ContentRepositoryImpl.java
  deployment-repository/src/main/java/org/jboss/as/repository/ExplodedContent.java
  deployment-repository/src/main/java/org/jboss/as/repository/HashUtil.java
  deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
Labels: ready-for-merge, deps-ok

#5590 WFCORE-6438 Remove deprecated for removal VersionedURN subclasses
  controller/src/main/java/org/jboss/as/controller/LegacySubsystemURN.java
  controller/src/main/java/org/jboss/as/controller/SubsystemURN.java
Labels: ready-for-merge, deps-ok
