Repository wildfly/wildfly-core, pull requests merged in 2023-08, with the labels that each got.

#5592 WFCORE-6440 HttpManagementAddHandler references ServerEnvironment incorrectly
  host-controller/src/main/java/org/jboss/as/host/controller/operations/HttpManagementAddHandler.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Labels: ready-for-merge, deps-ok

#5588 WFCORE-6400 Update DeploymentPhaseContext to return a ServiceTarget capable of resolving capability requirements.
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/CapabilityServiceTarget.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/RequirementServiceBuilder.java
  controller/src/main/java/org/jboss/as/controller/RequirementServiceTarget.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContext.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentPhaseContextImpl.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
Labels: deps-ok

#5480 WFCORE-6321 Expose ServerEnvironment via a capability
  server/src/main/java/org/jboss/as/server/ServerEnvironmentService.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
  server/src/main/java/org/jboss/as/server/deployment/ManagedExplodedContentServitor.java
  server/src/main/java/org/jboss/as/server/operations/HttpManagementAddHandler.java
Labels: ready-for-merge, deps-ok

#5595 [WFCORE-6442] Make ModuleSpecification retains distinct ModuleDepende…
  server/src/main/java/org/jboss/as/server/deployment/module/FilterSpecification.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependency.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
Labels: ready-for-merge, deps-ok

#5591 [WFCORE-6439] Upgrade JBoss Modules to 2.1.2.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5576 [WFCORE-6423] Allow reload operation to send an early response when u…
  controller/src/main/java/org/jboss/as/controller/remote/ModelControllerClientOperationHandler.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClient.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolClientImpl.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolHandlers.java
  controller/src/main/java/org/jboss/as/controller/remote/TransactionalProtocolOperationHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostReloadProxyTestCase.java
Labels: ready-for-merge, deps-ok, 22.x

#5594 [WFCORE-6441] Bump the core management version to version 23
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
  version/src/main/java/org/jboss/as/version/Version.java
Labels: ready-for-merge, deps-ok

#5593 [WFCORE-6436] Create the ModelTestModelControllerService variants for…
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
Labels: ready-for-merge, deps-ok

#5599 [WFCORE-6446] Enable better test failure output when the queue for sy…
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/syslog/SyslogHandlerTestCase.java
Labels: ready-for-merge, deps-ok

#5596 [WFCORE-6444] Upgrade BouncyCastle to 1.76.
  pom.xml
Labels: ready-for-merge, deps-ok

#5597 [WFCORE-6444] Upgrade BouncyCastle to 1.76.
  pom.xml
Labels: ready-for-merge, 21.x

#5601 [WFCORE-6448] Upgrade Eclipse Parsson from 1.1.3 to 1.1.4
  pom.xml
Labels: ready-for-merge, deps-ok

#5603 [WFCORE-6433] ServerGroupResourceDefinition registered DomainServerLifecycleHandlers in the wrong place
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/ServerGroupResourceDefinition.java
Labels: ready-for-merge, deps-ok

#5602 [WFCORE-6435] Make WildFly 29 available in ModelTestControllerVersion
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  pom.xml
Labels: ready-for-merge, deps-ok

#5589 [WFCORE-6375][WFCORE-6434] Do not synchronize stopped servers when a HC reconnects and allow reload/restart required when starting
  controller/src/main/java/org/jboss/as/controller/ControlledProcessState.java
  controller/src/test/java/org/jboss/as/controller/ControlledProcessStateUnitTestCase.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ConsoleAvailabilityService.java
  domain-http/interface/src/test/java/org/jboss/as/domain/http/server/ConsoleAvailabilityUnitTestCase.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/SyncServerStateOperationHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/secondaryreconnect/DeploymentScenario.java
Labels: ready-for-merge, deps-ok

#5232 WFCORE-5305 Response warnings don't propagate up in read-resource response assembly
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
Labels: ready-for-merge, deps-ok, 22.x

#5582 [WFCORE-6349] Log yaml files used for configuration extension
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
Labels: ready-for-merge, deps-ok

#5612 [WFCORE-6460] Fix the naming of build directory in Readme.md
  README.md
Labels: ready-for-merge, deps-ok

#5608 [WFCORE-5305] Fix import order in ReadResourceHandler
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
Labels: ready-for-merge, deps-ok

#5609 [WFCORE-6458]: $HOSTNAME being set to "" prevents qualified hostname resolution
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
Labels: deps-ok

#5605 [WFCORE-6454] Use TCP/IP process communication for surefire plugin
  pom.xml
  testsuite/pom.xml
Labels: deps-ok

#5622 [WFCORE-6467] Upgrade XNIO to 3.8.10.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5619 [WFCORE-6464] Update CustomCredentialSecurityFactoryImpl to no longer rely on private Elytron API
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryImpl.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/elytron/CustomCredentialSecurityFactoryTestCase.java
Labels: ready-for-merge, deps-ok

#5623 [WFCORE-6468] Upgrade Undertow to 2.3.8.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5618 [WFCORE-6462] Upgrade xom to version 1.3.9
  pom.xml
Labels: deps-ok

#5625 [WFCORE-6461] Replace PermissionUtils use of xom with staxmapper
  pom.xml
  testbom/pom.xml
  testsuite/shared/pom.xml
  testsuite/shared/src/main/java/org/jboss/as/test/shared/PermissionUtils.java
Labels: deps-ok
