Repository wildfly/wildfly-core, pull requests merged in 2023-09, with the labels that each got.

#5641 [WFCORE-6475] Upgrade WildFly Elytron to 2.2.2.Final
  pom.xml
Labels: deps-ok

#5640 [WFCORE-5753] Update ModelTestControllerVersion.EAP_XP_4 to use proper EAP XP4 artifacts
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
Labels: deps-ok

#5645 [WFCORE-6477]: Possible NPE in YAMLExtension for some resource without a
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
Labels: deps-ok

#5648 WFCORE-6478 Enable manual start of github actions CI workflow
  .github/workflows/build-manual.yml
Labels: deps-ok

#5637 [WFCORE-6470] Make the TcclMBeanServer.(un)registerMBean() methods us…
  jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java
Labels: deps-ok

#5628 [WFCORE-6471] Upgrade FasterXML Jackson to 2.14.3
  pom.xml
Labels: deps-ok

#5649 [WFCORE-6480] Upgrade xml-maven-plugin to 1.1.0
  elytron/pom.xml
  pom.xml
  testsuite/domain/pom.xml
Labels: deps-ok

#5639 [WFCORE-6466] Split LayersTest#test into two separate methods
  testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
Labels: deps-ok

#5624 [WFCORE-6469] Upgrade JBoss Marshalling to 2.1.2.SP1
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/marshalling/main/module.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#5647 [WFCORE-6476] Reduce failed step logging to DEBUG for read-only inter…
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Labels: ready-for-merge, deps-ok

#4966 [WFCORE-4296][WFCORE-5406] Add required --add-opens for java.base/com.sun.net.ssl.internal.ssl when HTTPS is configured
  core-feature-pack/common/src/main/resources/content/bin/common.bat
  core-feature-pack/common/src/main/resources/content/bin/common.ps1
  core-feature-pack/common/src/main/resources/content/bin/common.sh
  host-controller/src/main/java/org/jboss/as/host/controller/ManagedServerBootCmdFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/jvm/JvmType.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  pom.xml
Labels: deps-ok

#5660 [WFCORE-6493] Add Guava as a test dependency to the Test Suite.
  testsuite/domain/pom.xml
  testsuite/standalone/pom.xml
Labels: deps-ok

#5666 [WFCORE-6495] Upgrade FasterXML Jackson to 2.15.2
  pom.xml
Labels: deps-ok

#5670 [WFCORE-6502] Fix variable configuration on common.conf.bat are ignored
  core-feature-pack/common/src/main/resources/content/bin/common.bat
Labels: ready-for-merge

#5669 [WFCORE-6501] Upgrade StAXMapper 1.5.0.Final
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#5668 [WFCORE-6500] Upgrade JBoss DMR 1.7.0.Final
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
  pom.xml
Labels: ready-for-merge, deps-ok

#5671 [WFCORE-6506] Initial Java releases contain neither minor nor micro part in the version string - adjusting tests
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: deps-ok

#5673 [WFCORE-6491] Fix HostControllerBootOperationsTestCase random failures
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/HostControllerBootOperationsTestCase.java
  testsuite/domain/src/test/resources/host-configs/host-secondary-main-three-without-jvm.xml
Labels: ready-for-merge, deps-ok

#5675 [WFCORE-6518] Move createFilePermission methods from WF org.jboss.as.test.shared.integration.ejb.security.PermissionUtils to org.jboss.as.test.shared.PermissionUtils
  testsuite/shared/src/main/java/org/jboss/as/test/shared/PermissionUtils.java
Labels: ready-for-merge, deps-ok

#5684 [WFCORE-6515] Upgrade Jandex from 3.1.3 to 3.1.5
  pom.xml
Labels: ready-for-merge, deps-ok

#5681 [WFCORE-6512] Reimplement WFCORE-1386
  core-feature-pack/common/src/main/resources/content/docs/contrib/scripts/service/service.bat
Labels: deps-ok

#5687 [WFCORE-6510] Update wildfly-remoting_6_0.xsd copyright header
  remoting/subsystem/src/main/resources/schema/wildfly-remoting_6_0.xsd
Labels: deps-ok

#5678 [WFCORE-6520][WFCORE-6521] Further JDK11 Cleanup - removing unused code plus using new API to improve performance
  elytron/src/test/java/org/wildfly/extension/elytron/JdkUtils.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/jvm/JvmElement.java
  host-controller/src/test/java/org/jboss/as/host/controller/ManagedServerBootCmdFactoryTestCase.java
  launcher/src/main/java/org/wildfly/core/launcher/Jvm.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  platform-mbean/src/main/java/org/jboss/as/platform/mbean/PlatformMBeanUtil.java
  server/src/main/java/org/jboss/as/server/deployment/module/VFSResourceLoader.java
  server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/shared/AssumeTestGroupUtil.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/ssl/sni/SNICombinedWithALPNTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/JdkModuleDependencyTestCase.java
Labels: ready-for-merge, deps-ok

#5690 WFCORE-6529 Update Eclipse IDE templates to use new copyright header
  ide-configs/eclipse/wildfly-templates.xml
Labels: ready-for-merge, deps-ok

#5691 WFCORE-6530 Remove the obsolete COMMITMENT file
  COMMITMENT
Labels: ready-for-merge, deps-ok

#5676 [WFCORE-4532] Enable security tests on JDK14+ since they no longer fail
  elytron/src/test/java/org/wildfly/extension/elytron/TlsTestCase.java
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/OpenSslTlsTestCase.java
Labels: deps-ok

#5685 [WFCORE-6525] Rename AuditLogBootingSyslogTest to AuditLogBootingSysl…
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingSyslogTestCase.java
Labels: ready-for-merge, deps-ok
