Repository wildfly/wildfly-core, pull requests merged in 2023-04, with the labels that each got.

#5430 Fix for WFCORE-6280, Upgrade Galleon to 5.0.9.Final and galleon Plugins to 6.3.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5359 WFCORE-6203 Move test dependency to testbom
  bootable-jar/pom.xml
  cli/pom.xml
  controller-client/pom.xml
  controller/pom.xml
  core-management/core-management-subsystem/pom.xml
  core-model-test/framework/pom.xml
  core-model-test/tests/pom.xml
  core-security/pom.xml
  deployment-repository/pom.xml
  deployment-scanner/pom.xml
  domain-http/interface/pom.xml
  domain-management/pom.xml
  embedded/pom.xml
  event-logger/pom.xml
  host-controller/pom.xml
  io/tests/pom.xml
  jmx/pom.xml
  launcher/pom.xml
  logging/pom.xml
  management-client-content/pom.xml
  model-test/pom.xml
  network/pom.xml
  patching/pom.xml
  platform-mbean/pom.xml
  pom.xml
  process-controller/pom.xml
  protocol/pom.xml
  request-controller/pom.xml
  security-manager/pom.xml
  server/pom.xml
  testbom/pom.xml
  threads/pom.xml
Labels: ready-for-merge, deps-ok

#5432 [WFCORE-6283] Make TestModule.getModulesDirectory public
  testsuite/shared/src/main/java/org/jboss/as/test/module/util/TestModule.java
Labels: ready-for-merge, deps-ok

#5426 [WFCORE-6277] adds wildflyee.api module dependency to java.se
  core-feature-pack/common/src/main/resources/modules/system/layers/base/wildflyee/api/main/module.xml
Labels: ready-for-merge, deps-ok

#5393 [WFCORE-6244] Elytron mapped-role-mapper does not support expressions
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
  elytron/src/main/java/org/wildfly/extension/elytron/MapperParser.java
  elytron/src/main/java/org/wildfly/extension/elytron/RoleMapperDefinitions.java
  elytron/src/main/resources/org/wildfly/extension/elytron/LocalDescriptions.properties
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0-reject.xml
  elytron/src/test/resources/org/wildfly/extension/elytron/elytron-transformers-13.0.xml
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/MappedRoleMapperTest.java
Labels: ready-for-merge, deps-ok

#5435 [WFCORE-6284] Upgrade XNIO to 3.8.9.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5436 [WFCORE-6287] Replace deprecated systemProperties configuration
  pom.xml
  testsuite/elytron/pom.xml
  testsuite/manualmode/pom.xml
  testsuite/rbac/pom.xml
  testsuite/standalone/pom.xml
Labels: ready-for-merge, deps-ok

#5399 [WFCORE-6245] Eliminating deprecated ibm.jdk module usages
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/DeploymentModulesListTestCase.java
Labels: ready-for-merge, deps-ok

#5325 [WFCORE-6157] Partial revert - enabling failing tests
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
Labels: deps-ok, Stale

#5438 [WFCORE-6289] Upgrading JBoss MSC to 1.5.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5441 [WFCORE-6157] Allow OperationCancellationUnitTestCase to complete in a reasonable time.
  controller/src/test/java/org/jboss/as/controller/OperationCancellationUnitTestCase.java
Labels: deps-ok

#5434 [WFCORE-6279] Replace Deployment Processors Javax dependencies with Jakarta modules
  elytron/src/main/java/org/wildfly/extension/elytron/EESecurityDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/DriverDependenciesProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleAliasChecker.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: ready-for-merge, deps-ok, 20.x

#5449 [WFCORE-6291] Obtain the complete set of PolicyContextHandler implementations from the Elytron EE module.
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml
  elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
  pom.xml
Labels: ready-for-merge, Blocker, deps-ok

#4856 [WFCORE-2957] read-resource without include-runtime shows runtime-only resources
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadResourceHandler.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CompositeOperationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/WildcardOperationsTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/customcontext/testbase/CustomManagementContextTestBase.java
Labels: ready-for-merge, deps-ok, 21.x

#5448 [20.x] [WFCORE-6291] Obtain the complete set of PolicyContextHandler implementations from the Elytron EE module.
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/jakarta/authorization/main/module.xml
  elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
  pom.xml
Labels: ready-for-merge, Blocker, 20.x

#5452 [20.x][WFCORE-6271] Add a service that can be used to ensure a virtual SecurityDomain associated with a virtual-security-domain resource has been created
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDescriptionConstants.java
  elytron/src/main/java/org/wildfly/extension/elytron/VirtualDomainDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/VirtualSecurityDomainProcessor.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainMarkerUtility.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainMetaData.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainMetaDataService.java
  server/src/main/java/org/jboss/as/server/security/VirtualDomainUtil.java
  server/src/main/java/org/jboss/as/server/security/VirtualSecurityDomainCreationService.java
Labels: ready-for-merge, Critical, 20.x

#5454 [20x][WFCORE-6279] Fix minor bug displaying exclusion warnings
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
Labels: ready-for-merge, 20.x

#5445 [WFCORE-6249] Eliminating deprecated sun.jdk module usages
  core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/expressions/module/test-secure-expressions-module.xml
  testsuite/shared/src/main/resources/jmx-listener-module.xml
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/logging/operations/CustomFormattersTestCase.java
Labels: ready-for-merge, deps-ok

#5462 [WFCORE-6308] Removing unused Jetty ALPN provider - it was targeting JDK8 and below
  core-feature-pack/common/src/main/resources/modules/system/layers/base/io/undertow/core/main/module.xml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5461 [WFCORE-6310] Upgrade Byteman to 4.0.21
  pom.xml
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5457 [WFCORE-6196] Reject host registrations before WildFly 23
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5459 [WFCORE-6309] The license for StaxMapper should be LGPL 2.1 or Later.
  core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml
Labels: deps-ok, 21.0.0.Beta1

#5281 [WFCORE-6124] Remove deprecated SocketBinding and OutboundSocketBinding members
  jmx/src/test/java/org/jboss/as/jmx/JMXSubsystemTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/ModelControllerMBeanTestCase.java
  network/src/main/java/org/jboss/as/network/OutboundSocketBinding.java
  network/src/main/java/org/jboss/as/network/SocketBinding.java
  server/src/main/java/org/jboss/as/server/services/net/BindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/LocalDestinationOutboundSocketBindingAddHandler.java
  server/src/main/java/org/jboss/as/server/services/net/RemoteDestinationOutboundSocketBindingAddHandler.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/otherservices/subsystem/SubsystemAddWithSocketBindingUserService.java
Labels: deps-ok, 21.0.0.Beta1

#5468 [WFCORE-6322] Remove deprecated AbstractControllerService APIs
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestKernelServicesImpl.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
Labels: deps-ok, 21.0.0.Beta1

#5466 [WFCORE-6319] Remove misc unused and deprecated server module types and methods
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/coordination/ServerRequireRestartTask.java
  server/src/main/java/org/jboss/as/server/BootstrapListener.java
  server/src/main/java/org/jboss/as/server/Main.java
  server/src/main/java/org/jboss/as/server/deployment/client/ModelControllerServerDeploymentManager.java
  server/src/main/java/org/jboss/as/server/operations/ServerRestartRequiredHandler.java
  server/src/main/java/org/jboss/as/server/operations/SystemPropertyAddHandler.java
  server/src/main/java/org/jboss/as/server/operations/SystemPropertyDeferredProcessor.java
Labels: deps-ok, 21.0.0.Beta1

#5465 [WFCORE-6318][WFCORE-6297] OperationContext API cleanups
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
  controller/src/test/java/org/jboss/as/controller/access/management/AuthorizedAddressTest.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOperationTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ProfileIncludesHandlerTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ReloadRequiredServerTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerConfigOperationsTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/ServerGroupAffectedResourceServerGroupOperationsTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/SocketBindingGroupIncludesHandlerTestCase.java
Labels: deps-ok, 21.0.0.Beta1

#5467 [WFCORE-6324] Upgrade bouncycastle from 1.72 to 1.73
  pom.xml
Labels: deps-ok, 21.0.0.Beta1

#5460 [WFCORE-6306] Bump the core management version to version 22.
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
  version/src/main/java/org/jboss/as/version/Version.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5464 [WFCORE-6173] Remove deprecated AbstractRemoveStepHandler methods
  controller/src/main/java/org/jboss/as/controller/AbstractRemoveStepHandler.java
  controller/src/main/java/org/jboss/as/controller/ReloadRequiredRemoveStepHandler.java
  controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronRemoveStepHandler.java
  elytron/src/main/java/org/wildfly/extension/elytron/ExpressionResolverResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/TrivialCapabilityServiceRemoveHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ProfileRemoveHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ServerGroupRemoveHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/LocalDomainControllerRemoveHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/NativeManagementRemoveHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/operations/ServerRemoveHandler.java
  host-controller/src/main/java/org/jboss/as/host/controller/resources/NativeManagementResourceDefinition.java
  jmx/src/main/java/org/jboss/as/jmx/JMXSubsystemRemove.java
  jmx/src/main/java/org/jboss/as/jmx/RemotingConnectorRemove.java
  server/src/main/java/org/jboss/as/server/operations/NativeManagementRemoveHandler.java
  server/src/main/java/org/jboss/as/server/services/net/InterfaceRemoveHandler.java
  server/src/main/java/org/jboss/as/server/services/net/SocketBindingRemoveHandler.java
  server/src/main/java/org/jboss/as/server/services/net/SpecifiedInterfaceRemoveHandler.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/extension/dependent/RootResourceDefinition.java
Labels: deps-ok, 21.0.0.Beta1

#5469 [WFCORE-6314] Remove @Deprecated from RequestController.SERVICE_NAME …
  request-controller/src/main/java/org/wildfly/extension/requestcontroller/RequestController.java
  testsuite/shared/src/main/java/org/wildfly/test/suspendresumeendpoint/TestSuspendServiceActivator.java
Labels: deps-ok, 21.0.0.Beta1

#5474 [WFCORE-6293] Partial revert of 'Removing JDK 8 specific excludes from maven enforcer plugin configurations'
  core-feature-pack/common/pom.xml
  core-feature-pack/ee-10-api/pom.xml
Labels: deps-ok

#5473 WFCORE-6325 Replace ExtensionRegistry constructor bloat with builder pattern
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/test/java/org/jboss/as/controller/InterleavedSubsystemTestCase.java
  controller/src/test/java/org/jboss/as/controller/RemoveNonExistingResourceTestCase.java
  core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
  host-controller/src/main/java/org/jboss/as/host/controller/DomainModelControllerService.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/AbstractOrderedChildResourceSyncModelTestCase.java
  host-controller/src/test/java/org/jboss/as/domain/controller/operations/SyncModelServerStateTestCase.java
  jmx/src/main/java/org/jboss/as/jmx/MBeanServerService.java
  jmx/src/main/java/org/jboss/as/jmx/PluggableMBeanServerImpl.java
  jmx/src/test/java/org/jboss/as/jmx/auditlog/JmxAuditLogHandlerTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/rbac/JmxFacadeRbacEnabledTestCase.java
  jmx/src/test/java/org/jboss/as/jmx/rbac/JmxRbacTestCase.java
  server/src/main/java/org/jboss/as/server/Bootstrap.java
  server/src/test/java/org/jboss/as/server/parsing/SystemPropertiesParsingTestCase.java
  server/src/test/java/org/jboss/as/server/test/InterfaceManagementUnitTestCase.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/SubsystemTestDelegate.java
  testsuite/shared/src/main/java/org/wildfly/test/mixed/domain/TestParserUtils.java
Labels: deps-ok, 21.0.0.Beta1

#5475 [WFCORE-6316] Remove deprecated SimpleResourceDefinition elements
  controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java
  controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/DiscoveryOptionResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/discovery/StaticDiscoveryResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/ignored/IgnoredDomainTypeResourceDefinition.java
  management-client-content/src/main/java/org/jboss/as/management/client/content/ManagedDMRContentResourceDefinition.java
  management-client-content/src/main/java/org/jboss/as/management/client/content/ManagedDMRContentTypeResourceDefinition.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/transformers/subsystem/simple/VersionedExtensionCommon.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5471 [WFCORE-6315] Remove deprecated SimpleOperationDefinition elements
  controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/HostProcessReloadHandler.java
Labels: ready-for-merge, deps-ok, 21.0.0.Beta1

#5472 [WFCORE-6326] Revert the removal of the org.jboss.vfs module on deplo…
  server/src/main/java/org/jboss/as/server/deployment/module/ServerDependenciesProcessor.java
Labels: ready-for-merge, Blocker, deps-ok, 21.0.0.Beta1
