Repository wildfly/wildfly-core, pull requests merged in 2024-08, with the labels that each got.

#6114 [WFCORE-6936] Allow the maven.test.redirectTestOutputToFile system pr…
  pom.xml
  testsuite/client-old-server/pom.xml
  testsuite/domain/pom.xml
  testsuite/elytron/pom.xml
  testsuite/embedded/pom.xml
  testsuite/pom.xml
  testsuite/rbac/pom.xml
  testsuite/scripts/pom.xml
  testsuite/standalone/pom.xml
  testsuite/unstable-api-annotation/tests/pom.xml
Labels: deps-ok

#6069 [WFCORE-6891] Remove support for parsing domain management schemas prior to urn:jboss:domain:1.7
  .gitignore
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/ParseUtils.java
  host-controller/src/main/java/org/jboss/as/domain/controller/logging/DomainControllerLogger.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/DomainXml_Legacy.java
  host-controller/src/main/java/org/jboss/as/host/controller/parsing/HostXml_Legacy.java
  host-controller/src/test/java/org/jboss/as/domain/controller/parsing/SupportedNamespaceParsingTestCase.java
  host-controller/src/test/java/org/jboss/as/host/controller/parsing/SupportedNamespaceParsingTestCase.java
  server/src/main/java/org/jboss/as/server/parsing/StandaloneXml_Legacy.java
  server/src/main/java/org/jboss/as/server/parsing/VaultXml.java
  server/src/main/resources/schema/jboss-as-config_1_0.xsd
  server/src/main/resources/schema/jboss-as-config_1_1.xsd
  server/src/main/resources/schema/jboss-as-config_1_2.xsd
  server/src/main/resources/schema/jboss-as-config_1_3.xsd
  server/src/main/resources/schema/jboss-as-config_1_4.xsd
  server/src/main/resources/schema/jboss-as-config_1_5.xsd
  server/src/main/resources/schema/jboss-as-config_1_6.xsd
  server/src/test/java/org/jboss/as/server/parsing/Jbas9020TestCase.java
  server/src/test/java/org/jboss/as/server/parsing/SupportedNamespaceParsingTestCase.java
Labels: ready-for-merge, deps-ok

#6122 WFCORE-6940 Allow null ManagementResourceRegistrar.register(...)
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java
Labels: ready-for-merge, deps-ok

#6129 [WFCORE-6952] Upgrade WildFly Elytron to 2.5.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#6128 [WFCORE-6745] Upgrade log4j2 to 2.23.1 and log4j2-jboss-logmanager to…
  pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/LoggingDependenciesTestCase.java
Labels: ready-for-merge, deps-changed

#6130 [25.x][WFCORE-6952] Upgrade WildFly Elytron to 2.5.1.Final
  pom.xml
Labels: ready-for-merge, 25.x

#6131 [WFCORE-6953] org.bouncycastle.bcpg JBoss Modules module requires jav…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
Labels: deps-ok

#6132 [25.x][WFCORE-6953] org.bouncycastle.bcpg JBoss Modules module requires jav…
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
Labels: 25.x

#6136 [WFCORE-6946] Fix word order
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
Labels: ready-for-merge, deps-ok

#6127 WFCORE-6948 Add ability for wildfly-subsystem to register an operation transformation for any specific operation (not just add).
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java
Labels: ready-for-merge, deps-ok

#6133 WFCORE-6954 (wildfly-subsystem) Do not auto-register add/remove resource operations for runtime resources.
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java
Labels: ready-for-merge, deps-ok

#6126 WFCORE-6945 Required child resource logic in wildfly-subsystem is not stability-level aware
  controller/src/main/java/org/jboss/as/controller/ResourceRegistration.java
  controller/src/test/java/org/jboss/as/controller/ResourceRegistrationTestCase.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/PathElementProvider.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandler.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandlerDescriptor.java
Labels: ready-for-merge, deps-ok

#6137 [WFCORE-6956] Wrong endpoint-name if the JBoss server name and 'jboss…
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
Labels: ready-for-merge, deps-ok

#6110 WFCORE-6931 Remove usage of deprecated AbstractWriteAttributeHandler constructors in threads subsystem
  threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolAdd.java
  threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/BoundedQueueThreadPoolWriteAttributeHandler.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorAdd.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/EnhancedQueueExecutorWriteAttributeHandler.java
  threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolAdd.java
  threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/QueuelessThreadPoolWriteAttributeHandler.java
  threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolAdd.java
  threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/ScheduledThreadPoolWriteAttributeHandler.java
  threads/src/main/java/org/jboss/as/threads/ThreadFactoryAdd.java
  threads/src/main/java/org/jboss/as/threads/ThreadFactoryResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/ThreadFactoryWriteAttributeHandler.java
  threads/src/main/java/org/jboss/as/threads/ThreadSubsystemResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/ThreadsWriteAttributeOperationHandler.java
  threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolAdd.java
  threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolResourceDefinition.java
  threads/src/main/java/org/jboss/as/threads/UnboundedQueueThreadPoolWriteAttributeHandler.java
Labels: ready-for-merge, deps-ok

#6145 [WFCORE-6963] improve AbstractModelResource.hasChildren efficiency
  controller/src/main/java/org/jboss/as/controller/registry/AbstractModelResource.java
Labels: ready-for-merge, deps-ok

#6150 [WFCORE-6968] Upgrade WildFly Elytron to 2.5.2.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#6151 [25.x][WFCORE-6968] Upgrade WildFly Elytron to 2.5.2.Final
  pom.xml
Labels: 25.x
