Repository wildfly/wildfly-core, pull requests merged in 2024-01, with the labels that each got.

#5817 WFCORE-6347 Refine installer Builder/Configuration interfaces.
  service/src/main/java/org/wildfly/service/Installer.java
  service/src/main/java/org/wildfly/service/ServiceInstaller.java
  service/src/test/java/org/wildfly/service/DefaultServiceTestCase.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
  subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java
Labels: deps-ok

#5820 WFCORE-6347 Add provider interfaces per service descriptor.
  controller/src/main/java/org/jboss/as/controller/capability/BinaryCapabilityNameResolver.java
  controller/src/main/java/org/jboss/as/controller/capability/UnaryCapabilityNameResolver.java
  controller/src/test/java/org/jboss/as/controller/capability/CapabilityNameResolverTestCase.java
  service/src/main/java/org/wildfly/service/descriptor/BinaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/NullaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/QuaternaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/ServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/TernaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/UnaryServiceDescriptor.java
Labels: deps-ok

#5810 [WFCORE-6649][WFCORE-6653] Deprecate --no-resol-local-cache and replace it with --…
  installation-manager/src/main/java/org/wildfly/core/instmgr/AbstractInstMgrUpdateHandler.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrConstants.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrListUpdatesHandler.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrOperationStepHandler.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrPrepareRevertHandler.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrPrepareUpdateHandler.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/cli/AbstractInstMgrCommand.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/cli/ListUpdatesAction.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/cli/PrepareUpdateAction.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/cli/RevertCommand.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/cli/UpdateCommand.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/logging/InstMgrLogger.java
  installation-manager/src/main/resources/org/wildfly/core/instmgr/LocalDescriptions.properties
  installation-manager/src/main/resources/org/wildfly/core/instmgr/cli/command_resources.properties
  installation-manager/src/test/java/org/wildfly/core/instmgr/InstMgrResourceTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/installationmanager/InstallationManagerIntegrationTestCase.java
Labels: deps-ok

#5823 WFCORE-6347 Misc API cleanup of capability reference recorder interfaces in wildfly-subsystem
  controller/src/main/java/org/jboss/as/controller/capability/BinaryCapabilityNameResolver.java
  controller/src/main/java/org/jboss/as/controller/capability/UnaryCapabilityNameResolver.java
  discovery/src/main/java/org/wildfly/extension/discovery/AggregateDiscoveryProviderRegistrar.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceRecorder.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/capability/ResourceCapabilityReferenceRecorder.java
  subsystem/src/test/java/org/wildfly/subsystem/resource/capabilty/CapabilityReferenceRecorderTestCase.java
Labels: deps-ok

#5784 [WFCORE-6635] Add a base JBossModulesCommandBuilder for launching oth…
  launcher/src/main/java/org/wildfly/core/launcher/AbstractCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Arguments.java
  launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/CliCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/DomainCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Environment.java
  launcher/src/main/java/org/wildfly/core/launcher/JBossModulesCommandBuilder.java
  launcher/src/main/java/org/wildfly/core/launcher/Launcher.java
  launcher/src/main/java/org/wildfly/core/launcher/ProcessHelper.java
  launcher/src/main/java/org/wildfly/core/launcher/StandaloneCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
Labels: ready-for-merge, deps-ok

#5825 WFCORE-6347 Add method to cast service descriptor instance as subtype.
  controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ServiceRemoveStepHandler.java
  service/src/main/java/org/wildfly/service/descriptor/BinaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/NullaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/QuaternaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/ServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/TernaryServiceDescriptor.java
  service/src/main/java/org/wildfly/service/descriptor/UnaryServiceDescriptor.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/capability/CapabilityReferenceRecorder.java
  subsystem/src/test/java/org/wildfly/subsystem/resource/capabilty/CapabilityReferenceRecorderTestCase.java
Labels: ready-for-merge, deps-ok

#5802 [WFCORE-6646]: Can't undefine "use-identity-roles" of /core-service=m…
  domain-management/src/main/java/org/jboss/as/domain/management/access/AccessAuthorizationUseIdentityRolesWriteAttributeHandler.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/GenericCommandTestCase.java
Labels: ready-for-merge, deps-ok

#5805 [WFCORE-6648]: Mark "read-config-as-xml" as deprecated on Community stream.
  controller/src/main/java/org/jboss/as/controller/operations/common/XmlMarshallingHandler.java
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/DomainRootDefinition.java
  host-controller/src/main/java/org/jboss/as/host/controller/model/host/HostResourceDefinition.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
Labels: ready-for-merge, deps-ok

#5819 Fix for WFCORE-6656, CLI, shaded jar can't start embedded when logging json formater configured
  cli/pom.xml
  testsuite/shared/pom.xml
Labels: ready-for-merge, deps-ok

#5828 WFCORE-6347 Add convenience method to map a dependency to an alternate type.
  service/src/main/java/org/wildfly/service/Dependency.java
  service/src/main/java/org/wildfly/service/ServiceDependency.java
  service/src/test/java/org/wildfly/service/ServiceDependencyTestCase.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java
  subsystem/src/test/java/org/wildfly/subsystem/service/ServiceDependencyTestCase.java
Labels: deps-ok

#5830 [WFCORE-6538] Prepare test suite for upcoming JBoss Remoting & XNIO releases
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
Labels: ready-for-merge, deps-ok, 23.x

#5835 [WFCORE-6667] Upgrade WildFly Elytron to 2.2.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5779 [WFCORE-6627] Make use of the SetRequestInformationMechanismFactory to set the request information during HTTP authentication
  elytron/src/main/java/org/wildfly/extension/elytron/HttpServerDefinitions.java
Labels: ready-for-merge, deps-ok

#5832 [WFCORE-6665] Replace http-connect with connector on domain mode test…
  testsuite/domain/src/test/resources/domain-configs/domain-standard.xml
  testsuite/domain/src/test/resources/expected-main-one.xml
  testsuite/domain/src/test/resources/expected-main-three.xml
Labels: ready-for-merge, deps-ok

#5829 WFCORE-6176 Generalize capability filter to cover more complex scenarios.
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/AddResourceOperationStepHandler.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/OperationStepHandlerDescriptor.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/RemoveResourceOperationStepHandler.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/WriteAttributeOperationStepHandler.java
Labels: Blocker, deps-ok, 23.x

#5824 [WFCORE-6658] Convert ControlledProcessStateService to the current MS…
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Server.java
  controller/src/main/java/org/jboss/as/controller/ControlledProcessStateService.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerBootstrap.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedHostControllerFactory.java
  embedded/src/main/java/org/wildfly/core/embedded/EmbeddedStandaloneServerFactory.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java
  server/src/main/java/org/jboss/as/server/BootstrapImpl.java
Labels: ready-for-merge, deps-ok

#5836 WFCORE-6669 Various tests fail when env specifies JDK_JAVA_OPTIONS or JAVA_TOOL_OPTIONS
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/CliScriptTestCase.java
  testsuite/scripts/src/test/java/org/wildfly/scripts/test/ElytronToolScriptTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/CliArgumentsTestCase.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/management/cli/ColorOutputTestCase.java
Labels: ready-for-merge, deps-ok

#5831 [WFCORE-6664] Upgrade SLF4J from 2.0.9 to 2.0.11
  pom.xml
Labels: ready-for-merge, deps-ok

#5841 [WFCORE-6531] Wrap server options in double quotes
  core-feature-pack/common/src/main/resources/content/bin/domain.sh
  core-feature-pack/common/src/main/resources/content/bin/standalone.sh
Labels: ready-for-merge, deps-ok

#5844 [WFCORE-6676] CVE-2023-48795 Upgrade Apache Mina SSHD to 2.12.0
  pom.xml
Labels: ready-for-merge, deps-ok

#5846 [23.x] [WFCORE-6676] CVE-2023-48795 Upgrade SSHD from 2.11.0 to 2.12.0
  pom.xml
Labels: 23.x

#5852 WFCORE-6687: bump licenses-plugin to 2.4.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5849 [WFCORE-6680]: YamlExtensionTestCase assertions are too fragile.
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/test.xml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/testWithCli.xml
Labels: ready-for-merge, deps-ok
