Repository wildfly/wildfly-core, pull requests merged in 2024-02, with the labels that each got.

#5845 [WFCORE-6677] Bump the core management version to version 25
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
  version/src/main/java/org/jboss/as/version/Version.java
Labels: ready-for-merge, deps-ok

#5833 [WFCORE-6645] [WFCORE-6666] Review DomainTestSuite.createSupport uses and remove deprecated methods from DomainTestSupport
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AdminOnlyModeTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DefaultInterfaceOverridingDomainTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainGracefulShutdownTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ProductInfoUnitTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/RenameHostControllerTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SecondaryRegistrationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/ServerManagementTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/SimpleDomainControllerMigrationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/installationmanager/InstallationManagerIntegrationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/HierarchicalCompositionTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/IncludeAllRoleTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/JmxRBACProviderHostScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/JmxRBACProviderServerGroupScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/ListRoleNamesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/PermissionsCoverageTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/PropertiesRoleMappingHostScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/PropertiesRoleMappingServerGroupScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/PropertiesRoleMappingStandardRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACProviderHostScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACProviderRunAsHostScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACProviderRunAsServerGroupScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACProviderRunAsStandardRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACProviderServerGroupScopedRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACProviderStandardRolesTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RBACSensitivityConstraintUtilizationTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/RolesIntegrityCheckingTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/rbac/WildcardReadsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainSuspendResumeTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/DomainTestSuite.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HostReloadProxyTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/HostSuspendResumeTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ReloadWithConfigTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/domain/management/util/DomainTestSupport.java
Labels: ready-for-merge, deps-ok

#5611 [WFCORE-6456] Add checks to LayersTest to confirm expected unused or …
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/server/main/module.xml
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
  testsuite/shared/src/main/java/org/jboss/as/test/layers/Result.java
  testsuite/shared/src/main/java/org/jboss/as/test/layers/Scanner.java
Labels: deps-ok

#5842 WFCORE-6668 Ensure read-feature-description results contain stability as reported by associated description for use by WildFly Glow
  controller/src/main/java/org/jboss/as/controller/AbstractControllerService.java
  controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
  controller/src/main/java/org/jboss/as/controller/AttributeDefinition.java
  controller/src/main/java/org/jboss/as/controller/DelegatingResourceDefinition.java
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/NotificationDefinition.java
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/ParallelBootOperationContext.java
  controller/src/main/java/org/jboss/as/controller/ProvidedResourceDefinition.java
  controller/src/main/java/org/jboss/as/controller/ReadOnlyContext.java
  controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
  controller/src/main/java/org/jboss/as/controller/capability/Capability.java
  controller/src/main/java/org/jboss/as/controller/capability/RuntimeCapability.java
  controller/src/main/java/org/jboss/as/controller/descriptions/DefaultNotificationDescriptionProvider.java
  controller/src/main/java/org/jboss/as/controller/descriptions/DefaultOperationDescriptionProvider.java
  controller/src/main/java/org/jboss/as/controller/descriptions/DefaultResourceDescriptionProvider.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionSubsystemResourceDefinition.java
  controller/src/main/java/org/jboss/as/controller/extension/ParallelExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/operations/global/ReadFeatureDescriptionHandler.java
  controller/src/main/java/org/jboss/as/controller/registry/AbstractResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/DelegatingImmutableManagementResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/DelegatingManagementResourceRegistration.java
  controller/src/test/java/org/jboss/as/controller/test/AbstractProxyControllerTest.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelControllerService.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestModelDescriptionValidator.java
  subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/TestModelControllerService.java
  subsystem-test/tests/src/test/java/org/jboss/as/subsystem/test/stability/MixedStabilitySubsystemTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadsTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/ReadFeatureDescriptionTestCase.java
Labels: ready-for-merge, deps-ok

#5856 [WFCORE-6692] Upgrade WildFly Elytron to 2.3.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5848 [WFCORE-5169] upgraded to Apache Directory Server AM27 and Kerby
  elytron/pom.xml
  elytron/src/test/java/org/wildfly/extension/elytron/LdapService.java
  elytron/src/test/java/org/wildfly/extension/elytron/TestEnvironment.java
  elytron/src/test/resources/org/wildfly/extension/elytron/ldap.xml
  pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/InMemoryDirectoryServiceFactory.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/InMemorySchemaPartition.java
  testsuite/elytron/pom.xml
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/AbstractKerberosMgmtSaslTestBase.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/AbstractKrb5ConfServerSetupTask.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/InMemoryDirectoryServiceFactory.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/InMemorySchemaPartition.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/KDCServerAnnotationProcessor.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/ManagedCreateLdapServer.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/kerberos/ManagedCreateTransport.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ldap/InMemoryDirectoryServiceFactory.java
  testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/ldap/InMemorySchemaPartition.java
Labels: ready-for-merge, deps-ok

#5858 [WFCORE-6695] CVE-2023-4639 Upgrade Undertow to 2.3.11.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5861 [WFCORE-6411] Make it possible to use JaasSecurityRealm via a custom-realm resource
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/elytron/layer-spec.xml
  elytron/src/main/java/org/wildfly/extension/elytron/JaasCustomSecurityRealmWrapper.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  testsuite/elytron/pom.xml
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/JaasCustomRealmWrapperTest.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TestCallbackHandler.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TestLoginModule.java
  testsuite/elytron/src/test/resources/org/wildfly/test/security/common/elytron/jaas-login.config
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: ready-for-merge, Feature, deps-ok

#5587 [WFCORE-6411] Make it possible to use JaasSecurityRealm via a custom-realm resource
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/elytron/layer-spec.xml
  elytron/src/main/java/org/wildfly/extension/elytron/JaasCustomSecurityRealmWrapper.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  testsuite/elytron/pom.xml
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/JaasCustomRealmWrapperTest.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TestCallbackHandler.java
  testsuite/elytron/src/test/java/org/wildfly/test/security/common/elytron/TestLoginModule.java
  testsuite/elytron/src/test/resources/org/wildfly/test/security/common/elytron/jaas-login.config
  testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
Labels: Feature, deps-ok

#5871 [WFCORE-6702]/[WFCORE-6703] Elytron component upgrades
  pom.xml
Labels: ready-for-merge, deps-ok

#5870 [WFCORE-6701] Upgrade JBoss VFS to 3.3.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5868 [WFCORE-6699] Add EAP 8.0 as known host exclude release version
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
Labels: ready-for-merge, deps-ok

#5867 [WFCORE-6698] Upgrade SSHD from 2.12.0 to 2.12.1
  pom.xml
Labels: ready-for-merge, deps-ok

#5875 [WFCORE-6707][WFCORE-6708][WFCORE-6709] CVE-2023-5379 CVE-2024-1459 CVE-2024-1635 Upgrade Undertow, XNIO and JBoss Remoting
  pom.xml
Labels: ready-for-merge, deps-ok, Critical

#5869 WFCORE-6697: fix resource location check
  server/src/main/java/org/jboss/as/server/controller/resources/ModuleLoadingResourceDefinition.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/mgmt/api/core/ModuleLoadingManagementTestCase.java
Labels: ready-for-merge, deps-ok

#5866 [WFCORE-6696] Upgrade SLF4J from 2.0.11 to 2.0.12
  pom.xml
Labels: ready-for-merge, deps-ok

#5876 [WFCORE-6707][WFCORE-6708][WFCORE-6709] CVE-2023-5379 CVE-2024-1459 CVE-2024-1635 Upgrade Undertow, XNIO and JBoss Remoting
  pom.xml
Labels: Critical, 23.x

#5873 [WFCORE-6706] Upgrading JBoss MSC to 1.5.3.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5878 [WFCORE-6710] Upgrade JBoss Modules to 2.1.3.Final
  embedded/src/main/java/org/wildfly/core/embedded/LoggerContext.java
  pom.xml
Labels: ready-for-merge, deps-ok

#5877 [WFCORE-6685] CLIEmbedServerTestCase.testStdOutEcho fails intermittently
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
Labels: ready-for-merge, deps-ok

#5883 [WFCORE-6714] Upgrading JBoss Marshalling to 2.1.4.SP1
  pom.xml
Labels: deps-ok

#5807 WFCORE-6650 Expose server stability and allow feature filtering from a DeploymentUnit.
  server/src/main/java/org/jboss/as/server/deployment/DeploymentHandlerUtil.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnit.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitImpl.java
  server/src/main/java/org/jboss/as/server/deployment/RootDeploymentUnitService.java
  server/src/main/java/org/jboss/as/server/deployment/SubDeploymentUnitService.java
Labels: ready-for-merge, deps-ok, 24.x
