Repository wildfly/wildfly-core, pull requests merged in 2024-03, with the labels that each got.

#5851 [WFCORE-6679]: ManagementReadXmlTestCase inputs are too fragile.
  testsuite/domain/pom.xml
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/BasicOpsTestCase.java
  testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/ManagementReadXmlTestCase.java
  testsuite/domain/src/test/resources/base-server-config.xml
  testsuite/domain/src/test/resources/expected-main-one.xml
  testsuite/domain/src/test/resources/expected-main-three.xml
Labels: ready-for-merge, deps-ok

#5882 [WFCORE-6712] Ensure the JBoss Modules ModuleLoggerFinder is activate…
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  embedded/src/main/java/org/wildfly/core/embedded/LoggerContext.java
  testsuite/embedded/pom.xml
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/AbstractTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/Environment.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/host/controller/SystemLoggerHostControllerTestCase.java
  testsuite/embedded/src/test/java/org/wildfly/core/test/embedded/standalone/SystemLoggerStandaloneTestCase.java
Labels: ready-for-merge, deps-ok

#5889 [WFCORE-6720] Upgrade JBoss Class File Writer to 1.3.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5885 [WFCORE-6717]: Incorrectly set options on the command line should fail
  server/src/main/java/org/jboss/as/server/Main.java
Labels: ready-for-merge, deps-ok

#5888 [WFCORE-6719] Upgrade JBoss Invocation to 2.0.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#5887 [WFCORE-6167] Workaround for known issue (enabled on JDK22+)
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedHostControllerTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/CLIEmbedServerTestCase.java
Labels: ready-for-merge, deps-ok

#5893 [WFCORE-6726] Use Prospero --rm option to automatically delete the ca…
  core-feature-pack/common/src/main/resources/content/bin/installation-manager.bat
  core-feature-pack/common/src/main/resources/content/bin/installation-manager.ps1
  core-feature-pack/common/src/main/resources/content/bin/installation-manager.sh
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrCandidateStatus.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrService.java
Labels: ready-for-merge, deps-ok

#5896 Fix for WFCORE-6729, Upgrade Galleon to 6.0.0.Beta3, Galleon plugins to 7.0.0.Beta4, and provisioning tooling
  pom.xml
Labels: ready-for-merge, deps-ok

#5900 [WFCORE-6735] Enable experimental as minimun stability level for Wild…
  core-feature-pack/galleon-feature-pack/pom.xml
Labels: deps-ok

#5894 [WFCORE-6723] Add header 'X-Content-Type-Options' to http management handlers
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainUtil.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
Labels: deps-ok

#5898 WFCORE-6716 Drop obsolete default getStability() method…
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnit.java
Labels: ready-for-merge, deps-ok

#5902 WFCORE-6742 SubsystemExtension needs the ability to define the current model/schema version given the stability level of the process
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/extension/UnstableSubsystemNamespaceParser.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionParsingContext.java
  controller/src/test/java/org/jboss/as/controller/extension/ExtensionRegistryTestCase.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ApplyExtensionsHandler.java
  subsystem/src/main/java/org/wildfly/subsystem/SubsystemExtension.java
  subsystem/src/main/java/org/wildfly/subsystem/SubsystemPersistence.java
Labels: ready-for-merge, deps-ok

#5884 [WFCORE-6739] Allow ordering of ServerActivity execution by registerin…
  server/src/main/java/org/jboss/as/server/suspend/ServerActivity.java
  server/src/main/java/org/jboss/as/server/suspend/SuspendController.java
  server/src/test/java/org/jboss/as/server/suspend/SuspendControllerTestCase.java
Labels: deps-ok

#5907 Fix for WFCORE-6747, Upgrade to Galleon 6.0.0.Beta4 and WFGP 7.0.0.Beta5
  core-feature-pack/galleon-feature-pack/pom.xml
  pom.xml
Labels: deps-ok

#5724 [WFCORE-6560] Log installation provisioning information at boot
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrInitialization.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/InstMgrService.java
  installation-manager/src/main/java/org/wildfly/core/instmgr/logging/InstMgrLogger.java
Labels: ready-for-merge, deps-ok, 24.x

#5906 [WFCORE-6746] Upgrade JBoss Modules to 2.1.4.Final
  embedded/src/main/java/org/wildfly/core/embedded/LoggerContext.java
  pom.xml
Labels: ready-for-merge, deps-ok

#5897 WFCORE-6730 A registered operation should never contain parameters or reply parameters not enabled by stability-level of process
  controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinition.java
  controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java
  controller/src/main/java/org/jboss/as/controller/registry/ConcreteResourceRegistration.java
  controller/src/main/java/org/jboss/as/controller/registry/OperationEntry.java
  controller/src/test/java/org/jboss/as/controller/registry/CoreManagementResourceRegistrationUnitTestCase.java
Labels: ready-for-merge, deps-ok

#5904 [WFCORE-6743] Upgrade io.smallrye:jandex from 3.1.6 to 3.1.7
  pom.xml
Labels: deps-ok

#5821 [WFCORE-4917]: Experimental - Provide a cool boot banner.
  core-feature-pack/galleon-feature-pack/src/main/resources/packages/product.conf/content/modules/system/layers/base/org/jboss/as/product/wildfly-core/module.xml
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerService.java
  server/src/main/java/org/jboss/as/server/ApplicationServerService.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  version/src/main/java/org/jboss/as/version/ProductConfig.java
Labels: ready-for-merge, Feature, deps-ok, 24.x

#5895 [WFCORE-6728] Utility to reload servers started by testsuite to a desired stability level
  controller/src/main/java/org/jboss/as/controller/RunningModeControl.java
  controller/src/main/java/org/jboss/as/controller/access/constraint/SensitivityClassification.java
  controller/src/main/java/org/jboss/as/controller/access/management/SensitiveTargetAccessConstraintDefinition.java
  controller/src/main/java/org/jboss/as/controller/descriptions/ModelDescriptionConstants.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionRegistry.java
  controller/src/main/java/org/jboss/as/controller/operations/common/ProcessReloadHandler.java
  controller/src/main/java/org/jboss/as/controller/remote/ModelControllerClientOperationHandler.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiGenericOperationHandler.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/DomainApiHandler.java
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/EarlyResponseTransactionControl.java
  server/src/main/java/org/jboss/as/server/Bootstrap.java
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/ServerService.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
  testsuite/elytron/src/test/java/org/wildfly/test/integration/elytron/sasl/mgmt/KerberosHttpMgmtSaslTestCase.java
  testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/PreparedResponseTestCase.java
  testsuite/shared/src/main/java/org/jboss/as/test/integration/management/util/ServerReload.java
  testsuite/shared/src/main/java/org/wildfly/test/snapshot/ServerSnapshot.java
  testsuite/shared/src/main/java/org/wildfly/test/stability/StabilityServerSetupSnapshotRestoreTasks.java
  testsuite/standalone/src/test/java/org/jboss/as/test/integration/security/perimeter/DisableLocalAuthServerSetupTask.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/stability/AbstractStabilityServerSetupTaskTest.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/stability/StabilityCommunityServerSetupTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/stability/StabilityDefaultServerSetupTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/stability/StabilityExperimentalServerSetupTestCase.java
  testsuite/standalone/src/test/java/org/wildfly/core/test/standalone/stability/StabilityPreviewServerSetupTestCase.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/WildFlyRunner.java
Labels: deps-ok

#5916 [WFCORE-6758] Upgrade WildFly Elytron to 2.4.0.CR1
  pom.xml
Labels: deps-ok

#5917 [WFCORE-6731] Expose supported stability levels via the management API
  controller/src/main/java/org/jboss/as/controller/operations/common/ProcessEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerEnvironment.java
  host-controller/src/main/java/org/jboss/as/host/controller/descriptions/HostEnvironmentResourceDefinition.java
  host-controller/src/main/resources/org/jboss/as/host/controller/descriptions/LocalDescriptions.properties
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/ServerEnvironmentResourceDescription.java
  server/src/main/resources/org/jboss/as/server/controller/descriptions/LocalDescriptions.properties
  version/src/main/java/org/jboss/as/version/ProductConfig.java
Labels: deps-ok

#5903 WFCORE-4868: implement aliases for standalone configuration files
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/test/java/org/jboss/as/server/ServerEnvironmentTestCase.java
Labels: deps-ok

#5921 Fix for WFCORE-6762, Upgrade to Galleon 6.0.0.Beta5 and Galleon Plugins 7.0.0.Beta6
  core-feature-pack/galleon-feature-pack/pom.xml
  pom.xml
Labels: deps-ok
