Repository wildfly/wildfly-core, pull requests merged in 2024-04, with the labels that each got.

#5930 WFCORE-6768 Fix goofy WriteAttributeTranslationOperationStepHandler class name
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptorRegistrar.java
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/WriteAttributeTranslationOperationStepHandler.java
Labels: ready-for-merge, deps-ok

#5929 WFCORE-6767 ServiceDependency interface is missing QuaternaryServiceDescriptor factory method
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java
Labels: ready-for-merge, deps-ok

#5928 [WFCORE-6766] Do not ignore --stability argument when thre is only on…
  host-controller/src/main/java/org/jboss/as/host/controller/Main.java
  server/src/main/java/org/jboss/as/server/Main.java
Labels: ready-for-merge, deps-ok

#5933 WFCORE-6769 Port NaryServiceNameFactory logic from wildfly-clustering-common to ServiceNameFactory
  controller/src/main/java/org/jboss/as/controller/ServiceNameFactory.java
Labels: ready-for-merge, deps-ok

#5935 [WFCORE-6772] Make the installation-manager script POSIX compatable
  core-feature-pack/common/src/main/resources/content/bin/installation-manager.sh
Labels: ready-for-merge, deps-ok

#5934 [WFCORE-6771]: Fixing several small issues with the YAML extension.
  controller/src/main/java/org/jboss/as/controller/ModelControllerImpl.java
  controller/src/main/java/org/jboss/as/controller/RunningModeControl.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/persistence/BackupXmlConfigurationPersister.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationExtension.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationPersister.java
  controller/src/main/java/org/jboss/as/controller/persistence/NullConfigurationPersister.java
  controller/src/main/java/org/jboss/as/controller/persistence/XmlConfigurationPersister.java
  controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
  controller/src/test/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtensionTest.java
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/deployment.yml
  controller/src/test/resources/org/jboss/as/controller/persistence/yaml/failed_deployment.yml
  launcher/src/main/java/org/wildfly/core/launcher/BootableJarCommandBuilder.java
  launcher/src/test/java/org/wildfly/core/launcher/CommandBuilderTest.java
  model-test/src/main/java/org/jboss/as/model/test/StringConfigurationPersister.java
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/controller/resources/ServerRootResourceDefinition.java
  server/src/main/java/org/jboss/as/server/operations/ServerDomainProcessReloadHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/persistence/yaml/YamlExtensionTestCase.java
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/bootable-groups.properties
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/bootable-users.properties
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-adding-empty-extension.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-adding-extension-path-deployment-overlay-ignored.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-indentation-wrong.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-list-add-operation-to-non-existent-resource.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-list-add-operation-to-string-fails.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-non-existent-resource.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-operations.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-port-offset-override.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-remove-attribute-removes-above-resource.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-remove-non-existent-resource.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-remove-socket.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-replacing-by-empty-resource.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-setting-non-existent-attribute.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-socket-override.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test-undefine-non-existent-attribute.yml
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test.cli
  testsuite/manualmode/src/test/resources/org/jboss/as/test/manualmode/management/persistence/yaml/test.yml
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/Server.java
  testsuite/test-runner/src/main/java/org/wildfly/core/testrunner/ServerController.java
Labels: ready-for-merge, deps-ok

#5911 [WFCORE-6749] Fix incorrect output from standalone.sh -v
  server/src/main/java/org/jboss/as/server/Main.java
Labels: ready-for-merge, deps-ok

#5940 [WFCORE-6773] Read the permitted stability levels from the server rat…
  testsuite/shared/src/main/java/org/wildfly/test/stability/StabilityServerSetupSnapshotRestoreTasks.java
Labels: ready-for-merge, deps-ok

#5943 [WFCORE-6775] Upgrade Eclipse Parsson from 1.1.5 to 1.1.6
  pom.xml
Labels: ready-for-merge, deps-ok

#5945 [WFCORE-6753] Make ServerEnvironment.setStability() package protected
  server/src/main/java/org/jboss/as/server/ServerEnvironment.java
  server/src/main/java/org/jboss/as/server/ServerEnvironmentAwareProcessReloadHandler.java
  server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
Labels: ready-for-merge, deps-ok

#5926 WFCORE-6765 Schema version comparison should require compatible stability level
  controller/src/main/java/org/jboss/as/controller/xml/SimpleVersionedNamespace.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedFeature.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedNamespace.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedSchema.java
  controller/src/main/java/org/jboss/as/controller/xml/VersionedURN.java
  controller/src/test/java/org/jboss/as/controller/xml/VersionedNamespaceTestCase.java
Labels: ready-for-merge, deps-ok, 24.x

#5949 WFCORE-6781 Port composite ResourceOperationServiceHandler logic from wildfly-clustering-common
  subsystem/src/main/java/org/wildfly/subsystem/resource/operation/ResourceOperationRuntimeHandler.java
Labels: ready-for-merge, deps-ok

#5944 Fix for WFCORE-6776, Can't specify a stability level when starting a bootable JAR.
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/Arguments.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableJar.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/CmdUsage.java
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/_private/BootableJarLogger.java
Labels: ready-for-merge, deps-ok

#5818 WFCORE-6347 Add ServiceDescriptor variants of OperationContext.hasOptionalCapability(...) and CapabilityServiceSupport.hasCapability(...)
  controller/src/main/java/org/jboss/as/controller/OperationContext.java
  controller/src/main/java/org/jboss/as/controller/OperationContextImpl.java
  controller/src/main/java/org/jboss/as/controller/capability/CapabilityServiceSupport.java
  controller/src/test/java/org/jboss/as/controller/SocketCapabilityResolutionUnitTestCase.java
  remoting/subsystem/src/main/java/org/jboss/as/remoting/management/ManagementRemotingServices.java
Labels: ready-for-merge, deps-ok, 24.x

#5948 [WFCORE-6777] Do not allow mixed domains for preview and experimental…
  host-controller/src/main/java/org/jboss/as/host/controller/logging/HostControllerLogger.java
  host-controller/src/main/java/org/jboss/as/host/controller/mgmt/HostControllerRegistrationHandler.java
Labels: ready-for-merge, Blocker, deps-ok

#5956 [WFCORE-6780] Upgrade WildFly Elytron to 2.4.0.Final for CVE-2024-1233 and CVE-2023-6236
  elytron/pom.xml
  elytron/src/main/java/org/wildfly/extension/elytron/TokenRealmDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
  elytron/src/test/java/org/wildfly/extension/elytron/JwtSecurityRealmTestCase.java
  elytron/src/test/resources/org/wildfly/extension/elytron/jwt-realm-test.xml
  pom.xml
Labels: ready-for-merge, deps-ok, 24.x

#5951 [WFCORE-6783] Upgrade JBoss VFS to 3.3.2.Final
  pom.xml
Labels: deps-ok

#5952 [WFCORE-6784] Upgrading JBoss MSC to 1.5.4.Final
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/msc/main/module.xml
  pom.xml
Labels: deps-ok

#5953 [WFCORE-6785] Upgrade JBoss Modules to 2.1.5.Final
  pom.xml
Labels: deps-ok

#5946 [WFCORE-6757] Clean up ServiceBuilder references in AuthenticationClientDefinitions#performRuntime
  elytron/src/main/java/org/wildfly/extension/elytron/AuthenticationClientDefinitions.java
Labels: ready-for-merge, deps-ok, 24.x

#5955 WFCORE-6786 Port CredentialSourceDependency from wildfly-clustering-common
  controller/src/main/java/org/jboss/as/controller/security/CredentialReference.java
  service/src/main/java/org/wildfly/service/ServiceDependency.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceDependency.java
Labels: ready-for-merge, deps-ok, 24.x

#5961 [WFCORE-6789] Replace obsolote usage of jboss.server.deploy.dir in Bo…
  bootable-jar/runtime/src/main/java/org/wildfly/core/jar/runtime/BootableEnvironment.java
Labels: ready-for-merge, deps-ok, 24.x

#5963 Fix for WFCORE-6790, Upgrade wildfly-maven-plugin to 5.0.0.Final and wildfly-jar-maven-plugin to 11.0.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok, 24.x

#5941 [WFCORE-6756] Subsystem model bump and transformer adjustments needed for the dynamic SSLContext support
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronExtension.java
  elytron/src/main/java/org/wildfly/extension/elytron/ElytronSubsystemTransformers.java
Labels: ready-for-merge, Blocker, deps-ok, 24.x

#5965 WFCORE-6792 Rename Installer.Builder.async() -> Installer.Builder.blocking()
  service/src/main/java/org/wildfly/service/Installer.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
Labels: ready-for-merge, deps-ok, 24.x

#5942 [WFCORE-6774][CVE-2024-29857][CVE-2024-30171][CVE-2024-30172] Upgrade BouncyCastle from 1.77 to 1.78
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/bouncycastle/bcpg/main/module.xml
  pom.xml
Labels: ready-for-merge, Blocker, deps-ok, 24.x

#5967 [WFCORE-6560] Test of logging installation provisioning information a…
  testsuite/manualmode/pom.xml
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/provisioning/InstallationManagerBootTestCase.java
  testsuite/shared/src/main/java/org/wildfly/test/installationmanager/TestInstallationManager.java
Labels: ready-for-merge, deps-ok, 24.x

#5971 [WFCORE-6794] CVE-2023-1973 Upgrade Undertow to 2.3.13.Final
  pom.xml
Labels: ready-for-merge, Blocker, deps-ok, 24.x

#5969 [WFCORE-6560] Remove test exclusion cruft
  testsuite/manualmode/pom.xml
Labels: ready-for-merge, deps-ok, 24.x

#5973 [WFCORE-6796] Upgrade WildFly Elytron to 2.4.1.Final
  pom.xml
Labels: ready-for-merge, deps-ok, 24.x

#5978 [WFCORE-5386] Revert "[WFCORE-5922] Ignore RemotingLegacySubsystemTestCase#testSubsystemWithConnectorPropertyChange test case"
  pom.xml
  remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java
Labels: ready-for-merge, deps-ok, 24.x

#5977 [WFCORE-6738] CVE-2023-5685 Upgrade XNIO to 3.8.14.Final
  pom.xml
Labels: ready-for-merge, Blocker, deps-ok, 24.x

#5972 [WFCORE-6795] Upgrade wildfly-discovery to 1.3.0.Final
  pom.xml
Labels: ready-for-merge, deps-ok, 25.x

#5974 [WFCORE-6797] Upgrade BouncyCastle from 1.78 to 1.78.1
  pom.xml
Labels: ready-for-merge, deps-ok

#5975 [WFCORE-6799] Upgrade SLF4J from 2.0.12 to 2.0.13
  pom.xml
Labels: ready-for-merge, deps-ok, test-only-dep

#5976 [WFCORE-6801] Use maven.compiler.release to ensure the desired binary…
  pom.xml
Labels: ready-for-merge, deps-ok

#5979 [WFCORE-6803] Bump the kernel management API version to 26.0.0
  host-controller/src/main/java/org/jboss/as/domain/controller/resources/HostExcludeResourceDefinition.java
  host-controller/src/main/java/org/jboss/as/domain/controller/transformers/KernelAPIVersion.java
  version/src/main/java/org/jboss/as/version/Version.java
Labels: ready-for-merge, deps-ok

#5983 WFCORE-6792 Fix missing CapabilityServiceInstaller.Builder.async() -> blocking().
  subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java
Labels: deps-ok

#5984 WFCORE-6792 Fix missing CapabilityServiceInstaller.Builder.async() ->blocking().
  subsystem/src/main/java/org/wildfly/subsystem/service/capability/CapabilityServiceInstaller.java
Labels: 24.x

#5981 WFCORE-6806 Add method to combine multiple DeploymentServiceInstaller
  subsystem/src/main/java/org/wildfly/subsystem/service/DeploymentServiceInstaller.java
Labels: ready-for-merge, deps-ok
