Repository wildfly/wildfly-core, pull requests merged in 2024-05, with the labels that each got.

#5985 WFCORE-6808 Add capability-resolving variant of child ServiceTarget-based ServiceInstaller.Builder
  controller/src/main/java/org/jboss/as/controller/RequirementServiceTarget.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentUnitPhaseService.java
  subsystem/src/main/java/org/wildfly/subsystem/service/ServiceInstaller.java
Labels: ready-for-merge, deps-ok

#5986 [WFCORE-6811] Remove configuration stability level from WildFly Core …
  core-feature-pack/galleon-feature-pack/wildfly-feature-pack-build.xml
Labels: ready-for-merge, deps-ok

#5988 [WFCORE-6814] Adjusting ContentRepositoryTest to be functional on all JDKs on Fedora 40
  deployment-repository/src/test/java/org/jboss/as/repository/ContentRepositoryTest.java
Labels: ready-for-merge, deps-ok

#5990 WFCORE-6817 Operation parameters and reply attributes not enabled by the current stability level still appear in the resource description
  controller/src/main/java/org/jboss/as/controller/SimpleOperationDefinitionBuilder.java
Labels: ready-for-merge, deps-ok

#5989 WFCORE-6816 A resource with a deployment chain contributor should require restarting all services on removal
  subsystem/src/main/java/org/wildfly/subsystem/resource/ResourceDescriptor.java
Labels: ready-for-merge, deps-ok

#5994 WFCORE-6824 ServiceNameFactory.resolveServiceName(UnaryServiceDescriptor) throws ISE if resolved to a NullaryServiceDescriptor
  controller/src/main/java/org/jboss/as/controller/ServiceNameFactory.java
Labels: ready-for-merge, deps-ok

#5996 [WFCORE-6700][WFCORE-5753][WFCORE-6488] Introduce new version of WildFly Legacy Tests
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  model-test/src/main/java/org/jboss/as/model/test/ModelTestControllerVersion.java
  pom.xml
Labels: ready-for-merge, deps-ok

#5998 [WFCORE-6700] Minor Java Doc fix
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
Labels: deps-ok

#5993 [WFCORE-6823] Don't register the Jakarta AuthConfigFactory in the host controller.
  core-feature-pack/galleon-common/src/main/resources/feature_groups/host-profile.xml
Labels: ready-for-merge, deps-ok

#6001 [WFCORE-6831] Upgrade WildFly Elytron to 2.4.2.Final
  pom.xml
Labels: ready-for-merge, deps-ok

#6002 [WFCORE-6831] Upgrade WildFly Elytron to 2.4.2.Final
  pom.xml
Labels: 24.x

#6006 [WFCORE-6832] Wrong arguments to standalone.sh may lead to server content removal
  server/src/main/java/org/jboss/as/server/controller/git/GitRepository.java
  server/src/test/java/org/jboss/as/controller/persistence/RemoteGitPersistenceResourceTestCase.java
Labels: ready-for-merge, deps-ok

#6003 [24.x] [CVE-2024-4029] [WFCORE-6825] Options to control resources used for incomming connections.
  domain-http/interface/src/main/java/org/jboss/as/domain/http/server/ManagementHttpServer.java
  server/src/main/java/org/jboss/as/server/mgmt/UndertowHttpManagementService.java
  testsuite/manualmode/src/test/java/org/wildfly/core/test/standalone/mgmt/ManagementInterfaceResourcesTestCase.java
Labels: Blocker, 24.x
