Repository wildfly/wildfly-core, pull requests merged in 2024-12, with the labels that each got.

#6243 [WFCORE-7056] Upgrade SSHD from 2.13.2 to 2.14.0
  pom.xml
Labels: ready-for-merge

#6269 [WFCORE-7071] / [WFCORE-7072] Elytron EE 3.1.1.Final and use the new PolicyUtil to manage the java.security.Policy object
  elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
  pom.xml
Labels: ready-for-merge, Critical, 27.x

#6271 WFCORE-7083 ModuleNameValidator fails if module name contains a dash
  controller/src/main/java/org/jboss/as/controller/operations/validation/ModuleNameValidator.java
  controller/src/test/java/org/jboss/as/controller/operations/global/AbstractCollectionOperationsTestCase.java
  controller/src/test/java/org/jboss/as/controller/operations/global/CollectionOperationsTestCase.java
  controller/src/test/java/org/jboss/as/controller/operations/global/EnhancedSyntaxTestCase.java
  controller/src/test/java/org/jboss/as/controller/operations/global/StorageRuntimeCollectionOperationsTestCase.java
  controller/src/test/java/org/jboss/as/controller/operations/validation/ModelTypeValidatorUnitTestCase.java
  controller/src/test/java/org/jboss/as/controller/operations/validation/ModuleNameValidatorTestCase.java
Labels: ready-for-merge

#6273 [WFCORE-7084] Upgrade Installation Manager API to 1.1.0.Final
  pom.xml
Labels: ready-for-merge

#6270 [WFCORE-7082] Provide utilities to produce canonical representations …
  controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java
Labels: ready-for-merge

#6066 [WFCORE-6755] Move the org.wildfly.security:wildfly-elytron-dynamic-ssl artifact into its own module
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-base/main/module.xml
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/security/elytron-dynamic-ssl/main/module.xml
  core-feature-pack/galleon-common/src/main/resources/layers/standalone/elytron/layer-spec.xml
  elytron/src/main/java/org/wildfly/extension/elytron/DynamicSSLContextHelper.java
  elytron/src/main/java/org/wildfly/extension/elytron/SSLDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/TrivialResourceDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/_private/ElytronSubsystemMessages.java
Labels: ready-for-merge, deps-ok, 27.x

#6279 [WFCORE-7089] When setting a policy in the PolicyDefinitions do not a…
  elytron/src/main/java/org/wildfly/extension/elytron/PolicyDefinitions.java
Labels: ready-for-merge, Blocker, 27.x

#6247 [WFCORE-3720] Update ServiceModuleLoader to use non-deprecated JBoss Modules APIs
  server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleExtensionListProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExtensionIndexService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ExternalModuleSpecService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleResolvePhaseService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
Labels: ready-for-merge

#6284 [WFCORE-7093] Upgrade WildFly Legacy Tests to 9.0.0.Final
  core-model-test/tests/src/test/java/org/jboss/as/core/model/test/util/TransformersTestParameter.java
  elytron/src/test/java/org/wildfly/extension/elytron/SubsystemTransformerTestCase.java
  pom.xml
Labels: ready-for-merge

#6281 [WFCORE-7094] Fix remaining incorrect calls to ModuleIdentifier.getNa…
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
  server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java
Labels: ready-for-merge, Blocker, 27.x

#6286 Fix for WFCORE-7101, Upgrade WildFly Maven Plugin to 5.1.0.Final
  pom.xml
Labels: ready-for-merge

#6285 [WFLY-7100] Use a concurrent set for ModuleSpecification.userDependen…
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
Labels: ready-for-merge, 27.x

#6291 [WFCORE-7106] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Logging
  logging/src/main/java/org/jboss/as/logging/deployments/LoggingDependencyDeploymentProcessor.java
Labels: ready-for-merge

#6289 [WFCORE-7104] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Elytron
  elytron/src/main/java/org/wildfly/extension/elytron/DependencyProcessor.java
  elytron/src/main/java/org/wildfly/extension/elytron/EESecurityDependencyProcessor.java
Labels: ready-for-merge

#6290 [WFCORE-7105] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Test Suite
  testsuite/unstable-api-annotation/feature-pack/subsystem/src/main/java/org/wildfly/core/test/unstable/api/annotation/classes/subsystem/UnstableApiAnnotationTestDependencyProcessor.java
Labels: ready-for-merge

#6301 [WFCORE-7095][WFCORE-7108][WFCORE-7111][WFCORE-7112][WFCORE-7113][WFCORE-7114] Module identifier in api fixes
  controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java
  controller/src/test/java/org/jboss/as/controller/ModuleIdentifierUtilUnitTestCase.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/DeploymentListModulesHandler.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/AdditionalModuleSpecification.java
  server/src/main/java/org/jboss/as/server/deployment/module/DeploymentVisibilityProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleAliasChecker.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleDependency.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleIdentifierProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleSpecification.java
  server/src/main/java/org/jboss/as/server/deployment/module/SubDeploymentDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleDefinition.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleLoadService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleResolvePhaseService.java
  server/src/main/java/org/jboss/as/server/moduleservice/ServiceModuleLoader.java
  server/src/test/java/org/jboss/as/server/deployment/module/ModuleDependencyUnitTestCase.java
  server/src/test/java/org/jboss/as/server/deployment/module/ModuleSpecificationTestCase.java
Labels: 27.x

#6293 [WFCORE-7108] Add a ModuleIdentifierUtil method to parse a module ide…
  controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java
  controller/src/test/java/org/jboss/as/controller/ModuleIdentifierUtilUnitTestCase.java
Labels: ready-for-merge

#6298 [WFCORE-7111] Prepare org.jboss.as.server.deployment.Attachments for …
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ModuleIdentifierProcessor.java
Labels: ready-for-merge

#6299 [WFCORE-7112] Deprecate PermissionsParser.parse that takes ModuleIden…
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParser.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/deployment/PermissionsParserProcessor.java
Labels: ready-for-merge

#6300 [WFCORE-7113] Deprecate AdditionalModuleSpecification.getModuleIdenti…
  server/src/main/java/org/jboss/as/server/deployment/module/AdditionalModuleSpecification.java
Labels: ready-for-merge

#6302 [WFCORE-7114] Deprecate use of ModuleIdentifier in ModuleDefinition
  server/src/main/java/org/jboss/as/server/moduleservice/ModuleDefinition.java
Labels: ready-for-merge
