Repository wildfly/wildfly-core, pull requests merged in 2025-01, with the labels that each got.

#6306 [WFCORE-7118] Provide an alternative to Attachments.ADDITIONAL_ANNOTATION_INDEXES
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/DeploymentStructureDescriptorParser.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser10.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser11.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser12.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/JBossDeploymentStructureParser13.java
  server/src/main/java/org/jboss/as/server/deployment/module/descriptor/ModuleStructureSpec.java
  server/src/main/java/org/jboss/as/server/logging/ServerLogger.java
Labels: 28.x

#6319 [WFCORE-7131] Upgrading JBoss Marshalling to 2.2.2.Final
  pom.xml
Labels: ready-for-merge, 27.x

#6309 [WFCORE-7124] Remove use of server-side Stability type from the CLI
  cli/pom.xml
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedHostControllerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/EmbedServerHandler.java
  cli/src/main/java/org/jboss/as/cli/embedded/Stability.java
  core-feature-pack/common/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
Labels: ready-for-merge

#6311 [WFCORE-7126] Remove cruft testsuite/server-provisioning.xml
  testsuite/server-provisioning.xml
Labels: ready-for-merge

#6320 [WFCORE-7134] Remove ModuleIdentifier use in the elytron subsystem
  elytron/src/main/java/org/wildfly/extension/elytron/ClassLoadingAttributeDefinitions.java
  elytron/src/main/java/org/wildfly/extension/elytron/DirContextDefinition.java
  elytron/src/main/java/org/wildfly/extension/elytron/PermissionMapperDefinitions.java
Labels: ready-for-merge

#6297 [WFCORE-7110] Deprecate the security manager subsystem and report it will be removed in a future release.
  security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerExtension.java
  security-manager/src/main/java/org/wildfly/extension/security/manager/SecurityManagerRootDefinition.java
  security-manager/src/main/resources/org/wildfly/extension/security/manager/LocalDescriptions.properties
Labels: ready-for-merge

#6304 [WFCORE-7116] Remove ModuleIdentifier from Extension handling
  cli/src/main/java/org/jboss/as/cli/impl/ExtensionsLoader.java
  controller-client/src/main/java/org/jboss/as/controller/client/helpers/JBossModulesNameUtil.java
  controller-client/src/test/java/org/jboss/as/controller/client/helpers/JBossModulesNameUtilUnitTestCase.java
  controller/src/main/java/org/jboss/as/controller/ModuleIdentifierUtil.java
  controller/src/main/java/org/jboss/as/controller/extension/ExtensionAddHandler.java
  controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
  controller/src/main/java/org/jboss/as/controller/parsing/DeferredExtensionContext.java
  controller/src/main/java/org/jboss/as/controller/parsing/ExtensionXml.java
  controller/src/main/java/org/jboss/as/controller/transform/TransformerRegistry.java
  host-controller/src/main/java/org/jboss/as/domain/controller/operations/ApplyExtensionsHandler.java
Labels: ready-for-merge

#6327 [WFCORE-7151] Upgrade WildFly Galleon Plugins to 7.3.1.Final
  pom.xml
Labels: ready-for-merge

#6328 [WFCORE-7150] Remove deprecated Attachments.ADDITIONAL_ANNOTATION_IND…
  server/src/main/java/org/jboss/as/server/deployment/Attachments.java
  server/src/main/java/org/jboss/as/server/deployment/annotation/CompositeIndexProcessor.java
Labels: ready-for-merge

#6287 [WFCORE-7102]: AccessDeniedException on Windows when using a read-only
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFile.java
  controller/src/main/java/org/jboss/as/controller/persistence/ConfigurationFilePersistenceResource.java
  controller/src/main/java/org/jboss/as/controller/persistence/FilePersistenceUtils.java
  testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
Labels: ready-for-merge, 28.x

#6325 [WFCORE-7143] Consolidate HostControllerBootstrap and EmbeddedHostCon…
  host-controller/src/main/java/org/jboss/as/host/controller/AbstractHostControllerBootstrap.java
  host-controller/src/main/java/org/jboss/as/host/controller/HostControllerBootstrap.java
  host-controller/src/main/java/org/jboss/as/host/controller/embedded/EmbeddedHostControllerBootstrap.java
Labels: ready-for-merge
